### ISSUE TITLE
第69回 pupupopo, task, kiyamatic, katorie

### ISSUE THREAD

**Issue by katorie** [yochiyochirb/meetups#1004]
6.2.3長さを検証するから？
お名前間違えてたらセルフ編集お願いします！

**Comment by pupupopo88** [comment]
:ok_woman:

**Comment by katorie** [comment]
何も書くことないということは理解が進んでいるということ！？

**Comment by pupupopo88** [comment]
公式ドキュメント：validation
http://railsdoc.com/validation

**Comment by kiyamatic** [comment]
do　の数だけ end　がある

**Comment by TasukuNakano** [comment]
%wとは
http://docs.ruby-lang.org/ja/1.9.3/doc/spec=2fliteral.html#percent

**Comment by pupupopo88** [comment]
出逢い率！？

**Comment by TasukuNakano** [comment]
ぷぽさんはディスプレイを3枚使って仕事をしているらしい

**Comment by pupupopo88** [comment]
regex => れぐいーえっくす

**Comment by kiyamatic** [comment]
正規表現は難しすぎるわ

**Comment by katorie** [comment]
>  (注: リスト6.14の正規表現をRubularで使う場合、冒頭の\Aと末尾の\zの文字は含めないでください)

?

**Comment by pupupopo88** [comment]
正規表現実践入門、4/14に発売されたばかりです
http://www.amazon.co.jp/dp/4774172707

**Comment by pupupopo88** [comment]
表6.1のところまで終わりました
http://railstutorial.jp/chapters/modeling-users?version=4.0#table-valid_email_regex

**Comment by yucao24hours** [comment]
ヤバイ interactive regexp tutorial
http://regexone.com/

**Comment by ManabuSeki** [comment]
ドリルしようと思ってます

http://www.amazon.co.jp/%E5%8F%8D%E5%BE%A9%E5%AD%A6%E7%BF%92%E3%82%BD%E3%83%95%E3%83%88%E4%BB%98%E3%81%8D-%E6%AD%A3%E8%A6%8F%E8%A1%A8%E7%8F%BE%E6%9B%B8%E3%81%8D%E6%96%B9%E3%83%89%E3%83%AA%E3%83%AB-WEB-PRESS-plus/dp/4774145092
