### ISSUE TITLE
第71回 ohtsuka, odailly, katorie

### ISSUE THREAD

**Issue by katorie** [yochiyochirb/meetups#1006]

**Comment by to0526** [comment]
\w 単語構成文字 [a-zA-Z0-9_]

**Comment by odaillyjp** [comment]
```ruby
/[\-]/
```
ハイフンの前にバックスラッシュは必要でしたっけ？

**Comment by to0526** [comment]
`[\w+-.]+`、`[\w+\-.]+`
ハイフンの前にバックスラッシュはあってもなくても良さそう

**Comment by odaillyjp** [comment]
```ruby
/[+-.]+/.match(',')
# => マッチする

/[+\-.]+/.match(',')
# => マッチしない
```

**Comment by to0526** [comment]
ドットはバックスラッシュいらない？

括弧で囲ってたらいらなそう

**Comment by to0526** [comment]
/pat/i 大文字小文字を無視する
/pat/m メタ文字「.」が改行にマッチするようになる
/pat/x コメント内の空白を無視する。コメントの仕様が変化する
/pat/o パターン内の #{} の展開を1回限りしかしない。

**Comment by to0526** [comment]
oオプションとは

**Comment by katorie** [comment]
有効な使い道がわからないけど…

**Comment by odaillyjp** [comment]
```ruby
['a', 'b', 'c'].each do |x|
  if /#{x}/o =~ x
    puts x
  end
end
# => a
```

**Comment by to0526** [comment]
速度的なものが必要であれば使う…？

「分からんかったら使うな」らしい

**Comment by odaillyjp** [comment]
メールアドレスのローカル部に使用できる文字

http://ja.wikipedia.org/wiki/%E3%83%A1%E3%83%BC%E3%83%AB%E3%82%A2%E3%83%89%E3%83%AC%E3%82%B9

**Comment by to0526** [comment]
99.9％のメールドレスにマッチする正規表現
http://www.softantenna.com/wp/webservice/email-regular-expression/

**Comment by to0526** [comment]
http://ejje.weblio.jp/content/case-sensitive

**Comment by katorie** [comment]
どじっこアリスのお話が終わったところまでです
