### ISSUE TITLE
第71回 yucao24hours, hirozaki, manabuseki, highwide

### ISSUE THREAD

**Issue by highwide** [yochiyochirb/meetups#1007]
「6.2.5一意性を検証する」から

**Comment by yucao24hours** [comment]
hi

**Comment by highwide** [comment]
http://ref.xaio.jp/ruby/classes/object/clone

**Comment by ManabuSeki** [comment]
hi

**Comment by highwide** [comment]
`bundle exec rspec` だと通るが、`rspec` だと落ちる。
-> 単なる `rspec` だと、自分のMacにグローバルにインストールしたrspec gemを使っているのでは？

**Comment by ManabuSeki** [comment]
```
bundle exec rspec
```
と
```
bundle exec rake spec
```
で動きが違うみたい

**Comment by yucao24hours** [comment]
何度見ても `uniqueness` が `upinetree` に見えて仕方ない

**Comment by upinetree** [comment]
|дﾟ)ﾁﾗｯ

**Comment by yucao24hours** [comment]
|冫､)ｼﾞｰ

**Comment by highwide** [comment]
![見ているな](http://pic.prepics-cdn.com/16000915/33222354.jpeg)

**Comment by yucao24hours** [comment]
http://railstutorial.jp/chapters/modeling-users?version=4.0#code-email_downcase までいきました！

**Comment by upinetree** [comment]
![](http://livedoor.blogimg.jp/yasu006/imgs/7/9/79e5f97f.jpg)

**Comment by highwide** [comment]
リスト6.20 email属性を小文字に変換してメールアドレスの一意性を保証する。
まで
