### ISSUE TITLE
よちよち.rb は今後どうなっていくのか、どうしていきたいか

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#1016]
2015/06/01のミートアップは、私のお願いで急きょ Rails チュートリアル会ではなく「よちよち.rb のこれからのミートアップについて」を話し合う日にさせていただきました。

その話し合いのときに Google Docs をみんなで一緒に編集しながら意見を出していったので、当日いらっしゃらなかった方でも編集・閲覧ができるようにこちらに置いておきます。
（まさか起きないとは思いますが、改ざんとかはしないでくださいね。したとしても履歴は残ります！）

https://docs.google.com/document/d/1IDbO_sZv9mJS8szAbhmMy8_XAmsywt7XGdRZavvKiF4/edit?usp=sharing

この issue はタスクの一覧のために立てています。関連する話題についてはこちらにコメントをつけていただいても、Idobata で話す形にしても構いません。
今後どうするかが決まり次第 close します。

**Comment by to0526** [comment]
> 今後どうするかが決まり次第 close します。

いつまでに決めたいか、というのを共有しておいた方が良いかと思いました！（昨日のミートアップで仰っていたように「来週の半ばくらいまで」ですかね？）

**Comment by yucao24hours** [comment]
そうでした。次の Rails チュートリアル会の準備に具体的にとりかかる前まで、すなわち来週の半ばくらいまでにひとまず直近の方針を決めます。（来週月曜日はもくもく会なので次の Rails チュートリアル会は再来週）

**Comment by yucao24hours** [comment]
しばらくの間、「なにも決めないでまず集まってみて、その日のその場でやりたいことをやる」という内容でやってみようということにしました。それはそれでいろんなことができそうで楽しそう。

**Comment by yucao24hours** [comment]
2ヶ月くらいたつけど、毎回けっこうおもしろいのでこのかんじでいこうと思いました。また、おもしろいことを思いついたらそれを随時取り入れていきましょう！ご協力ありがとうございました :pray:
