### ISSUE TITLE
banmasa.md

### ISSUE THREAD

**Issue by BanMasanobu** [yochiyochirb/meetups#1030]
## 自己紹介
名前：伴　正信
Slerでクラウドサービスのコントロールパネル(AWSみたいなやつ)をRailsを作っています。現在、1年程度です。
http://www.intec.co.jp/service/detail/eins_sps_s/

## Ruby on Rails とわたし
__ステータスは3(ほんば)です。__

## Git, Github
__ステータスは2(ふたば)です。__

趣味は格闘技とバスケです

**Comment by yucao24hours** [comment]
こちら、 PR と間違えてしまったんですよね、きっと。
すみませんが close させていただきますね :bow:
