### ISSUE TITLE
どの位の単位でメソッドとか分けていますか？

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#1037]
メソッドをつくるときに心がけていること、「こういうふうになったらメソッドに切り出すタイミングだ！」ということ、などがあればおしえてください。

**Comment by yuzoiwasaki** [comment]
同じ処理、似たような処理を複数回書いたりしている時は共通部分を切り出してメソッド化しますかねー。

**Comment by yucao24hours** [comment]
#729 の方針にのっとり、現時点でアクティブでなさそうな issue についてはひとまず close させていただきました。
ただし、「今後これの話はいっさいしないで！」というわけではなく、あくまでも **今** ホットなものを open のステータスにしておきたいという私の希望からであって、他意はまったくありません。
私以外のどなたかが「これ必要！」と思った場合はぜひ遠慮なく reopen してくださいね :rose:
