### ISSUE TITLE
Ruby の勉強にオススメな書籍をおしえてください！

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#1038]
"現在ドットインストールでRubyの勉強をしているが、書籍だとどれがオススメなのか。（たのしいRubyなどがAmazonでは評価が高いが実際はどうなのか）"

**Comment by yucao24hours** [comment]
"とっかかりとしては、わかりやすい！慣れて理解していったら、Web 上で情報を見つける、という使いかたができる。"

**Comment by yucao24hours** [comment]
だっちさんは "コードの世界" http://www.amazon.co.jp/dp/4822234312 だそうです！

**Comment by yucao24hours** [comment]
わたしは最近ようやくこれを買いました [初めてのRuby](http://www.amazon.co.jp/dp/4873113679 )

**Comment by yucao24hours** [comment]
[初めてのプログラミング 第2版](http://www.amazon.co.jp/dp/4873114691) こちらはプログラミング初心者向けの本だそうですが、説明のために Ruby を使っているそうです :relaxed: by おがたさん

**Comment by ta1kt0me** [comment]
作りながら学べる系で、[Rubyによるクローラー開発技法 　巡回・解析機能の実装と21の運用例](http://www.amazon.co.jp/Ruby%E3%81%AB%E3%82%88%E3%82%8B%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%A9%E3%83%BC%E9%96%8B%E7%99%BA%E6%8A%80%E6%B3%95-%E3%80%80%E5%B7%A1%E5%9B%9E%E3%83%BB%E8%A7%A3%E6%9E%90%E6%A9%9F%E8%83%BD%E3%81%AE%E5%AE%9F%E8%A3%85%E3%81%A821%E3%81%AE%E9%81%8B%E7%94%A8%E4%BE%8B-%E4%BD%90%E3%80%85%E6%9C%A8-%E6%8B%93%E9%83%8E-ebook/dp/B00TO6KMEK/ref=sr_1_6?s=books&ie=UTF8&qid=1434778009&sr=1-6&keywords=Ruby)とか

**Comment by yucao24hours** [comment]
[作りながら学ぶRuby入門 第2版](http://www.amazon.co.jp/dp/B00GJGOPU0) もたしかどなたかが以前教えてくださった記憶が

**Comment by yucao24hours** [comment]
他の言語を触った経験があって、あらたに Ruby をはじめるのであれば、 (Ruby徹底攻略 (WEB+DB PRESS plus))[http://www.amazon.co.jp/dp/4774165344] もよいとのこと :+1: by いわさきさん

**Comment by yucao24hours** [comment]
#729 の方針にのっとり、現時点でアクティブでなさそうな issue についてはひとまず close させていただきました。
ただし、「今後これの話はいっさいしないで！」というわけではなく、あくまでも **今** ホットなものを open のステータスにしておきたいという私の希望からであって、他意はまったくありません。
私以外のどなたかが「これ必要！」と思った場合はぜひ遠慮なく reopen してくださいね :rose: 
特にこちらの issue については、今後情報があり次第コメントを追加してメモを残していくのもいいかもしれませんね。（そういう用途なら wiki にしてもいいのか）

**Comment by yucao24hours** [comment]
というわけで wiki にしてみました！
https://github.com/yochiyochirb/meetups/wiki/books-to-learn-ruby
