### ISSUE TITLE
Proc や lambda の使い所ってどんなところ？

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#1049]
"Procやlambdaの使い所がよくわかりません。実コードでこんな時便利みたいな例があれば知りたいです。"

**Comment by yucao24hours** [comment]
わたしは Ruby エンジニアというより Rails エンジニアなので、Rails の中でのコードになりますが、たとえばログイン・ログアウトの際の処理をする `UserSessionsController` というのがあったとき（`destroy` でログアウトを、`create` でログインできるかどうかの処理をするような実装のやつ）、

```ruby
before_action -> { redirect_to root_path }, if: :logged_in?, except: :destroy
```

みたいなフックを書いたりすることができますね。

**Comment by ManabuSeki** [comment]
lambda(ラムダ？)ってmodelの中でwhere文とかの条件に使った以外あまり使ったことないです

コントロールに書くと…
```
@user = User.where(:name => params[:name])
```
でも、こういうのはモデルに書きたいヘ(^o^)ノ

Userモデル 
```
class User < ActiveRecord::Base
  scope :search, lambda { |name|
    where("name = ?", "#{name}") 
  }
end
```
使い方はこんな感じ 
```
@user = User.search
```

引用元：
http://murajun1978-pg.blogspot.jp/2012/10/rails-scope.html

**Comment by 5t111111** [comment]
ちょっと極端ですが、Proc も lambda も、処理のまとまりに可搬性を持たせるために利用するものだと思っています。もっと具体的に言うと、「メソッド」と「ブロック」に可搬性を持たせたいときに使えます。「可搬性」というのは、普通のオブジェクトみたいな扱いができるようにすると捉えてもらって構いません。

上で回答してくれている2つの例は、いずれもlambdaを使うことで『メソッドの引数として処理のまとまりを渡す』ことを実現しています。メソッドに対して処理のまとまりを渡したいとき、通常はブロックを使いますよね。`users.each { |user| ... }` みたいな。上記で `before_action -> { redirect_to root_path } ...` としてlambdaを `before_action` メソッドに渡しているのは、`users.each { |user| ... }` でメソッドにブロックを渡しているのと (厳密には別物ですが) 、メソッドに『処理のまとまりを渡す』という意味で論理的には同じことをしていると言って良いと思います。

では、可搬性を持たせる、とはもっと具体的な例ではどういうものか。

一番単純なパターンは、単純に処理のまとまりを定義するために Proc や lambda を定義することです。

```ruby
shouhin_1 = 100
shouhin_2 = 200
shouhin_3 = 300

a = -> (price) { (price * 1.08).round }

zeikomi_keisan = a

puts zeikomi_keisan.call(shouhin_1) #=> 108
puts zeikomi_keisan.call(shouhin_2) #=> 216
puts zeikomi_keisan.call(shouhin_3) #=> 324
puts zeikomi_keisan.class #=> Proc
```

`-> (price) { (price * 1.08).round }` と、lambdaを使って処理をProcオブジェクトとして定義することで、処理のまとまりを変数 `a` という変数に代入して可搬性を持って扱うことができています。`a` はオブジェクトなので、`zeikomi_keisan = a`として別の変数に代入し、その上で `call` メソッドで処理を呼び出すことができています。

もう1つ例をあげます。詳細はコード中のコメントに書いているだけですが、エラー出力メソッドでエラーを出力したい場面を想定し、かつ、エラーの出力方法をメソッド呼び出し時に指定できるようにしたい (例では `puts` と `p`) というものです。処理のまとまりをProcオブジェクトとして扱うことで、可搬性を持たせることができているなー、という感じがするでしょうか。

```ruby
def output_error(&block) # ブロックをProcオブジェクトとして受け取っている
  error = 'やばいエラー' # 出力するエラー内容
  output_method = block # Procオブジェクトを他の変数に代入している。
  output_method.call(error) # Procオブジェクトでerrorをブロック引数として処理を実行している
  output_error_detail(output_method) # Procオブジェクトを引数にして別のメソッドを実行している
end

def output_error_detail(proc) # ブロックをProcオブジェクトとして受け取っている
  error_detail = 'やばいエラーの詳細はやっぱりやばい' # 出力する詳細エラー内容
  proc.call(error_detail) # Procオブジェクトでerror_detailをブロック引数として処理を実行している
end

 # エラー内容をputsで表示したい
output_error { |e| puts e }
#=> やばいエラー
#=> やばいエラーの詳細はやっぱりやばい

# エラー内容をpで表示したい
output_error { |e| p e }
#=> "やばいエラー"
#=> "やばいエラーの詳細はやっぱりやばい"

# lambdaを引数としてメソッドに渡すと…
output_error_detail -> (e) { puts e }
#=> やばいエラーの詳細はやっぱりやばい
```

**Comment by highwide** [comment]
「可搬性」という言葉でめっちゃなるほどと思いました。

**Comment by yuzoiwasaki** [comment]
なるほど〜。大変参考になりました！どうもありがとうございました！！

**Comment by yucao24hours** [comment]
#729 の方針にのっとり、現時点でアクティブでなさそうな issue についてはひとまず close させていただきました。（というかこちらの issue はもう解決してるからこれはこれでいいのかも？）

ただし、「今後これの話はいっさいしないで！」というわけではなく、あくまでも **今** ホットなものを open のステータスにしておきたいという私の希望からであって、他意はまったくありません。
私以外のどなたかが「これ必要！」と思った場合はぜひ遠慮なく reopen してくださいね :rose:
