### ISSUE TITLE
テンプレートエンジン、なにをつかってる？（Slim, Haml, erb など）

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#1050]
"（実務での）slim率とhaml率とerb率を知りたいです。あと、社内のコーディングルールが決まっていれば、会社によってどんなコーディングルールがあるのか聞いてみたいです。"

**Comment by yucao24hours** [comment]
わたしは入社してから今まで Haml 以外を実務で使ったことないです :pig:

**Comment by ManabuSeki** [comment]
僕は業務でerb使ってます
デザイナーさんが組み込みまでやってくださるのでerbです

**Comment by yucao24hours** [comment]
コーディングルール、って、どのレベルまでのことを言うかむずかしいですね。スペースは半角 n 個！とか、そういうことかな？？
この文脈では "ビューテンプレートでの" コーティングルールだと思いますが、http://www.jrayson.co.uk/blog/131118-mind-bem-ding-writing-modular-css
今のプロジェクトではこの MindBEMding でやってます。それまでのプロジェクトは、わたしがフロントをさわることがほとんどなかったので、わかりません :see_no_evil:

**Comment by to0526** [comment]
実務ではhamlばかりですね〜（少しだけslim使ったことありますが、hamlに慣れているので属性の書き方など少し違うところがあり戸惑った記憶があります）

**Comment by to0526** [comment]
コーディングルールですが、ビューに関しては特に決めてないですかね〜（hamlはインデントが重要なので自然とそれなりに綺麗になるからというのもあるかもしれません）

**Comment by to0526** [comment]
（なるべくviewにロジックは書かずにhelperやdecoratorに書くというのがありますが、これはコーディングルールじゃない気がします。が一応dumpしておきます）

**Comment by to0526** [comment]
情報共有として[haml-lint](https://github.com/brigade/haml-lint)というhaml版rubocopみたいなgemもあります

**Comment by yucao24hours** [comment]
そうですねー、ここでいう「コーディングルール」が具体的にどんなことを知りたいかがわかると、よりジャストミートな回答がゲットしやすくなりそう。（質問を挙げてくださったご本人見ていらしゃるかな... :eyes: ）

**Comment by yucao24hours** [comment]
#729 の方針にのっとり、現時点でアクティブでなさそうな issue についてはひとまず close させていただきました。
ただし、「今後これの話はいっさいしないで！」というわけではなく、あくまでも **今** ホットなものを open のステータスにしておきたいという私の希望からであって、他意はまったくありません。
私以外のどなたかが「これ必要！」と思った場合はぜひ遠慮なく reopen してくださいね :rose:
