### ISSUE TITLE
第78回（7/6 開催）で使用する Gist 回収場所

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#1066]
自己紹介で使う Gist の URL を、ここのコメントに貼っていってください :rabbit:

# 必ず書いておいてほしい内容
* お名前
* ご職業
* 右のリンクを参考にした **Rails 4** と **Github** に関するあなたのステータス
[各技術のステータス | よちよち.rb](https://github.com/yochiyochirb/meetups/blob/master/member_status.md)
* **自分をお惣菜に例えてください。また、それを挙げた理由を教えてください。**

**Comment by seisonshi** [comment]
https://gist.github.com/seisonshi/42fd55de57947978b641/4ab7864d0dc2ef9d531cc5ab6417d894b39176a2

**Comment by yukios** [comment]
初参加です。よろしくお願いします！
https://gist.github.com/yukios/981980e863df03622532

**Comment by rin0801** [comment]
初参加です！よろしくお願いします。
↓手間取りました。。。遅くなってすみません
https://gist.github.com/rin0801/fbee11a2d53a078b97be

**Comment by bumptakayuki** [comment]
２回目です。宜しくお願いします！
https://gist.github.com/bumptakayuki/e6b7f6ab1932dce99e01

**Comment by yucao24hours** [comment]
@bumptakayuki @yukios @rin0801 @seisonshi 
先日はお疲れ様でした! いつもあんな感じでわいわいたのしくやっていますので、いつでもまたお越しくださいね :smiley: 

先ほど、みなさま宛（@bumptakayuki さんは既にメンバーなのでそれ以外の方） に yochiyochirb の organization への招待メールをお送りしました。
そのメールに記載されている確認リンクを踏んでいただくことで、こちらの meetups リポジトリへの push 権が付与されるようになっています。

2回目以降のご参加の方には、 https://github.com/yochiyochirb/meetups/wiki#how-to-use-github を参考にしながら 自己紹介ファイルを追加するプルリクエストを送っていただいておりますので、Github の練習がてら是非チャレンジしてみてください。
以下もあわせてご確認ください：
* [マージするときのルール](https://github.com/yochiyochirb/meetups/wiki/to-merge-branch)
* [この Organization を抜けたいときは](https://github.com/yochiyochirb/meetups/issues/121)

ご不明な点については Idobata でも Github でも大丈夫ですので是非お気軽に話しかけていただければと思います :strawberry:  またよろしくお願いします!!!
