### ISSUE TITLE
ミートアップ 100 回を記念したなにかをやりたい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#1178]
みなさまのおかげで、よちよち.rb はもう間もなく 第 :one: :zero: :zero: 回を迎えます。
（今日のミートアップが 89回でした）

月曜日が祝日の日が今後何度かあるのですが、その日のミートアップをお休みにしたとしてカウントすると、2015 年 12 月 7 日(月) が第 100 回になりそうです。（あくまでも予定です）

この時期の前後に、ぜひなにかやりたい！と思ったのですが、いかがでしょうか？ :eyes:

**Comment by yucao24hours** [comment]
RubyKaigi2015 が 12/11-13 だから、何かやるとしたらそれ以降のほうがいいかも。

**Comment by yucao24hours** [comment]
とりあえずなんかやろう（独断）

**Comment by katorie** [comment]
:tada: :tada: :tada:

**Comment by yucao24hours** [comment]
このままいくとほんとに 12月になりそうだ。忘年会とかいろんなものとかぶりそうだけど、よちよち.rb でも忘年会兼100回記念、みたいにしたらいいんじゃないかなと思っておりました。そろそろ Doorkeeper たてるかなー。

**Comment by yucao24hours** [comment]
先日 友達がやっているお店 http://miraishokudo.com/ にお手伝いをしに行った時、よちよち.rb 100 回の話をしていたら、「よかったらうちのお店使って開催してよ〜！」と言ってもらったので、やらせてもらおっかなーと思っているところ。
なにをするかは考えてないけど、厨房を借りて料理とかしてもいいし、広い壁があるからプロジェクタで画面うつしたりしてもいいし、とのことだった。めっちゃおもしろそう。ワクワク。

**Comment by makoto-ogata** [comment]
すいません、タブレットでgithub見てて、操作を間違えてissueを閉じてしまいました！！（慌ててまた開きました）
申し訳ありませんです。

**Comment by yucao24hours** [comment]
今週末にまたお店にいってくるので、そのときにちょっと打ち合わせをする予定。
もし「こんなことやりたいかも」といった内容があったら、ぜひきかせてください〜。

**Comment by pupupopo88** [comment]
ぜひぜひ、お祝いやりましょう :tada:  :tada:  :tada:  :tada:  :tada: 
またLTとかやっても面白そうですね！

**Comment by yucao24hours** [comment]
簡単にうちあわせしてきた。

- 土曜日なら、ランチ後は閉店してるのでずっと貸してもらえる
- 日曜日なら一日中貸してもらえる
- キッチンを使ってお酒をつくったりして OK
- 調理もして OK 

懸念してるのは、入れる人数。多くても15名とのことなんだけど、どれくらい来てくれるかまったく予想がつかないのでなんとも。
どこかで仮募集とかしたらいいのかな。

**Comment by yucao24hours** [comment]
12/20(日) を仮開催日として Doorkeeper で募集をしようとおもいます！！！！！

**Comment by yucao24hours** [comment]
今やってる

**Comment by yucao24hours** [comment]
2015/12/20(日) に開催しました!! 
参加してくださったみなさま、たのしい時間をありがとうございました :relaxed:
