### ISSUE TITLE
参加者として、いつでも正しい手順がわかるマニュアルが設置されていてほしい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#1247]
なぜなら、何をしたらいいかがはっきりとわかっていると、不安がなく参加できてうれしいからだ。

具体的には、

- GitHub のインタフェースが変わったので wiki を更新する
- wiki の内容でつかえたところがなかったか、最近はじめて来てくれた人にフィードバックをもらってみる
- idobata rooms のリンクが古くないか確認する 

などが思い当たる。ような気がする。

**Comment by ManabuSeki** [comment]
2014年のアドベントカレンダーのURL追加しておきました

**Comment by yucao24hours** [comment]
うおーー めちゃめちゃ助かります && うれしいです :relaxed: ありがとうございます！！

**Comment by yucao24hours** [comment]
https://github.com/yochiyochirb/meetups/wiki/frequently-asked-questions-about-self-introduction

**Comment by yucao24hours** [comment]
wiki の更新おわった！！！！！！:tada:

**Comment by yucao24hours** [comment]
どなたからもフィードバックを受け取れるように、Google フォームでアンケートを作ってリンクを入れてみた。わかりづらいというご指摘があったら、随時対応させていただきたいため。

**Comment by yucao24hours** [comment]
ということでこちらは done
