### ISSUE TITLE
第97回（11/24 開催）で使用する Gist 回収場所

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#1248]
はじめての方は、自己紹介で使う Gist の URL をここのコメントに貼っていってください :rabbit:

# 必ず書いておいてほしい内容
* お名前
* ご職業
- 【初参加の方限定の質問】なんで Ruby をはじめようと思ったの？
- 【初参加・二回目以上参加の方共通質問】旅先での(とっておきの)失敗談
* 以下のリンクを参考にした **Rails 4** と **GitHub** に関するあなたのステータス
[各技術のステータス | よちよち.rb](https://github.com/yochiyochirb/meetups/blob/master/member_status.md)

**Comment by Eyako** [comment]
https://gist.github.com/dbf630f76ceb279eb859.git

よろしくお願いいたします^^

**Comment by Eyako** [comment]
https://gist.github.com/Eyako/dbf630f76ceb279eb859/raw/38819fd652e589eed7fd6d8f6a864a638182bf77/eiki_yako..md
よろしくお願いいたします^^

**Comment by yucao24hours** [comment]
@Eyako はじめまして！ご記入ありがとうございます :smile: 
ただ、上記リンクをクリックすると 404 エラーになってしまうので、URL が誤っているようです :sweat_drops: 

Gist を開くと以下のような画面になると思うので、その時にブラウザの URL バーに表示されている URL （下図の赤い矢印が指している箇所）をコピペして、こちらのコメントに改めて投稿していただけますでしょうか :bow: 

![gist](https://cloud.githubusercontent.com/assets/1979779/11325403/1ec091ae-9190-11e5-985b-19703905e3a8.png)

**Comment by Eyako** [comment]
https://gist.github.com/Eyako/dbf630f76ceb29eb859
このURLでご覧になれますか？

**Comment by yucao24hours** [comment]
はい、見られました！ありがとうございます :star:

**Comment by sek1guch1** [comment]
過去に何度か申し込みキャンセルをしてしまいました。申し訳ございません。
本日は参加します。よろしくお願いいたします。
https://gist.github.com/sek1guch1/6640ba7d6fd12ceae31c

**Comment by sek1guch1** [comment]
### `git push` しました。

**Comment by yucao24hours** [comment]
@Eyako @sek1guch1  改めまして、先日は初参加していただきありがとうございました！おかげさまでとてもたのしく過ごすことができました :coffee: 
突然ペアプロ！という内容でびっくりさせてしまったかも!?しれませんが、みんなで無理せずちょっとずつすすんで行こう〜という方針でやっていますので、よろしければまた一緒に過ごしましょう :relieved: 

2回目以降のご参加の方には、 https://github.com/yochiyochirb/meetups/wiki#how-to-use-github を参考にしながら 自己紹介ファイルを追加するプルリクエストを送っていただいておりますので、Github の練習がてら是非チャレンジしてみてください。
以下もあわせてご確認ください：
* [マージするときのルール](https://github.com/yochiyochirb/meetups/wiki/to-merge-branch)
* [この Organization を抜けたいときは](https://github.com/yochiyochirb/meetups/issues/121)

ご不明な点については Idobata でも Github でも大丈夫ですので是非お気軽に話しかけていただければと思います :strawberry:  またよろしくお願いします!!!
