### ISSUE TITLE
データモデリングの話

### ISSUE THREAD

**Issue by ManabuSeki** [yochiyochirb/meetups#1368]
とりあえず立てます

## 参加者
 - highwide
 - 5t111111
 - waterlow
 - ManabuSeki
 - dorachan1029

**Comment by 5t111111** [comment]
英語という高い山を越えられないでいます

**Comment by waterlow** [comment]
データモデリング白熱中

**Comment by waterlow** [comment]
* person or user ？
* サロゲートキー(idカラム)消すor何らか手を加えることある？

**Comment by waterlow** [comment]
白熱して何も書けなかった

**Comment by 5t111111** [comment]
### これを実現したい

![scannable document on feb 13 2017 21_58_36](https://cloud.githubusercontent.com/assets/333180/22884318/b0548676-f237-11e6-940f-21146ba81b17.png)

**Comment by 5t111111** [comment]
### こういうモデルのリレーションで設計すればいいのでは？

![scannable document 3 on feb 13 2017 21_58_36](https://cloud.githubusercontent.com/assets/333180/22884334/c7341f1e-f237-11e6-91a2-97f045828ee2.png)

**Comment by 5t111111** [comment]
### 実際に格納されるデータの例

![scannable document 2 on feb 13 2017 21_58_36](https://cloud.githubusercontent.com/assets/333180/22884344/d3f1966e-f237-11e6-8472-d4a3f564da82.png)

**Comment by highwide** [comment]
個人的にArrayとListの話ができて興奮しました

**Comment by 5t111111** [comment]
今のところ特に隙はなさそう？

**Comment by yucao24hours** [comment]
終わったので close
