### ISSUE TITLE
Rubyクイズを解きまくる会

### ISSUE THREAD

**Issue by TasukuNakano** [yochiyochirb/meetups#1369]
これを解きます
https://hoshinotsuyoshi.com/ruby_truthy_or_falsy/

**Comment by yuki3738** [comment]
```3.! > 2```

**Comment by TasukuNakano** [comment]
`1.0 === 1` が true という驚き

**Comment by yuki3738** [comment]
ﾅﾆｺﾚ…
``` ruby
:1.equal? :1
```

**Comment by muramurasan** [comment]
```ruby
irb(main):001:0> -1i
=> (0-1i)
```
?????????????

**Comment by ikatsuki** [comment]
```
:1.equal? :1
```

**Comment by ikatsuki** [comment]
`[ ].shift`
`1/0.0`

**Comment by muramurasan** [comment]
`( )` があるとOKなのはわかるんですけど、左から順に解釈するわけじゃないんですね....
```ruby
irb(main):001:0> 1...3.cover?(2)
NoMethodError: undefined method `cover?' for 3:Integer
        from (irb):1
        from /Users/hoshino/.rbenv/versions/2.4.0/bin/irb:11:in `<main>
```

**Comment by yuki3738** [comment]
``` ruby
Infinity
```

**Comment by yuki3738** [comment]
Infinityはerrorです…

**Comment by TasukuNakano** [comment]
日本語変数がいけるという驚き

**Comment by yuki3738** [comment]
ふむ :kissing:
Congratulations, you got 70% correct!

**Comment by huideyeren** [comment]
`1.0 === 1`がtrueと聞いてバージョンの違いかと思ったらなぜかrbenvがおかしいことになっててドハマり中。

**Comment by akinomaeni** [comment]
Float::Infinity

**Comment by akinomaeni** [comment]
https://docs.ruby-lang.org/ja/latest/class/Float.html#C_-I-N-F-I-N-I-T-Y

**Comment by TasukuNakano** [comment]
`cover?` メソッドについて

https://docs.ruby-lang.org/ja/latest/method/Range/i/cover=3f.html

**Comment by TasukuNakano** [comment]
>( ) があるとOKなのはわかるんですけど、左から順に解釈するわけじゃないんですね....

`3.cover?` となってしまっていて、 `NoMethodError` となり、よくハマるポイントという話をした

**Comment by yuki3738** [comment]
``` ruby
_
```

**Comment by yuki3738** [comment]
``` ruby
75 =< -75
```

**Comment by TasukuNakano** [comment]
`_` これは、 irb 特有のものではないかという話をした

`_` だけ書いた rb ファイルを実行したら、

```
hoge.rb:1:in `<main>': undefined local variable or method `_' for main:Object (NameError)
```

となりました

**Comment by TasukuNakano** [comment]
`3.! => false` 
`.!` が、反転させるメソッドではないか( `if !variable` 的な)
という話をした

**Comment by akinomaeni** [comment]
https://docs.ruby-lang.org/ja/latest/class/BasicObject.html#I_--21

**Comment by akinomaeni** [comment]
複素数リテラル
https://docs.ruby-lang.org/ja/latest/doc/spec=2fliteral.html#num

**Comment by TasukuNakano** [comment]
`(0**0) => 1`

数学ェ…
http://www.proof0309.com/entry/2no0zyou

**Comment by yuki3738** [comment]
Congratulations, you got 60% correct! :expressionless:

**Comment by TasukuNakano** [comment]
Congratulations, you got 70% correct!
(何回か解いてここまできました 😃  )

**Comment by yucao24hours** [comment]
終わったので close
