### ISSUE TITLE
nokogiri を愛でる会

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#1370]
## 参加者
- yucao24hours
- TeruhisaShibuya
- oh-naoki
- tetsutaroendo

**Comment by TeruhisaShibuya** [comment]
こんちは！！

**Comment by oh-naoki** [comment]
よろしくお願いいたします

**Comment by tetsutaroendo** [comment]
はじめまして、遠藤です

**Comment by TeruhisaShibuya** [comment]
自分のサービスを作るためにnokogiriが必要なんですが、どのように勉強したら良いか分からないです！！

**Comment by yucao24hours** [comment]
http://qiita.com/advent-calendar/2016/crawler

**Comment by yucao24hours** [comment]
nokogiri が好きな人はこちらのブログも読んでいます: http://blog.takuros.net/

**Comment by yucao24hours** [comment]
http://morizyun.github.io/blog/ruby-nokogiri-scraping-tutorial/ を読んで nokogiri について理解してこう

**Comment by yucao24hours** [comment]
scrape: 擦り傷

**Comment by yucao24hours** [comment]
「そもそもみんなプログラムはじめたばかりのときってどうやって勉強してたの？」

**Comment by yucao24hours** [comment]
https://github.com/yucao24hours/nhk_gogaku/blob/master/shusseki.rb#L28

このあたりが XPath の実用例です!

**Comment by yucao24hours** [comment]
https://docs.ruby-lang.org/ja/latest/class/IO.html#S_FOR_FD

**Comment by yucao24hours** [comment]
終わったので close
