### ISSUE TITLE
cyber-dojo.org をやってみるぜ

### ISSUE THREAD

**Issue by 5t111111** [yochiyochirb/meetups#1375]
http://cyber-dojo.org/
やったことある人いますか？
TDDの課題などがあるらしく、ペアプロでやってみるとか楽しそうかと

- bonbon0605 
- 5t111111

**Comment by bonbon0605** [comment]
👍

**Comment by 5t111111** [comment]
LGTM

**Comment by yucao24hours** [comment]
なにをやったのかさっぱりわからない！！！！

**Comment by bonbon0605** [comment]
``http://cyber-dojo.org/kata/edit/83EB6A3C6F?avatar=shark``

**Comment by bonbon0605** [comment]
上記URLで続きができる？

**Comment by 5t111111** [comment]
http://cyber-dojo.org のなんかハリーポッターの本のやつをやった (未完成)

**Comment by yucao24hours** [comment]
ミートアップが終わったのでこちらは close します。
おつかれさまでした！
