### ISSUE TITLE
Docker をさわろう会

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#1376]

**Comment by yucao24hours** [comment]
みんなの Docker レベルを確認しています

**Comment by yucao24hours** [comment]
https://www.docker.com/products/docker#/mac

まずはインストール

**Comment by yucao24hours** [comment]
http://qiita.com/minodisk/items/5ffd20588b995523756f

**Comment by yucao24hours** [comment]
`docker` コマンドの確認をしてる

**Comment by yucao24hours** [comment]
https://hub.docker.com/_/hello-world/

`docker run hello-world` はこれを pull している

**Comment by yucao24hours** [comment]
https://www.docker.com/products/docker-toolbox

おべんり機能

**Comment by yucao24hours** [comment]
用途が違う...？！

**Comment by u9r52sld** [comment]
https://docs.docker.com/docker-for-mac/docker-toolbox/

**Comment by yucao24hours** [comment]
```shell
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
8aec416115fd: Pull complete
695f074e24e3: Pull complete
946d6c48c2a7: Pull complete
bc7277e579f0: Pull complete
2508cbcde94b: Pull complete
Digest: sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950
Status: Downloaded newer image for ubuntu:latest
Hello World
```

きたわぁ

**Comment by huideyeren** [comment]
https://alpinelinux.org/ かるいやつ

**Comment by yucao24hours** [comment]
ほ〜〜

**Comment by huideyeren** [comment]
https://github.com/huideyeren/wordpress-h2o-http2-hhvm

Wordpressのは作ったけどメンテナンスしてない……

**Comment by yucao24hours** [comment]
https://github.com/bm-sms/daimon_skycrawlers/blob/master/templates/new/docker-compose.yml.erb コレ読んだ ✌️

**Comment by yucao24hours** [comment]
https://hub.docker.com/_/ruby/

オフィシャルの image がある。
rails のオフィシャル image もあるけど、みんな ruby のほうを使っているらしい。

**Comment by yucao24hours** [comment]
終わってた。
当日参加されたみなさん、ありがとうございました！
