### ISSUE TITLE
第125回 @popmac, @daido1976, @hanaseleb, @Chinats

### ISSUE THREAD

**Issue by popmac** [yochiyochirb/meetups#1384]
## Railsチュートリアルを最初から

**Comment by Chinats** [comment]
テスト投稿

**Comment by hanaseleb** [comment]
よろしくお願いします！hanaselebです。
もはや手足があるかわからないレベルのよちよちです。

**Comment by popmac** [comment]
よろしくお願いします😊

**Comment by daido1976** [comment]
daido1976です！Railsチュートリアルは7章までやって放置してました、、、
よちよち思い出していきたいです！よろしくお願いします！

**Comment by popmac** [comment]
「第1章 ゼロからデプロイまで」から読んでいきます

**Comment by hanaseleb** [comment]
# バグではありません、仕様です!

**Comment by popmac** [comment]
> MVCやREST、ジェネレータ、マイグレーション、ルーティング、ERBなど、Railsフレームワークのコア技術を本チュートリアルでまとめて学ぶことができます。

これだけ学べるのすごい

**Comment by daido1976** [comment]
>ベストプラクティス（英: best practice）は、ある結果を得るのに最も効率のよい技法、手法、プロセス、活動などのこと。

**Comment by hanaseleb** [comment]
ドメイン駆動設計
テスト駆動開発

**Comment by ckanayama** [comment]
テスト駆動開発 (TDD)とは？
→テストを先に書く開発手法

**Comment by hanaseleb** [comment]
> 統合テストとは、システム開発におけるプログラムの検証作業の中でも、手続きや関数といった個々の機能を結合させて、うまく連携・動作しているかを確認するテストのことである。

統合テストでは、個々の機能を果たすためのプログラム部品（プログラムモジュール）を組み合わせて、データの受け渡しがうまく行われているか、コードの記述様式は揃っているか、データを授受するタイミングはずれていないか、といった点が確認される。統合テストで不備が発見された際には、再度コーディングが行われる。

プログラムの検証作業では、はじめに個々のプログラムモジュールがきちんと仕様どおりに機能しているかを確認する「単体テスト」が行われる。単体テストによって個々のプログラムモジュールが問題なく機能すると確認された際に、統合テストによって連携が確かめられる。統合テストで問題がないと確認されたら、次にはモジュールの組み合わせをさらに複合させてひとつのシステムを形成させ、モジュールの連携によって構築されたシステムが全体として予定通りの機能を満たしているかどうかを確認する「システムテスト」が行われる。さらに顧客に試用してもらって顧客の要望がきちんと満たされているかどうかを確認する「承認テスト」が行われる。これら一連のテストを経て、システムが完成する。

**Comment by daido1976** [comment]
「モックアップ」「テスト駆動開発 (TDD)」「統合テスト」について、、、

**Comment by popmac** [comment]
この3つは確かにレイヤーが違う感じですね💦

**Comment by hanaseleb** [comment]
## seductive
魅惑的な

**Comment by popmac** [comment]
seductive っていう英単語初めて見た

**Comment by daido1976** [comment]
_一口サイズのコード_ ていい響き

**Comment by popmac** [comment]
1人で読んでいる時「一口サイズ」「歯ごたえ」っていう比喩表現を楽しむ余裕がなかったな...

**Comment by hanaseleb** [comment]
## scaffold
足場

**Comment by daido1976** [comment]
Railsチュートリアルの日本語訳が素敵

**Comment by popmac** [comment]
DisneyもRailsだったの

**Comment by daido1976** [comment]
Shopifyて知らなかった

**Comment by ckanayama** [comment]
MerbとRailsの合流という歴史

**Comment by popmac** [comment]
RailsとMerbの合流についてあれこれ - アンカテ http://d.hatena.ne.jp/essa/20081225/p1

**Comment by hanaseleb** [comment]
[MerbはRails 3.0にマージされる - InfoQ](https://www.infoq.com/jp/news/2008/12/merb-merged-in-rails-30)

**Comment by hanaseleb** [comment]
AWSの登録にはクレカが必要。

**Comment by daido1976** [comment]
`DSL (ドメイン固有言語) `とは、、、

**Comment by ckanayama** [comment]
>DSLは、ある分野に固有の語彙や語法を使用して事象を表現できるよう作られたプログラミング言語です。

Rubyに特化したフレームワークRails

**Comment by popmac** [comment]
以下の3つをやってみます
- Ruby on Railsで使うRuby gemはどのWebサイトにありますか？ヒント: 分からないときはとにかくググりましょう。
- 現時点でのRailsの最新バージョンはいくつですか？
- Ruby on Railsはこれまでに何回ダウンロードされたでしょうか？調べてみてください。

**Comment by ckanayama** [comment]
>Ruby on Railsで使うRuby gemはどのWebサイトにありますか？ヒント: 分からないときはとにかくググりましょう。

https://rubygems.org/

**Comment by daido1976** [comment]
[RubyGems](https://rubygems.org/)

**Comment by hanaseleb** [comment]
## Ruby on Railsで使うRuby gemはどのWebサイトにありますか？ヒント: 分からないときはとにかくググりましょう。

[RubyGems.org | your community gem host](https://rubygems.org/)

## 現時点でのRailsの最新バージョンはいくつですか？

[Latest version — Rails 5.2.0 released April 9, 2018](https://weblog.rubyonrails.org/2018/4/9/Rails-5-2-0-final/)

## Ruby on Railsはこれまでに何回ダウンロードされたでしょうか？調べてみてください。

わかりません・・・

**Comment by hanaseleb** [comment]
![image](https://user-images.githubusercontent.com/8947320/39997294-63f6bce4-57bd-11e8-827a-de38ec2cbe13.png)

**Comment by ckanayama** [comment]
>Ruby on Railsはこれまでに何回ダウンロードされたでしょうか？調べてみてください。

Ruby gemsで調べれるんだ。

**Comment by hanaseleb** [comment]
これって、5.2のDL数ですか？それともRails通算？

**Comment by daido1976** [comment]
railsもgemなんですねー
https://rubygems.org/gems/rails

**Comment by daido1976** [comment]
Railsのソースコード
https://github.com/rails/rails

**Comment by hanaseleb** [comment]
## MITライセンスとは
下記の条件を受け入れていただけるのであれば、誰でも自由に無料で、このソフトウェアをつかっていただくことができます。
このソフトウェアをコピーしてつかったり、配布したり、変更を加えたり、変更を加えたものを配布したり、商用利用したり、有料で販売したり、なんにでも自由につかってください。

このソフトウェアの著作権表示（「Copyright (c) 年 作者名」）と、このライセンスの全文（英語の文章）を、ソースコードのなかや、ソースコードに同梱したライセンス表示用の別ファイルなどに掲載してください。

このソフトウェアにはなんの保証もついていません。たとえ、このソフトウェアを利用したことでなにか問題が起こったとしても、作者はなんの責任も負いません。

**Comment by ckanayama** [comment]
マサチューセッツ工科大学

**Comment by popmac** [comment]
確かに MIT

**Comment by ckanayama** [comment]
[1.1.1 前提知識](https://railstutorial.jp/chapters/beginning?version=5.1#sec-prerequisites)を読み終わったところまで。

**Comment by daido1976** [comment]
@popmacさん素敵な発表ありがとうございます！！！

**Comment by daido1976** [comment]
エディタは僕もAtom使ってます

**Comment by hanaseleb** [comment]
Atomがいいんですかねぇ。Sublime使ってますが、Atomにとても興味があります。

**Comment by ckanayama** [comment]
【補足】
Rails作者の名前
→ デイヴィッド・ハイネマイヤー・ハンソン (David Heinemeier Hansson)

Railsのダウンロード数が意外と少ない気がする
→Railsが当初からgem扱いだったわけではないのと、大元のやつなので他のgemのように何かに付随してダウンロードされるわけではないから数字としては少なめに見える。

**Comment by daido1976** [comment]
Rubyの基礎は[プロを目指す人のためのRuby入門 言語仕様からテスト駆動開発・デバッグ技法まで ](https://www.amazon.co.jp/%E3%83%97%E3%83%AD%E3%82%92%E7%9B%AE%E6%8C%87%E3%81%99%E4%BA%BA%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AERuby%E5%85%A5%E9%96%80-%E8%A8%80%E8%AA%9E%E4%BB%95%E6%A7%98%E3%81%8B%E3%82%89%E3%83%86%E3%82%B9%E3%83%88%E9%A7%86%E5%8B%95%E9%96%8B%E7%99%BA%E3%83%BB%E3%83%87%E3%83%90%E3%83%83%E3%82%B0%E6%8A%80%E6%B3%95%E3%81%BE%E3%81%A7-Software-Design-plus%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA/dp/4774193976)を会社の研修でやりました！
Qiitaでよく見る伊藤さんが書いてる本でめちゃくちゃわかりやすかったです！

**Comment by popmac** [comment]
この本は「とりあえずRailsでアプリ作ったけどRuby分からん」という状態の僕にはかなり参考になりました😊

**Comment by daido1976** [comment]
@hanaseleb 
僕もsublime使ってましたが、Atomに変えました！ショートカットがめちゃ便利です！

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
