### ISSUE TITLE
第125回 とっしー，ドバッティ，NAO,  カサ

### ISSUE THREAD

**Issue by toshichanapp** [yochiyochirb/meetups#1385]

**Comment by dobatty** [comment]
hi

**Comment by toshichanapp** [comment]
技術的に困難な課題を魔法のように解決するには、やはりハードスキル (操作方法などの定型化しやすいスキル) とソフトスキル (デバッグなどの定型化しにくいスキル) の両面における熟練が必要

**Comment by toshichanapp** [comment]
「REST」という設計思想の重要性をいち早く理解し、対応したフレームワークの１つ

**Comment by toshichanapp** [comment]
Ruby gem https://rubygems.org/
Railsの最新バージョン 5.2.0 https://rubyonrails.org/
Ruby on Rails　ダウンロード数 ？

**Comment by dobatty** [comment]
Cloud ShellとAWS Cloud9を比較してみた
https://qiita.com/tora470/items/1fac2ddd03c6a4a86e68

**Comment by dobatty** [comment]
個人的には、最近Atom使ってますー

**Comment by nao-aloha** [comment]
読み進めていて初めて見る単語だらけで帰ってから読み返し必須！
一番心に残ったのはフローチャートと"分からないときはとにかくググれ"という言葉。

**Comment by toshichanapp** [comment]
単語，単語で止まって調べる

**Comment by A-kasa** [comment]
どうぞよろしく

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
