### ISSUE TITLE
ShinsukeKido kumewata KoichiTsujihashi tararico

### ISSUE THREAD

**Issue by ShinsukeKido** [yochiyochirb/meetups#1386]

**Comment by kumewata** [comment]
てすと

**Comment by ShinsukeKido** [comment]
よろしくお願いします！！

**Comment by kumewata** [comment]
よろしくお願いします！

**Comment by kumewata** [comment]
Rails作者 デイヴィッド・ハイネマイヤー・ハンソン (David Heinemeier Hansson)
https://ja.wikipedia.org/wiki/%E3%83%87%E3%82%A4%E3%83%B4%E3%82%A3%E3%83%83%E3%83%89%E3%83%BB%E3%83%8F%E3%82%A4%E3%83%8D%E3%83%9E%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%BB%E3%83%8F%E3%83%B3%E3%82%BD%E3%83%B3

**Comment by ShinsukeKido** [comment]
モックアップ？

**Comment by ShinsukeKido** [comment]
「モックアップ」「テスト駆動開発 (TDD)」「統合テスト」の違い？

**Comment by kumewata** [comment]
MITライセンス、他には？

**Comment by kumewata** [comment]
[演習]
1. RubyGems
https://rubygems.org/

2. 最新ver
v5.2.0
https://rubyonrails.org/

3. Railsのダウンロード数
~1.3億
http://bestgems.org/total

**Comment by ShinsukeKido** [comment]
http://bestgems.org/total

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
