### ISSUE TITLE
第125回 ゆかお、わかすぎ、がく、しょーぐん、みなみや

### ISSUE THREAD

**Issue by yuki3738** [yochiyochirb/meetups#1387]
ﾜｲﾜｲ

**Comment by to0526** [comment]
我に続けえ

**Comment by yuki3738** [comment]
強い
<img width="216" alt="2018-05-14 20 50 22" src="https://user-images.githubusercontent.com/6305192/39995818-74398b0e-57b8-11e8-98de-1ca5e45e3973.png">

**Comment by 5t111111** [comment]
> Learn Enough to Be Dangerous シリーズの一つであり、

知らないことだらけや

**Comment by yuki3738** [comment]
> 「熟練」になるとは

力が欲しい

**Comment by 5t111111** [comment]
> 適切なRuby gemの選定方法

こんなのも教えてくれるの…？？？すごい

**Comment by yucao24hours** [comment]
危険になるためのコマンドライン

**Comment by yuki3738** [comment]
アプリ名も進化するRails tutorial

**Comment by ManabuSeki** [comment]
このチュートリアルの中核である`第3章以降`のサンプルアプリケーションからは、scaffoldを**一切使わず**に開発を進めていきます。

**Comment by ManabuSeki** [comment]
アダルトチームは少し先やります
1.2まで飛ばす

**Comment by 5t111111** [comment]
Cloud9が心配になったんで1.2にワープ

**Comment by yuki3738** [comment]
AWSのcloud9使うの初めて

**Comment by yucao24hours** [comment]
AWS Cloud9 便利

**Comment by ManabuSeki** [comment]
AWSが不安要素になってしまった

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
