### ISSUE TITLE
第126回 チーム ガルシアさん

### ISSUE THREAD

**Issue by ShinsukeKido** [yochiyochirb/meetups#1389]

**Comment by ShinsukeKido** [comment]
よろしくお願いします！

**Comment by lime1024** [comment]
こんにちは！こんにちは！

**Comment by 10mi8o** [comment]
よろしくお願いします！

**Comment by lime1024** [comment]
インデントを4->2にするのは宗教なのか

**Comment by lime1024** [comment]
BitbucketとHerokuとは...
HerokuはFFFTPみたいな感じのもののこと?

**Comment by garciaaan1994** [comment]
ガル所感

# イントロ

- cloud9起動するまで時間かかるの割とつらみがある風
 - ローカルの方が楽かもと思ってしまった
 - cloud9を使うメリットがあまり感じられない
 
# 輪読タイム

## 1.2 さっそく動かす

### 1.2.1 

- Cloud9ワークスペースには、Ruby、RubyGems、Gitなど、プロ級のRails開発環境に必要なソフトウェアがすべて組み込まれてい -> だからcloud9なのか
- 打つコマンドが少なくて良い？
- atom使いたみ、、になった
- インデントについて
 - 言語によって推奨が違う
 - 単純な見やすさ重視？
- bitbucketはgithub的な

### 1.2.2 

- こないだやったときは5.2.0だった

**Comment by ShinsukeKido** [comment]
rails のバージョン変更によって作成されるファイルが変わることへの対応はどうしているのか？

**Comment by 10mi8o** [comment]
.gitignore Gitに取り込みたくないファイルとはどういうケースを想定しているの？

**Comment by lime1024** [comment]
railsをアップデートしないデメリットがわからなくて、チートして旦那にききました。
回答「Windows XP を使い続けますか？」

わかんねーけどわかったような気がしないでもない...

**Comment by garciaaan1994** [comment]
# 発表
- cloud9を使うメリットについて話した
- バージョンアップについての闇
　- チームでの開発をしていて、バージョンアップをするときに発生する問題は？
　- どう対応してるの？

**Comment by lime1024** [comment]
4 -> 2 宗教戦争の結末はこちら
http://i.loveruby.net/ja/ruby/codingstyle.html

**Comment by yucao24hours** [comment]
http://i.loveruby.net/ja/ruby/codingstyle.html

**Comment by lime1024** [comment]
Herokuはお手軽サーバ

**Comment by lime1024** [comment]
Cloud9は開発環境の構築が楽になるというメリット

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
