### ISSUE TITLE
第126回 たらりこ, きょうこ, ちなつ

### ISSUE THREAD

**Issue by ckanayama** [yochiyochirb/meetups#1390]

**Comment by kyokokato** [comment]
IDEとは？統合開発環境
ルビーマイン

**Comment by ckanayama** [comment]
Rubyで有名な（最初使ってみてよかった）IDE
https://www.jetbrains.com/ruby/

**Comment by ckanayama** [comment]
IDE: integrated development environment

**Comment by kyokokato** [comment]
Railsチュートリアルのワークスペースは１年間無料なのでご安心ください。
きになる

**Comment by ckanayama** [comment]
IAM
>AWS Identity and Access Management (IAM) は、AWS リソースへのアクセスを安全に制御するためのウェブサービスです。IAM を使用して、リソースを使用するために認証 (サインイン) され、許可された (アクセス権限を持つ) ユーザーを制御します。

**Comment by tararico** [comment]
cloud9の使い方がわからん

**Comment by ckanayama** [comment]
旧cloud9だとチュートリアル通りにコマンドを打つと設定が色々違っていて困ることがわかった、、

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
