### ISSUE TITLE
第126回　とっしー、Nao、みや、かに

### ISSUE THREAD

**Issue by nao-aloha** [yochiyochirb/meetups#1391]

**Comment by toshichanapp** [comment]
ゆかお「つまづきから学びがある」

**Comment by toshichanapp** [comment]
アプリケーションスケルトン？

**Comment by MH4GF** [comment]
bashとは？？？？？？？？

**Comment by toshichanapp** [comment]
ブライアン・フォックス!!!!!

**Comment by kanikani2929** [comment]
```gem install rails -v 5.1.4```を入力するとエラーになった。
```
$ rails new
$ bundle init
$ bundle install
```
で解決した。

**Comment by kanikani2929** [comment]
Bash:Unixのコマンド言語？
https://qiita.com/ycoda/items/87d23b818cb06ba1c348

**Comment by kanikani2929** [comment]
https://eng-entrance.com/linux-shell

**Comment by toshichanapp** [comment]
bash のほか　zsh ,fishなどが有る

**Comment by toshichanapp** [comment]
mkdir: make directory
mv: move
cp: copy
cd: change directory

**Comment by toshichanapp** [comment]
ファイル/ディレクトリ構造がすべてのRailsアプリで標準化されているおかげで、他の開発者の書いたRailsのコードが読みやすくなります。これはWebフレームワークを導入する大きなメリットです

**Comment by MH4GF** [comment]
標準化ありがたい

**Comment by MH4GF** [comment]
アセットパイプライン？？？？？

**Comment by toshichanapp** [comment]
バージョンを指定する主な方法は2通り
`>=`という記法では常に最新のgemがインストールされ、
`~>` 4.0.0という記法ではマイナーバージョンの部分に相当するアップデート済みのgem]
 (例: 4.0.0から4.0.1) をインストールします。後者の場合、メジャーバージョン (例: 4.0から4.1) のリリースはインストールされません1

**Comment by kanikani2929** [comment]
慣れるまでgemのバージョンは指定したほうが良さそう。

**Comment by toshichanapp** [comment]
リスト 1.5 コピペしたら怒られた

bundle updateで解決！

**Comment by kanikani2929** [comment]
http://shindolog.hatenablog.com/entry/2014/01/19/012802

**Comment by MH4GF** [comment]
なお、uglifierはAsset Pipelineでファイル圧縮を行うためのものです

**Comment by toshichanapp** [comment]
gem 'turbolinks'
https://gist.github.com/saboyutaka/8727377

> fetchReplacement
<a>タグのリンクをクリックした時の遷移をajax化して画面遷移なしにページ遷移する。
clickイベントの挙動を変えている
fetchHistory
戻るボタンなどを押した時のイベントを書き換えている
fetchReplacement時にpushStateでキャッシュしたページをpopStateで復元する。

**Comment by toshichanapp** [comment]
rails gemについて調べてる方がいらした
https://suin.io/536

**Comment by MH4GF** [comment]
http://ruby-rails.hatenadiary.com/entry/20141026/1414289421

**Comment by toshichanapp** [comment]
rails 標準gem
https://qiita.com/kkenya/items/e9eba0021b1cf5efca2b

**Comment by MH4GF** [comment]
Yay! You’re on Rails!

**Comment by toshichanapp** [comment]
ランタイム
http://wa3.i-3-i.info/word13464.html
> プログラムとかを動かすときに必要な部品のこと

**Comment by kanikani2929** [comment]
演習
```
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
Rails 5.1.4
```

**Comment by toshichanapp** [comment]
rails sでこけた
Address already in use - bind(2) for "0.0.0.0" port 3000 (Errno::EADDRINUSE)

-p オプションで3000以外のポートを指定することで解決

**Comment by MH4GF** [comment]
Rails version: 5.1.5
Ruby version: 2.3.6 (x86_64-darwin17)

**Comment by kanikani2929** [comment]
https://qiita.com/paranishian/items/8a18aba3c2f9e7e5d00f

**Comment by toshichanapp** [comment]
Yay!
わ〜い
https://eow.alc.co.jp/search?q=yay

**Comment by toshichanapp** [comment]
RailsがMVC (model-view-controller) というアーキテクチャパターン

**Comment by MH4GF** [comment]
アプリケーション内のデータ（ユーザー情報など）と、データを表示するコードを分離

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
