### ISSUE TITLE
第126回 つっちー、いけだ、いわち、まっつん

### ISSUE THREAD

**Issue by popmac** [yochiyochirb/meetups#1392]
よろしくおねがいします😊

**Comment by ikedakohei** [comment]
よろしくです！

**Comment by tsuchiya12345** [comment]
宜しくお願いします〜

**Comment by ghost** [comment]
よろしくどうぞ〜

**Comment by tsuchiya12345** [comment]
> 環境にばらつきがあると、さまざまな問題が複合して発生してしまいます   

やっかい。。。

**Comment by popmac** [comment]
`rbenv versions`

**Comment by ikedakohei** [comment]
RubyGemsパッケージマネージャってなに？？

**Comment by ikedakohei** [comment]
RubyGemsはgemの管理
bundlerはgem同士の依存関係まで管理
あってる??

**Comment by popmac** [comment]
environmentディレクトリってprojectsディレクトリみたいな感じか

**Comment by popmac** [comment]
シェルとは
http://wa3.i-3-i.info/word11219.html

bashとは
http://wa3.i-3-i.info/word11786.html

**Comment by popmac** [comment]
読み方でよく話題に上がるkubernetes

**Comment by popmac** [comment]
zshっていうものもあります

**Comment by popmac** [comment]
`ls -alF` は便利！

**Comment by ikedakohei** [comment]
`ls -lF`便利！

**Comment by ikedakohei** [comment]
みんなが使っているエディタは？

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
