### ISSUE TITLE
第126回 アダルトチーム @5t111111 @huideyeren @ta1kt0me @yuki3738 @ManabuSeki

### ISSUE THREAD

**Issue by ta1kt0me** [yochiyochirb/meetups#1393]
https://railstutorial.jp/chapters/beginning?version=5.1#sec-up_and_running

**Comment by huideyeren** [comment]
Cloud9の環境が整わない……。

**Comment by huideyeren** [comment]
環境用意するまで時間がかかる……オハイオは遠いのか。

**Comment by yuki3738** [comment]
いきなり 🚽 のとみー

**Comment by 5t111111** [comment]
いきなりはじまった

**Comment by ta1kt0me** [comment]
> テキストエディタやコマンドラインを使う環境と、IDE (統合開発環境) の2つに分けられます。

統合開発環境がふえていていい世界だな〜と思う今日この頃

**Comment by 5t111111** [comment]
rails tutorial 用の Cloud9 のイメージがある？？

**Comment by yucao24hours** [comment]
>意図的にそうしてあります

の意図がわかってない（この後わかるのか？）

**Comment by huideyeren** [comment]
GoogleやMicrosoftもCloud9みたいなのやればいいんじゃないかな。

**Comment by ta1kt0me** [comment]
Cloud9で作ったからAWSにデプロイしやすい仕組みがあるﾄﾉｺﾄ

**Comment by huideyeren** [comment]
シンガポールで作り直しても止まってるんだが。

**Comment by huideyeren** [comment]
どのレベルのインスタンスを使えばいいんだ……？
とりあえずt2.microを選択。

**Comment by 5t111111** [comment]
t2.micro 以外で作ると無料期間でも課金されるから注意

**Comment by huideyeren** [comment]
Connectingで止まってる。

**Comment by ta1kt0me** [comment]
この辺でちょっとした設定ができる
<img width="963" alt="_2018-05-28_21_02_07" src="https://user-images.githubusercontent.com/1412864/40613751-c6b8c306-62ba-11e8-8e86-ef4bf3e5be2e.png">

**Comment by yucao24hours** [comment]
>クラウドIDEを使っている場合はBitbucketとHerokuコマンドをセットアップする必要があります

そうなんだあ
Bitbucket は private が無料だからなのかなー

**Comment by ta1kt0me** [comment]
adblockでハマってしまった

**Comment by huideyeren** [comment]
どうやらAdBlockが悪さをしてた模様。

**Comment by 5t111111** [comment]
なんか謎のおかしい場合は大抵adblockが悪い…

**Comment by ManabuSeki** [comment]
AdBlockダメゼッタイ

**Comment by ManabuSeki** [comment]
ruby 2.4.1が入ってる

**Comment by ta1kt0me** [comment]
> RubyGemsパッケージマネージャ

パッケージマネージャーの登場

**Comment by huideyeren** [comment]
5.1.4をインストール

**Comment by 5t111111** [comment]
> 開発環境 (1.3.4) と本番環境 (1.5) 

いきなり2つも作るのか

**Comment by ta1kt0me** [comment]
開発環境と本番環境

**Comment by huideyeren** [comment]
いきなりUNIXコマンド

**Comment by ta1kt0me** [comment]
> (訳注: 操作を誤ったときの被害もその分甚大ですが)

親切

**Comment by ta1kt0me** [comment]
> railties

れいるたいず

**Comment by huideyeren** [comment]
確かにBundler使ってないなー

**Comment by ta1kt0me** [comment]
> rails _5.1.4_ new hello_app

`_x.x.x_` これ使いたくなるときいっぱいありそう。で嬉しみ

**Comment by ta1kt0me** [comment]
```
doc/ | マニュアルなど、アプリケーションのドキュメント
```

ここまでのところ、こいつはいない。

**Comment by yucao24hours** [comment]
```
doc/ | マニュアルなど、アプリケーションのドキュメント
```

**Comment by yuki3738** [comment]
1.3.1の前まで

**Comment by ta1kt0me** [comment]
https://www.railstutorial.org/book/beginning#sec-the_hello_application 本家にも doc の記述があった（でも実際には作られない）

**Comment by huideyeren** [comment]
t2.microでもいろいろ使ってたりするとお金がかかるよ〜

**Comment by 5t111111** [comment]
Rubyの一時代を築いたtDiaryは3タブなんだぞ！！！
https://github.com/tdiary/tdiary-core/blob/master/lib/tdiary.rb

**Comment by ManabuSeki** [comment]
https://aws.amazon.com/jp/ec2/pricing/on-demand/
シンガポールでEC2上げっぱなしで計算すると

```ruby
((0.0146 * 24) * 31) * 111
=> 1205.7264
```
為替で少しブレますが
1200円ぐらいですかね

**Comment by huideyeren** [comment]
あ、そういえば今日の参加者、みんなMac持ってきてる。

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
