### ISSUE TITLE
第127回　かとうさん、どばしさん、ひでさん、らいむ

### ISSUE THREAD

**Issue by lime1024** [yochiyochirb/meetups#1394]

**Comment by kyokokato** [comment]
よろしくお願いしますー

**Comment by hideame** [comment]
よろしくお願いします！

**Comment by dobatty** [comment]
よろしくおねがいしますっ

**Comment by lime1024** [comment]
スケルトンってなに・・・すけすけなの

**Comment by dobatty** [comment]
スケルトン（テンプレートファイル） https://github.com/lion-man44/rails-tutorial/issues/1

**Comment by kyokokato** [comment]
骨格

**Comment by lime1024** [comment]
すけすけじゃなくて骨組みです（すみません

**Comment by kyokokato** [comment]
インターフェース

**Comment by dobatty** [comment]
Bashとは？　個人的にはzshつかってます:)

**Comment by lime1024** [comment]
Bashは使いやすいコマンドラインって覚えておけば大丈夫、らしい！

**Comment by kyokokato** [comment]
-rf r再帰的　f強制的に
ディレクトリ配下一式強制的に削除

**Comment by lime1024** [comment]
オハイオ州 -> シンガポール
これでcloud9がつながるようになった...かとうさんありがとう！

**Comment by lime1024** [comment]
~
にょろにょろの名前はチルダ

**Comment by dobatty** [comment]
バイナリとは？

**Comment by kyokokato** [comment]
C言語　コンパイルするとバイナリファイルができる

**Comment by lime1024** [comment]
コンパイルすることで、バイナリがつくられる(機械語 : コンピュータ用)

**Comment by lime1024** [comment]
`uglifier`の読み方

**Comment by yuki3738** [comment]
> uglifierの読み方

https://github.com/yochiyochirb/meetups/issues/1397#issuecomment-396217160

**Comment by dobatty** [comment]
GitHubのリポジトリを直接指定してgemをinstallすることも
gem 'hogehoge', git: 'hello/yochiyochi'

**Comment by lime1024** [comment]
1.3.1の途中まで

**Comment by hideame** [comment]
Cloud9で、rails _5.1.4_ new hello_appできない問題
 ⇒ AWSのバージョン問題？
 ⇒ Railsのバージョンが違かった模様($ gem install rails -v 5.1.4)

**Comment by lime1024** [comment]
発表者は男気ジャンケンで決めました！ひでさんよろしくです！

**Comment by lime1024** [comment]
> uglifier => アグリファイヤー

**Comment by hideame** [comment]
ec2-user:~/environment $ rails -v
Rails 5.1.6

**Comment by dobatty** [comment]
GitHubのリポジトリを直接指定してgemをinstallする
gem 'hogehoge', git: 'hello/yochiyochi'

**Comment by hideame** [comment]
ugly = 醜い

**Comment by hideame** [comment]
リンク張るのいいですね！

**Comment by hideame** [comment]
commitはファイル単位ではなく、改修内容単位がいいらしい。

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
