### ISSUE TITLE
第127回　ひさ　ゆうた　とみやま

### ISSUE THREAD

**Issue by 10mi8o** [yochiyochirb/meetups#1395]

**Comment by 10mi8o** [comment]
mkdirの正式な読み方は？

**Comment by 10mi8o** [comment]
アセットパイプラインって具体的に何しているのか？

**Comment by hisayonr0717** [comment]
アセットパイプラインとは、、

**Comment by 10mi8o** [comment]
gemfileとgemfile.lockの役割の違いは？

**Comment by hisayonr0717** [comment]
そもそもgemfileとは

**Comment by 10mi8o** [comment]
Herokuで使うデータベースと競合する可能性とは？

**Comment by 10mi8o** [comment]
git commitする粒度（タイミング）はどれくらい

**Comment by hisayonr0717** [comment]
リポジトリとは

**Comment by hisayonr0717** [comment]
1.4.2まで進みました。

**Comment by hisayonr0717** [comment]
発表者はゆうたさんです☆

**Comment by yuki3738** [comment]
> git commitする粒度（タイミング）はどれくらい

私の教祖の伊藤さんの良い記事を貼っておきます。
https://qiita.com/jnchito/items/40e0c7d32fde352607be

**Comment by hisayonr0717** [comment]
おー！
わざわざありがとうございます( ^ω^ )

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
