### ISSUE TITLE
第127回 tsuzy,うっちー,ツッチー

### ISSUE THREAD

**Issue by tsuchiya12345** [yochiyochirb/meetups#1396]

**Comment by uchinokot** [comment]
http://www.catb.org/jargon/html/H/hello-world.html

[Eric S. Raymond](https://ja.wikipedia.org/wiki/%E3%82%A8%E3%83%AA%E3%83%83%E3%82%AF%E3%83%BB%E3%83%AC%E3%82%A4%E3%83%A2%E3%83%B3%E3%83%89)のWebサイト

**Comment by uchinokot** [comment]
Unix
> コンピュータ用のマルチタスク・マルチユーザーのオペレーティングシステムの一種である

UNIXおよびUNIX系システムの系統図
https://ja.wikipedia.org/wiki/UNIX#/media/File:Unix_history-simple.svg

**Comment by tsuchiya12345** [comment]
RHEL、ubuntuはLinuxの系統？
FreeBSDってどのくらい使われてるのかな？？

**Comment by uchinokot** [comment]
bashとは
http://e-words.jp/w/bash.html

**Comment by tsuchiya12345** [comment]
Rackとは
https://railsguides.jp/rails_on_rack.html

> Rackは、Rubyのウェブアプリケーションに対して、最小限でモジュール化されていて、応用の効くインターフェイスを提供します。RackはHTTPリクエストとレスポンスを可能なかぎり簡単な方法でラッピングすることで、ウェブサーバー、ウェブフレームワーク、その間に位置するソフトウェア (ミドルウェアと呼ばれています) のAPIを一つのメソッド呼び出しの形にまとめます。

**Comment by tsuchiya12345** [comment]
> 残念ながら、経験上ちょっとしたマイナーアップグレードですら問題を引き起こすことがあります。

IBM Cloud PaaS(Cloud Foundry)で実際問題おきました。。。

**Comment by uchinokot** [comment]
Gemfileのバージョン指定

- `>=` という記法では常に最新のgemがインストール
- `~>` 4.0.0という記法ではマイナーバージョンの部分に相当するアップデート済みのgem (例: 4.0.0から4.0.1) をインストール

**Comment by tsuchiya12345** [comment]
bundle installとbundle updateの違い
https://qiita.com/lasershow/items/1a048d03ddaaba98171e

**Comment by tsuchiya12345** [comment]
1.3.1 Bundlerの最後まで読みました！

**Comment by uchinokot** [comment]
> `>=` という記法では常に最新のgemがインストール

他のgemで参照されている依存関係を解決するときに使う。
`Gemfile.lock` を見てみるとどんなライブラリがインストールされているか分かる。

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
