### ISSUE TITLE
第127回 ちなつ、Nao、popmac、いけだ

### ISSUE THREAD

**Issue by ikedakohei** [yochiyochirb/meetups#1398]

**Comment by ckanayama** [comment]
UnixのコマンドラインとLinuxコマンドラインの違いがわからない

**Comment by ikedakohei** [comment]
伽藍とバザール

**Comment by popmac** [comment]
http://sezemi.hatenablog.com/entry/2015/04/20/180558
> 伽藍とバザール*は，一部のエリートプログラマ達がクローズドに作る，いわゆる伽藍方式の方が，品質が良いソフトが出来るとされていたところに，すべてオープンにして世界中のプログラマがよってたかって開発するバザール方式で開発したLinuxが大成功し，それが何故できたのか，探求していくというお話で，後半はそのOSS開発コミュニティをどう作るのか，というお話でした．

**Comment by ikedakohei** [comment]
https://linuc.org/
Linuxの資格とりたい

**Comment by ckanayama** [comment]
別のOSで動かすの辛そう

**Comment by popmac** [comment]
`gem list | grep rails`

**Comment by ckanayama** [comment]
```
coffee-rails (4.2.2)
jquery-rails (4.3.1)
rails (5.2.0, 5.1.6, 5.1.4)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.4)
sass-rails (5.0.7, 5.0.6)
sprockets-rails (3.2.1)
```

**Comment by popmac** [comment]
```
rails (5.2.0, 5.1.4)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.4)
sprockets-rails (3.2.1)
```

**Comment by popmac** [comment]
cloud9、最初からrails入ってるみたい

**Comment by ckanayama** [comment]
フロントエンド 目線
http://liginc.co.jp/web/html-css/html/144170

**Comment by nao-aloha** [comment]
Webpacker
https://qiita.com/hiyamamoto/items/e0a30b4799314174b80f

**Comment by ikedakohei** [comment]
Gemfileのコメントは最初に消す?

**Comment by ikedakohei** [comment]
rootとroutesの呼び方

**Comment by nao-aloha** [comment]
Cloud9ショートカット集
https://qiita.com/ko_coon/items/e105e1bbca9bc7d2f1fa

**Comment by ikedakohei** [comment]
rails server -> rails s

**Comment by ckanayama** [comment]
JavaScriptランタイムエラーが発生したことのある人がいない

**Comment by popmac** [comment]
JavaScriptランタイムが無いというエラーでrails serverが起動しない場合 -- ぺけみさお https://www.xmisao.com/2014/03/08/rails-server-could-not-find-a-javascript-runtime.html

**Comment by popmac** [comment]
`node -v`

**Comment by ckanayama** [comment]
入ってました

**Comment by ckanayama** [comment]
[1.3.2 rails server](https://railstutorial.jp/chapters/beginning?version=5.1#sec-rails_server) まで進みました。

**Comment by popmac** [comment]
http://hai3.net/blog/2013/11/29/rails-javascript-runtime/
Node.jsが入っていないMacでRailsアプリが起動できるのは `therubyracer` のおかげなんだろうか...

**Comment by yucao24hours** [comment]
ミートアップが終了したので閉じます。気になった話題などがあったらまた reopen したり、新たに issue をたてたりしてみてください 😃
