### ISSUE TITLE
第128回 こんちゃん/たいき/ドバティ　

### ISSUE THREAD

**Issue by dobatty** [yochiyochirb/meetups#1399]

**Comment by 5t111111** [comment]
こちらに乱入します

**Comment by 5t111111** [comment]
https://railstutorial.jp/chapters/beginning?version=5.1#sec-rails_server

**Comment by konchanxxx** [comment]
cloud9のpros,consは何だろう？

**Comment by 5t111111** [comment]
welcome ページが変わったらしい
https://github.com/rails/rails/pull/32735

**Comment by dobatty** [comment]
ダイバーシティだけど、偏っている気も？w

**Comment by konchanxxx** [comment]
bundle install コマンドがあるが、 `bundle install --path vendor/bundle` でアプリケーション配下のディレクトリを指定した方が影響範囲を限定できるので良さそう

**Comment by 5t111111** [comment]
```
ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```

**Comment by dobatty** [comment]
cloud9を開発現場で聞いたことない？（観測範囲だけど） HackerNewsとかで話出たりするけど。。。

**Comment by dobatty** [comment]
インターフェイスの共通、動作環境（Mac/Windows）→dockerの充実、ランタイムの環境は揃えやすくなった。クラウド上で動かす楽しさが減った。

**Comment by konchanxxx** [comment]
図1.14は何でFirefox何だろう

**Comment by 5t111111** [comment]
MVC

**Comment by konchanxxx** [comment]
リスト1.7は変数展開がないのでシングルクォーテーションで良さそう

**Comment by konchanxxx** [comment]
Cloud9でのrails server起動方法

`rails s -b $IP -p $PORT`

https://qiita.com/daiki7nohe/items/558706ccad0408a89549

**Comment by konchanxxx** [comment]
ローカル環境へrails環境を構築する方法
https://qiita.com/yn01/items/2ea2a498b4a1eef7e1cd

**Comment by konchanxxx** [comment]
初心者におすすめの動画教材
ローカルにRails環境を構築する方法も学べる

https://dotinstall.com/lessons/basic_rails_v3

**Comment by konchanxxx** [comment]
個人的には
Schooとかもおすすめ
https://schoo.jp/

**Comment by konchanxxx** [comment]
1.4.1まで読んだ

**Comment by 5t111111** [comment]
1.4.1 の最後のほうまで読んだ (1.4.1 を読み終わってはいない)

**Comment by 5t111111** [comment]
じゃんけんで負けて発表者になりました

**Comment by kiitaaaaa** [comment]
ものすごく初心者な状態で参加してしまったのですが、優しく教えて下さりありがとうございます。
次回参加する時までに、今回よりも話について行けるように頑張ります！
