### ISSUE TITLE
第128回 つつみ、よしかわ、こたに、らいむ

### ISSUE THREAD

**Issue by lime1024** [yochiyochirb/meetups#1401]

**Comment by lime1024** [comment]
エラーは出てないけど**JavaScriptランタイム**ってなんやろってはなしに。

**Comment by nao-aloha** [comment]
https://msdn.microsoft.com/ja-jp/library/1dk3k160(v=vs.94).aspx

**Comment by hisayonr0717** [comment]
ランタイムとは
https://wa3.i-3-i.info/word13464.html

**Comment by kottyan** [comment]
shareでWebページ開けない？

**Comment by lime1024** [comment]
Railsのバージョンが、5.1.4を指定してインストールしたはずだけど、確認すると5.1.6に...
前回のよちよちでもそんな話出ていませんでしたっけ？

**Comment by lime1024** [comment]
1.3 終了しました！次回 1.4 からで大丈夫です。

**Comment by lime1024** [comment]
MVCが分からなくて、とりあえず図を書き出して照らし合わせながらすすめたら頭にはいってきた！

**Comment by lime1024** [comment]
https://git-scm.com/book/ja/v2
