### ISSUE TITLE
第128回 アダルトチーム yucao24hours, ManabuSeki, yuki3738, 5t111111, katorie

### ISSUE THREAD

**Issue by katorie** [yochiyochirb/meetups#1402]

**Comment by 5t111111** [comment]
よろしくお願いします

**Comment by 5t111111** [comment]
1.3.2 rails server から
https://railstutorial.jp/chapters/beginning?version=5.1#sec-rails_server

**Comment by ManabuSeki** [comment]
hi 😃

**Comment by ManabuSeki** [comment]
いきなりのJavascriptランタイム

## ExecJS supports these runtimes:
- therubyracer - Google V8 embedded within Ruby
- therubyrhino - Mozilla Rhino embedded within JRuby
- Node.js
- Apple JavaScriptCore - Included with Mac OS X
- Microsoft Windows Script Host (JScript)

どれか

**Comment by yuki3738** [comment]
PR チャンス
`MVCの3つの要素をすべて扱いします`

**Comment by yucao24hours** [comment]
Cloud9 でも Vim を開こうとする人たち...

**Comment by yucao24hours** [comment]
http://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-root

**Comment by yucao24hours** [comment]
Cloud9 のターミナルで `ls` とかをしてディレクトリ名をクリックすると、そのディレクトリが左のソースツリーに出てくるらしい（豆知識）

**Comment by ManabuSeki** [comment]
CUIにGUIを求めてはいけない

でも便利そう

```sh
ls
```

**Comment by yuki3738** [comment]
routes.rb を変更したら application の 再起動必要じゃね？という話をしてる。

**Comment by ManabuSeki** [comment]
typo警察くるよ 👮

**Comment by ManabuSeki** [comment]
Optionキー押しながら他のキー押した事ないわ

**Comment by yuki3738** [comment]
ゆかお typo collection

1. applicaton
2. boodbye

**Comment by yucao24hours** [comment]
茶目っ気を出して JSON 出してみた系
```ruby
  def goodbye
    render json: { greeting: "goodbye, world!" }
  end
```

**Comment by ManabuSeki** [comment]
pro Git
https://git-scm.com/book/ja/v2

**Comment by yuki3738** [comment]
意識高すぎて自然に git commit してしまった かとりえ

**Comment by ManabuSeki** [comment]
コメント間違えたから `git commit --amend`　使ったら `nano`で開いた

ツライ


vimにする方は下記を参照
```sh
git config --global core.editor 'vim -c "set fenc=utf-8"'
```

**Comment by yuki3738** [comment]
> 仮に、あなたが重要なapp/controllers/ディレクトリを削除してしまったとしましょう。

ねーよ。

**Comment by ManabuSeki** [comment]
# これでひと安心です。

**Comment by yuki3738** [comment]
1.4.2 が終わった！

**Comment by yucao24hours** [comment]
1.4.2 の最後までよんだ

**Comment by konchanxxx** [comment]
https://ja.stackoverflow.com/questions/8228/rails%E3%81%AE%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E5%A4%89%E6%9B%B4%E3%81%AE%E8%87%AA%E5%8B%95%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%81%BF%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
らc
