### ISSUE TITLE
第128回tsujihashi,popMac,kani,tararico

### ISSUE THREAD

**Issue by KohichiTsujihashi** [yochiyochirb/meetups#1403]

**Comment by popmac** [comment]
popmac:~/environment $ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by kanikani2929** [comment]
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]

**Comment by tararico** [comment]
ruby 2.4.1p111 (2017-03-22 revision 58053)[x86_64-darwin16]

**Comment by popmac** [comment]
ちなみに `ls -alF` で同じ階層にあるディレクトリとファイルが見れます

**Comment by KohichiTsujihashi** [comment]
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by kanikani2929** [comment]
Rails 5.1.4

**Comment by popmac** [comment]
popmac:~/environment $ rails -v
Rails 5.2.0

**Comment by KohichiTsujihashi** [comment]
Rails 5.2.0

**Comment by tararico** [comment]
Rails 5.1.4

**Comment by popmac** [comment]
cloud9でブラウザ開くの難しいと思ったら書いてあった...

**Comment by KohichiTsujihashi** [comment]
ブラウザ開けた！

**Comment by popmac** [comment]
MVCはどうして「models」「views」「controllers」という順番なんだろう...

処理の流れは「controllers」「models(使わない時もある)」「views」かなと思っているんですが...

**Comment by kanikani2929** [comment]
https://qiita.com/tori_rito/items/38b2f180343cdc3ab7ac

**Comment by kanikani2929** [comment]
https://qiita.com/kt3k/items/cbb4a8ceffd52741b9a4

**Comment by popmac** [comment]
` ls app/controllers/*_controller.rb`
これって正規表現かワイルドカードかどっちだろう？

**Comment by kanikani2929** [comment]
> カードゲームのワイルドカードに由来する呼称。 UNIXのシェルでは、「 ? 」（疑問符）を任意の一文> > 字、「 * 」（アスタリスク）を長さ0文字以上の任意の文字列にマッチするパターンとして、コマンド> > ライン上で、存在するファイルの名前に対して展開される。

https://ja.wikipedia.org/wiki/%E3%83%AF%E3%82%A4%E3%83%AB%E3%83%89%E3%82%AB%E3%83%BC%E3%83%89_(%E6%83%85%E5%A0%B1%E5%87%A6%E7%90%86)

**Comment by popmac** [comment]
https://qiita.com/whisky-shunsuke/items/d719c92c566c133f51b1

**Comment by popmac** [comment]
一旦この疑問から脱出します...

**Comment by popmac** [comment]
cloud9って自動保存じゃないのね...

**Comment by kanikani2929** [comment]
ASCII文字
http://e-words.jp/w/ASCII%E6%96%87%E5%AD%97.html

**Comment by popmac** [comment]
普段はビューファイルがあるので `render html: "hello, world"` みたいに書かないなと思いました
`render json` とか `render layout` は書くけれど...

**Comment by popmac** [comment]
`1.4.1 インストールとセットアップ` の途中までやりました😊

**Comment by 5t111111** [comment]
https://github.com/yochiyochirb/meetups/issues/1403#issuecomment-399927501

これはワイルドカードですね〜

**Comment by popmac** [comment]
ありがとうございます❗

**Comment by konchanxxx** [comment]
これでauto saveできるのかな（小並感
https://community.c9.io/t/c9-user-options-auto-save-is-not-showing-up/778

**Comment by tararico** [comment]
@rexitorg ありがとうございます！

**Comment by konchanxxx** [comment]
AWSでなくなった...??
https://community.c9.io/t/auto-save-on-aws-c9/21330
