### ISSUE TITLE
第129回 いけだ、ちなつ、らいむ

### ISSUE THREAD

**Issue by lime1024** [yochiyochirb/meetups#1404]
こんにちは！こんにちは！

**Comment by ckanayama** [comment]
Linus Torvalds リーナス・トーバルズ

**Comment by ikedakohei** [comment]
GitってLinuxの開発者がつくったの？

**Comment by ikedakohei** [comment]
Linuxのキャラクターの名前はTux(タックス)

**Comment by lime1024** [comment]
ソースコードだけじゃなくても、バージョン管理って大事ですよね。
会社にあるファイルで hoge(2).拡張子 とか、新hoge.拡張子 とか見るとどれが新しいのかわからなくなる現象がよく発生する

**Comment by ckanayama** [comment]
前回ちゃんとコードを音読しなかったけれど、今回はコードも音読している

**Comment by ckanayama** [comment]
`git config user.email`

**Comment by ckanayama** [comment]
個別メールアドレスを使い分けたい時

$ git config user.name "John Doe"
$ git config user.email johndoe@example.com

**Comment by ikedakohei** [comment]
https://qiita.com/shionit/items/fb4a1a30538f8d335b35
`local`と`global`の違いは...?

**Comment by lime1024** [comment]
`git init` を実行する階層を間違えた！
`.git` リポジトリが1階層上にもできあがってしまった！

**Comment by ikedakohei** [comment]
リポジトリって何だろう？

**Comment by ikedakohei** [comment]
リポジトリって`git init`されたディレクトリ？もしくはgit以外のバージョン管理システム使用されててもいいのかもですが...

**Comment by ckanayama** [comment]
git入ってないとリポジトリじゃ無いのか？

リポジトリ: 情報が保管されているデータベース
なのでgitが入ったらgitリポジトリということ？

**Comment by lime1024** [comment]
世間は冷たい
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q10121667680

**Comment by ikedakohei** [comment]
Git リポジトリなる言葉がある
https://git-scm.com/book/ja/v1/Git-%E3%81%AE%E5%9F%BA%E6%9C%AC-Git-%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE%E5%8F%96%E5%BE%97

**Comment by ikedakohei** [comment]
ローカル・リポジトリ -> ローカルマシン上で管理されているリポジトリ
リモート・リポジトリ -> GitHubなどで管理されているリポジトリ

**Comment by lime1024** [comment]
ディレクトリとは単にフォルダ(階層構造)って覚えておけば良さそう？
リポジトリはこれがわかりやすそうだった
https://backlog.com/ja/git-tutorial/intro/intro1_2.html

**Comment by lime1024** [comment]
Cloud9 で .gitignore を見ようとしても見せへんで〜ってされる...つれない......

**Comment by ikedaCoffee** [comment]
c9 open ファイル名

**Comment by lime1024** [comment]
`bash: c9: command not found`

**Comment by ckanayama** [comment]
環境設定 → Find in Files → ignore there files
で見られる。驚き。

**Comment by ckanayama** [comment]
>隠しファイルを表示するには、[Environment (環境)] ウィンドウで歯車アイコンを選択してから、次のように [Show Hidden Files (隠しファイルを表示する)] を選択します。

**Comment by lime1024** [comment]
memo : 帰ったら Atom IDE を調べる

**Comment by ckanayama** [comment]
Atom IDE使いたい
https://ide.atom.io/
https://atom.io/packages/ide-ruby

**Comment by ckanayama** [comment]
`git diff --staged`は何もなかったら無視されるけど、
`git status`はちゃんと
`On branch master
nothing to commit, working tree clean`
教えてくれる
（でもGUIが一番見やすい・・・）

**Comment by lime1024** [comment]
less is...

**Comment by ckanayama** [comment]
recursive : リカーシブ

**Comment by lime1024** [comment]
1.4.2までおわり(最後はちょっと駆け足だったけど)

**Comment by lime1024** [comment]
less is 強いcat...？
