### ISSUE TITLE
第129回 こんちゃん、おさか、くめ

### ISSUE THREAD

**Issue by kumewata** [yochiyochirb/meetups#1406]

**Comment by kumewata** [comment]
よろしくお願いします！

**Comment by konchanxxx** [comment]
よろしくですー by konchan

**Comment by KazuyaOsaka** [comment]
テスト

**Comment by KazuyaOsaka** [comment]
よろしくおねがいします！

**Comment by kumewata** [comment]
"分散"バージョン管理システムとは？

分散<=>中央


[ガチで5分で分かる分散型バージョン管理システムGit (3/6)](http://www.atmarkit.co.jp/ait/articles/1307/05/news028_3.html)

**Comment by konchanxxx** [comment]
Git開発者 Linus Torvalds

https://cdn-ak.f.st-hatena.com/images/fotolife/m/mochizuki_p/20170221/20170221190858.png

**Comment by yucao24hours** [comment]
"SIer ではまだ SVN が多い気がします"

**Comment by yucao24hours** [comment]
COBOL は秀丸で書く

**Comment by KazuyaOsaka** [comment]
cloud9は統合開発環境（前回の復習？）

**Comment by konchanxxx** [comment]
COBOLのエディタ
https://qiita.com/nonbiri15/items/d6716f5cea30f2708bc2

**Comment by kumewata** [comment]
最悪--abortで回避

**Comment by KazuyaOsaka** [comment]
サルでもわかるGit
https://backlog.com/ja/git-tutorial/

**Comment by konchanxxx** [comment]
pushする時使ってるやつ

`git push -u origin HEAD`

**Comment by yucao24hours** [comment]
https://github.com/yochiyochirb/sandbox GitHub 練習用リポジトリです！ご自由にお使いください〜

**Comment by konchanxxx** [comment]
ローカルでわけわからなくなった時とりあえず変更を一時領域に退避させる

```
$ git add . && git stash
```

**Comment by kumewata** [comment]
Gitはライブラリ
GitHubはWebサービス

**Comment by konchanxxx** [comment]
共通的に無視するような設定
global_ignore
https://qiita.com/elzup/items/4c92a2abdab56db3fb4e

**Comment by konchanxxx** [comment]
gitignore_globalか

**Comment by kumewata** [comment]
リポジトリが増えてくると毎度.gitignoreを書くのが面倒になる。
->そういう時は、gitignore_globalに書く。

* [グローバルで.gitignoreを適応する](https://qiita.com/katsew/items/5cade12fa743a2f31f25)
* [gitignore に書くべきでないものは gitignore_global へ](https://qiita.com/elzup/items/4c92a2abdab56db3fb4e)

**Comment by kumewata** [comment]
git add
-> Gitが変更ファイルを意識し始める:eye:

**Comment by kumewata** [comment]
vimハラ...?

**Comment by kumewata** [comment]
[Vim Mnemonic | Vim のコマンドの覚え方大全](http://haya14busa.com/vim-mnemonic/)

**Comment by kumewata** [comment]
マウスとかいらないんですよ

**Comment by KazuyaOsaka** [comment]
-mフラグ　=　-mオプション

**Comment by yucao24hours** [comment]
"-m を フラグ と呼ぶのは一般的なの？"

**Comment by kumewata** [comment]
ローカルリポジトリ、リモートリポジトリ
cloud9から始めると紛らわしい気がする。。

**Comment by kumewata** [comment]
ドキドキしながら
```
rm -rf
```

**Comment by kumewata** [comment]
1.4.2の途中まで進みました。
