### ISSUE TITLE
第129回　popmac/どばてぃ/たいき

### ISSUE THREAD

**Issue by kiitaaaaa** [yochiyochirb/meetups#1408]

**Comment by popmac** [comment]
よろしくお願いします😊

**Comment by dobatty** [comment]
よろしくおねがいしますー！

**Comment by kiitaaaaa** [comment]
よろしくお願いします！

**Comment by dobatty** [comment]
Gitが入っているかの確認:)

**Comment by popmac** [comment]
`git --version`

**Comment by popmac** [comment]
git version 2.14.1

**Comment by dobatty** [comment]
git version 2.14.1

**Comment by kiitaaaaa** [comment]
git version 2.15.2

**Comment by dobatty** [comment]
ruby 2.4.1

**Comment by dobatty** [comment]
みんな大好きSourceTree?

**Comment by dobatty** [comment]
猛者の方々はどうなんでしょう？？？

**Comment by dobatty** [comment]
VS code、ターミナルの同画面起動がいい感じ（統合ターミナル）

**Comment by dobatty** [comment]
spotlight は便利やね

**Comment by dobatty** [comment]
初心者でもできた！Ruby on Rails開発環境の構築方法（Mac編）
https://techacademy.jp/magazine/4630

**Comment by dobatty** [comment]
ローカル環境でのrubyサンプルプログラム初実行＼（＾〇＾）／

**Comment by dobatty** [comment]
https://www.rubylife.jp/install/install/index4.html

**Comment by popmac** [comment]
Gitの設定をgit configで確認・変更 | note.nkmk.me https://note.nkmk.me/git-config-setting/

**Comment by popmac** [comment]
git config の global の設定はどこで行っている？

**Comment by popmac** [comment]
$ git config user.name
popmac

**Comment by popmac** [comment]
global はこっちか

$ git config --global user.name
popmac

**Comment by popmac** [comment]
gitconfig の基本を理解する - Qiita https://qiita.com/shionit/items/fb4a1a30538f8d335b35

**Comment by dobatty** [comment]
--local, --global, --system の使い分けは？

**Comment by popmac** [comment]
ここに global の設定が書いてあるのかな
`~/.gitconfig`

**Comment by popmac** [comment]
`cat ~/.gitconfig`

**Comment by dobatty** [comment]
$で1行やで〜〜

**Comment by dobatty** [comment]
とりあえず@example.comで。あとで変更した方がよいかな

**Comment by dobatty** [comment]
historyコマンド

**Comment by konchanxxx** [comment]
> みんな大好きSourceTree?

自分は `tig` です〜
https://qiita.com/suino/items/b0dae7e00bd7165f79ea

**Comment by popmac** [comment]
GitKraken かっこいい
https://www.gitkraken.com/

**Comment by konchanxxx** [comment]
GitHubのクライアントとか進化してほc
https://desktop.github.com/

**Comment by popmac** [comment]
1.4.1 インストールとセットアップ の途中(.gitignoreのところ)まで読みました

**Comment by kiitaaaaa** [comment]
本日は沢山教えて頂きありがとうございました！
