### ISSUE TITLE
第130回 アダルトチーム ゆかお がく ぷぽ わかすぎ みなみや

### ISSUE THREAD

**Issue by yuki3738** [yochiyochirb/meetups#1410]
🌞🌞 🌞 🌞 🌞

**Comment by 5t111111** [comment]
🌞 🌞 🌞 🌞 🌞 🌞

**Comment by ManabuSeki** [comment]
hi 😄

**Comment by pupupopo88** [comment]
👀

**Comment by 5t111111** [comment]
1.4.3 Bitbucket 〜
https://railstutorial.jp/chapters/beginning?version=5.1#sec-bitbucket から

**Comment by 5t111111** [comment]
> Bitbucketではリポジトリを非公開にしても容量無制限かつ無料で利用できます。

Bitbucket リポジトリのサイズあるという認識
https://ja.confluence.atlassian.com/bitbucket/reduce-repository-size-321848262.html

**Comment by yuki3738** [comment]
制限入っちゃったんすかね

**Comment by 5t111111** [comment]
GitLabへのインポートが普段の10倍に急増、GitHubの買収報道で
https://www.publickey1.jp/blog/18/gitlab10github.html

**Comment by yuki3738** [comment]
bitbucket に 「課題」っていう機能がある人とない人がいる 👀

**Comment by 5t111111** [comment]
Bitbucket、UI  がだいぶ変わってる

**Comment by ManabuSeki** [comment]
全く関係ないけど　ぶっ込み

http://csirt.ninja/?p=1441

**Comment by ManabuSeki** [comment]
![image](https://user-images.githubusercontent.com/7938885/43075346-815d7536-8ebb-11e8-955c-6e65e0898b26.png)

↑をやった結果です
自分は悲しくなった

**Comment by ManabuSeki** [comment]
うう
MongoDB漏れたんか

![image](https://user-images.githubusercontent.com/7938885/43075375-9f08cb4e-8ebb-11e8-87f8-456d08c79582.png)

**Comment by yuki3738** [comment]
cloud 環境に戸惑う老害達…

**Comment by pupupopo88** [comment]
老害「もうlocalでrails newしてpushしよ」

**Comment by 5t111111** [comment]
`git push` の `--all` オプションあんま使わない

**Comment by pupupopo88** [comment]
「`git push -u origin --all` しとけばいいよね」って認識になっちゃうとよくなさそう。

**Comment by pupupopo88** [comment]
**「よい習慣を形成するには早すぎる」ということはない**

**Comment by pupupopo88** [comment]
コミットメッセージが適当で困った話で盛り上がる

**Comment by yuki3738** [comment]
「頭来たからcloud9にtig入れちゃった」

**Comment by ManabuSeki** [comment]
なぜHeyなんだ

**Comment by pupupopo88** [comment]
bitbucker使ったことなかったけどなかなか良さそう。
デザインよい

**Comment by yuki3738** [comment]
今日は [1.5 デプロイする](https://railstutorial.jp/chapters/beginning?version=5.1#sec-deploying) までやりました！！

**Comment by ManabuSeki** [comment]
セキュリティ情報

[プレミアム・アウトレット会員情報漏えい事件](http://foxsecurity.hatenablog.com/entry/2018/04/16/090000)
