### ISSUE TITLE
第130回 くめ、つじはし、いがらし、らいむ

### ISSUE THREAD

**Issue by lime1024** [yochiyochirb/meetups#1411]
こんにちは！こんにちは！

**Comment by kumewata** [comment]
よろしくお願いします！

**Comment by ekrc-1** [comment]
よろしくお願いします！！

**Comment by kumewata** [comment]
今日のお役立ち
[Mac - 接続している Wi-Fi のパスワードを表示（確認）](https://pc-karuma.net/mac-wi-fi-password-display/)

**Comment by lime1024** [comment]
Github でも同じことができる？？？

**Comment by ekrc-1** [comment]
ssh公開鍵←雰囲気で使っている

**Comment by kumewata** [comment]
SSH？

[SSH通信って、結局何してるの？](https://qiita.com/naoki_mochizuki/items/aea14a65a4a513e4816f)

**Comment by lime1024** [comment]
Bitbucket じゃなくて Github でやることになったので、公開鍵登録した！

**Comment by lime1024** [comment]
Github のリポジトリの作成ってどうやってやるの？

**Comment by lime1024** [comment]
書かなくても README は作るべきらしい

**Comment by kumewata** [comment]
インフラエンジニアにも物理寄りと非物理寄りのジャンルがある

**Comment by lime1024** [comment]
物理寄りっていい方が正しいかわからないのですが、私は閉空間における無線機とアンテナの設置数とか、給電線の長さとかそれに伴って無線局の免許がどうのとか、なんかそっち系のインフラやってます

**Comment by kumewata** [comment]
チュートリアルどおりでもなかなか詰まる^^;

**Comment by lime1024** [comment]
```sh
$ git remote add origin git@github.com:ユーザー名/hello_app.git
```

が最初できなくて困ったけど`hello_app/`に入ってもう一回コマンド打ち込んだらいけた

**Comment by ekrc-1** [comment]
BitBucketで新規リポジトリ作成時、`Include a README?` をNoにしないとTutorialとは別のページが表示される

**Comment by lime1024** [comment]
> `Please type 'yes' or 'no':`

`yes or no` を `y` で答えたら yes か no で答えろって怒られた ひぇ

**Comment by ekrc-1** [comment]
`$ git push -u origin master` したら赤色でなんか出た(Cloud9, BitBucket)
```
remote: 
remote: We're changing our IP addresses starting 29 July 2018 at 22:00 UTC.
remote: Please make sure your firewalls are up to date:
remote: https://blog.bitbucket.org/?p=3707
```

**Comment by kumewata** [comment]
途中から開発に入る時は```git clone```でリポジトリを落としてくる機会の方が多いかも

**Comment by lime1024** [comment]
ぶらんちってなんだろう

**Comment by ekrc-1** [comment]
↑こんなのあるんだ・・・↓
「シュタゲで分かるGit」をテーマにした「Steins;Git」
http://blog.o2p.jp/2014/07/23/c86-steins-git/

**Comment by lime1024** [comment]
シュタゲのgit入門、これオススメらしいですよ(オススメされて未だ読んでないけど

**Comment by ekrc-1** [comment]
1.4.4 ブランチ、編集、コミット、マージ の「Branch」まで

**Comment by kumewata** [comment]
Gitを使うための通信プロトコルは4つある
