### ISSUE TITLE
第130回　けん　ちなつ　いっせー

### ISSUE THREAD

**Issue by muurann** [yochiyochirb/meetups#1412]

**Comment by ckanayama** [comment]
>ホスティングとは、インターネットサービスプロバイダなどが、お客様のメールサービスやウェブサービスをお預かりし、運用するサービスです。

私たちのコードをBitbucketさんが預かってくれる感じ？

**Comment by ken3ypa** [comment]
ホスティング　≒　管理？中央に集める感じ

**Comment by ckanayama** [comment]
容量制限はありません

**Comment by ken3ypa** [comment]
Github 公開とか非公開　なんのため？

■公開のメリット
・転職の際など見せられる
・他の人にソースコード見せて改善を仰げる

■非公開のメリット
・会社で管理したいときとか、見せたくないもの入ってたりするときとか

**Comment by ken3ypa** [comment]
Labはラボ　のっと　ラブ

**Comment by ken3ypa** [comment]
keygen は key + generate

**Comment by ckanayama** [comment]
SSHあわあわする・・・

**Comment by ckanayama** [comment]
cat = catenate = 	(…を)鎖状に(連結)する

**Comment by ken3ypa** [comment]
cat は catenate の略
闇が深くなった

**Comment by ken3ypa** [comment]
id_rsa.pub　←公開鍵(.publicの略)
id_rsa　←秘密鍵

**Comment by ken3ypa** [comment]
http://bigchu.com/ssh-known_hosts.html
known_hostsについて

**Comment by ckanayama** [comment]
秘密鍵と公開鍵
https://milestone-of-se.nesuke.com/sv-advanced/digicert/public-private-key/

**Comment by muurann** [comment]
https://knowledge.sakura.ad.jp/3543/
公開鍵認証方式　簡単説明

**Comment by ken3ypa** [comment]
http://www.koikikukan.com/archives/2013/01/31-005555.php
・クライアント、[秘密鍵・公開鍵]を作成
・Bitbucketに公開鍵を登録
・サーバ、渡した公開鍵で暗号化を渡す
・クライアント、暗号化されたデータを、最初に作った秘密鍵で復号化？

**Comment by ken3ypa** [comment]
>-uについて

-u と --set-upstream は同じ意味です。このオプションをつけるとローカルリポジトリの現在のブランチの上流をorigin master に規定したことになります。

■上流ブランチ
http://www-creators.com/archives/4931

**Comment by ken3ypa** [comment]
1.4.3 Bitbucket　まで読了

**Comment by ManabuSeki** [comment]
前に作った資料を放流します

https://drive.google.com/file/d/1Yqgo3vPuI_hsU3jlWTrCvWaEIrSwVty9/view

**Comment by 5t111111** [comment]
公開鍵暗号方式 (公開鍵基盤 = PKI) の理解の第一歩的なので個人的オススメページ
https://persol-tech-s.co.jp/corporate/security/article.html?id=26

**Comment by ken3ypa** [comment]
色々な繋ぎ方あるんですね
https://git-scm.com/book/ja/v1/Git-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-%E3%83%97%E3%83%AD%E3%83%88%E3%82%B3%E3%83%AB

**Comment by ckanayama** [comment]
gitを使うためのプロトコル色々
Local、Secure Shell (SSH) ←今日設定したやつ、Git、 HTTP

**Comment by 5t111111** [comment]
そうそう、さっき言ったのまさに↑の話です。
実際に現実世界 (というかインターネット越しの世界) では HTTP (S) / Secure Shell (SSH) のいずれかしか使わないです。

**Comment by ken3ypa** [comment]
ざっくり
Git： ローカル環境でソース管理するためのツール
Github ：Gitを複数人で管理するシステム
