### ISSUE TITLE
第130回　ツッチー、ノブ、トモ

### ISSUE THREAD

**Issue by tomo358** [yochiyochirb/meetups#1413]

**Comment by tsuchiya12345** [comment]
git pushの-uフラグ：
「追跡ブランチ」むずい。。

**Comment by tomo358** [comment]
リモート追跡ブランチは「ローカルリポジトリにあって、他のリポジトリの状態を追跡するブランチ」
よく分からない...

**Comment by Nobu777** [comment]
リモートリポジトリ＝共有のリポジトリ
ローカルリポジトリ＝自分のパソコンのリポジトリ？

**Comment by tsuchiya12345** [comment]
これ参考になる？

> ローカルにはmaster とorigin/masterの2つのブランチが存在する。
> master はローカルの更新を見ている。

>「ローカルにはmaster とorigin/masterの2つのブランチが存在する」と上で書きましたが、origin/masterはmasterブランチのリモートブランチであり、追跡ブランチです。

http://snowlong.hatenablog.com/entry/2015/03/12/212455

**Comment by tsuchiya12345** [comment]
https://www.kaeruspoon.net/articles/1078

**Comment by Nobu777** [comment]
origin/master=リモートブランチ（追跡ブランチ）

ローカルリポジトリ内のmasterブランチを-uでローカルにあるorigin/masterに同期することで、
リモートブランチとなり共有される。

**Comment by tsuchiya12345** [comment]
> HerokuではPostgreSQLデータベースを使います

この段階でherokuデプロイするのか。。。
DBまでpostgresで。。

**Comment by tomo358** [comment]
rails db:create コマンドを打ったら、デフォルトでsqliteデータベースになりました。

**Comment by tomo358** [comment]
1.4.3 Bitbucketまでです
