### ISSUE TITLE
第131回　popmac たいき　たらりこ

### ISSUE THREAD

**Issue by kiitaaaaa** [yochiyochirb/meetups#1414]

**Comment by tararico** [comment]
よろしくお願いします〜〜

**Comment by popmac** [comment]
よろしくおねがいします🙏

**Comment by kiitaaaaa** [comment]
よろしくお願いします！

**Comment by tararico** [comment]
## markdownについて 
* 書き方
* 色々書いてみて試す
` コマンド`

**Comment by tararico** [comment]
branchってなに？

**Comment by popmac** [comment]
<img width="198" alt="2018-08-06 21 20 03" src="https://user-images.githubusercontent.com/19648958/43716265-8319f738-99be-11e8-878e-631dfad36db4.png">

**Comment by tararico** [comment]
なるほど

**Comment by popmac** [comment]
> git commitには現存するすべてのファイル (git mvで作成したファイルも含む) への変更を一括でコミットする-aフラグがあります。

`git commit -am 'コミットメッセージ'` って書く人がいるのは、そういうことか...

**Comment by tararico** [comment]
mergeとは

**Comment by popmac** [comment]
Cloud9、commitするごとに `.c9/metadata/tab1` みたいなのが生成されて master に checkout できない...

**Comment by popmac** [comment]
上記の問題は `~/environment` で `git init` したのが原因でした💦

とりあえず `rm -rf .git/` で `~/environment` をGit管理下から外しました

**Comment by tararico** [comment]
1.5 デプロイの手前、mergeするところまで進みました。
