### ISSUE TITLE
第131回 きど、ゆうや、こたに、くめ

### ISSUE THREAD

**Issue by kumewata** [yochiyochirb/meetups#1417]

**Comment by kumewata** [comment]
よろしくお願いします！

**Comment by ShinsukeKido** [comment]
ありがとうございます！

**Comment by yuya-yamashita** [comment]
お願いします！

**Comment by kottyan** [comment]
よろしくおねがいします

**Comment by kumewata** [comment]
噂？のJira
https://ja.atlassian.com/software/jira

**Comment by yuya-yamashita** [comment]
現場ではどこまでREADMEを書くの？

**Comment by yuya-yamashita** [comment]
環境構築の手順も書くらしい

**Comment by kottyan** [comment]
READMEはそのアプリを起動するときにセットアップすること、手順などを書いておく!(^^)!

**Comment by kumewata** [comment]
プロジェクトにジョインした人向けに環境構築とか
わりと雑に書いてるので、参加したばかりのメンバーの最初のコミットがREADMEの修正をすることが多いかも。。

**Comment by yuya-yamashita** [comment]
gitはcui、guiどっちが良い？

**Comment by ShinsukeKido** [comment]
git 操作、GUI? CLI?

**Comment by yuya-yamashita** [comment]
http://tracpath.com/bootcamp/learning_git_gitkraken.html

**Comment by kumewata** [comment]
GitKraken
https://www.gitkraken.com/

**Comment by kumewata** [comment]
ブランチ名どうつける？

**Comment by yuya-yamashita** [comment]
ブランチ名は機能名タスク名かfuture？

**Comment by kumewata** [comment]
タスク管理ツールがつけるIDとセットでつける？

**Comment by ShinsukeKido** [comment]
オフィス移転パーティー！！！

**Comment by kumewata** [comment]
そば屋で乾杯 #2
https://sobanomi.connpass.com/event/97182/?utm_campaign=event_publish_to_follower&utm_medium=twitter&utm_source=notifications

**Comment by yuya-yamashita** [comment]
https://www.udemy.com/unscared_git/

おすすめです

**Comment by kumewata** [comment]
[Git]ファイルを移動する(git mv)
http://tech.katsubemakito.net/git/git_move

**Comment by yuya-yamashita** [comment]
@yuya05020

**Comment by kumewata** [comment]
表参道.rb #37 ~ Ruby/Railsの学び方 ~
https://omotesandorb.connpass.com/event/95518/

Otemachi.rb #9
https://enechange-meetup.connpass.com/event/94799/

大江戸Ruby会議07
https://asakusarb.doorkeeper.jp/events/77378

**Comment by yuya-yamashita** [comment]
https://regional.rubykaigi.org/

**Comment by ShinsukeKido** [comment]
[メタプログラミングRuby](https://www.amazon.co.jp/%E3%83%A1%E3%82%BF%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0Ruby-%E7%AC%AC2%E7%89%88-Paolo-Perrotta/dp/4873117437)

**Comment by kumewata** [comment]
ゆるふわクリエーターバスケ vol.5
https://sport-creator.connpass.com/event/96476/

**Comment by yuya-yamashita** [comment]
https://www.amazon.co.jp/dp/B071V7MY82/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1

プリンシプル オブ プログラミング 3年目までに身につけたい 一生役立つ101の原理原則

**Comment by kumewata** [comment]
英語のネーミングに困ったら
https://codic.jp/

**Comment by yuya-yamashita** [comment]
トピックブランチは残す派が多い？

**Comment by yuya-yamashita** [comment]
マージは誰でもできるチームもある

**Comment by yuya-yamashita** [comment]
チームによっては特定の人しかマージしないというルールを設けている場合もある

**Comment by yuya-yamashita** [comment]
https://qiita.com/mint__/items/bfc58589b5b1e0a1856a

git flow git hub flow違い

**Comment by kumewata** [comment]
1.4.4の最後までdone

**Comment by kottyan** [comment]
現場では-b切ったのを先にpushしてOKもらってからpullする！！

**Comment by kumewata** [comment]
```git remote -v```でリモートの向き先を確認できる(fetchとpush)。
