### ISSUE TITLE
第131回 のぶ、つじはし、くりはら、いけだ

### ISSUE THREAD

**Issue by ikedakohei** [yochiyochirb/meetups#1418]

**Comment by ikedakohei** [comment]
よろしくお願いしますー！

**Comment by KohichiTsujihashi** [comment]
宜しくお願いします！

**Comment by acculief** [comment]
よろしくおねがいます^ - ^

**Comment by acculief** [comment]
.md はMarkdownの略。
HTMLに簡単に変換でき、Bitbucketでも自動的にHTMLで表示してくれる

**Comment by ikedakohei** [comment]
1.3からスタートに変更！

**Comment by acculief** [comment]
gem 'hoge' , '>= 1.3.0'
1.3.0以上の最新バージョンのgemがインストールされる
gem 'hoge', '~> 4.0.0'
gemのバージョンを指定可能！

**Comment by ikedakohei** [comment]
https://qiita.com/bluegirl_beer/items/02c4bacd5bb862535d9d

**Comment by ikedakohei** [comment]
1.3.4らへんまで作業しましたー！

**Comment by 5t111111** [comment]
> gem 'hoge', '~> 4.0.0'
> gemのバージョンを指定可能！

もしかしたら誤解があるかもしれないので一応補足すると、
これは正確には

```
4.0.0以上で、最後の数値以外のバージョンが同じ (つまり 4.0.5 は OK だけど 4.1.0 は NG)
```

ものの指定になります
