### ISSUE TITLE
第132回　けん　popmac　くめ　しげみつ

### ISSUE THREAD

**Issue by shogoshigemitsu** [yochiyochirb/meetups#1422]

**Comment by ken3ypa** [comment]
よろしくお願いします！

**Comment by kumewata** [comment]
よろしくお願いします！

**Comment by popmac** [comment]
よろしくお願いします！

**Comment by shogoshigemitsu** [comment]
宜しくお願いいたします。

**Comment by popmac** [comment]
デプロイって配置するとか展開するって意味か

**Comment by popmac** [comment]
「日本酒をデプロイする」という使い方もあるらしい

**Comment by kumewata** [comment]
Phusion Passenger?

**Comment by ken3ypa** [comment]
![image](https://user-images.githubusercontent.com/28388130/44658008-f67c5000-aa39-11e8-97fa-b8a6fbe86133.png)

**Comment by ken3ypa** [comment]
https://qiita.com/kurosawa_kuro/items/d3927bdaa68b02a42036#%E9%BB%92%E6%BE%A4-%E3%81%8A%E3%81%99%E3%81%99%E3%82%81%E3%82%BB%E3%83%83%E3%83%88https://qiita.com/kurosawa_kuro/items/d3927bdaa68b02a42036

**Comment by ken3ypa** [comment]
DOM　説明
http://www.doraneko.org/misc/dom10/19981001/introduction.html

**Comment by ken3ypa** [comment]
Nodeの立ち位置どこよ

**Comment by popmac** [comment]
Node.js とは何か？ - Qiita https://qiita.com/kobalab/items/e0c2a3d5a9f4c172bad0

> 1. Node.jsとはJavaScript処理系である
> 2. 付属ライブラリはノンブロッキングI/Oが特徴である
> 3. ライブラリの参照方法が異なるため、ブラウザ上のJavaScriptと互換性がない

**Comment by shogoshigemitsu** [comment]
アパッチとは
https://www.kagoya.jp/howto/rentalserver/apache/

**Comment by ken3ypa** [comment]
もでゅ〜る？

**Comment by popmac** [comment]
module | ロングマン現代英英辞典でのmoduleの意味 | LDOCE https://www.ldoceonline.com/jp/dictionary/module

> one of several parts of a piece of computer software that does a particular job

Google翻訳したもの
特定の仕事をするコンピュータソフトウェアのいくつかの部分の1つ

**Comment by ken3ypa** [comment]
ApacheやNginxなどに載せられるmoduleがPhusion Passenger

**Comment by popmac** [comment]
Herokuでデプロイした時にデフォルトで使われるWebサーバって何だろう？

**Comment by popmac** [comment]
言語によって違うっぽい？

**Comment by ken3ypa** [comment]
Hero + HaikuでHerokuらしい
http://www.youtube.com/watch?v=jDQT__oLnZU

**Comment by popmac** [comment]
Herokuにデプロイする時はGitHubを通さないとできない？

https://b-side.work/2017/02/heroku-and-git/
http://patriae.hatenablog.com/entry/2015/02/07/181907

じゃなくて `git heroku push master` はHerokuの中のリモートリポジトリを指してて、GitHubにコードを上げておく必要はないってことか

そういえば `git remote add heroku <Heroku上のリポジトリのURL>` ってやってた💦

**Comment by kumewata** [comment]
変数を分離させておく話
[Twelve-Factor App](https://12factor.net/ja/)

[とにかく分かりづらいTwelve-Factor Appの解説を試みる](https://www.slideshare.net/masatoshitada7/twelvefactor-app)

**Comment by ken3ypa** [comment]
git push heroku master ←Herokuのリモートリポジトリを見にいってる
git push origin master ←Gitのリモートリポジトリを見にいってる

**Comment by kumewata** [comment]
[Git submodule の基礎](https://qiita.com/sotarok/items/0d525e568a6088f6f6bb)

**Comment by ken3ypa** [comment]
サブモジュールなるものがあるらしい
https://git-scm.com/book/ja/v1/Git-%E3%81%AE%E3%81%95%E3%81%BE%E3%81%96%E3%81%BE%E3%81%AA%E3%83%84%E3%83%BC%E3%83%AB-%E3%82%B5%E3%83%96%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB

**Comment by ken3ypa** [comment]
https://qiita.com/TakahiRoyte/items/b7c4d1581df1a17a93fb

**Comment by kumewata** [comment]
[NetlifyはGitHubなどからデプロイできる静的Webホスティングサービス](https://tech.qookie.jp/posts/info-netlify-static-web-deploy/)

**Comment by ken3ypa** [comment]
「ちなみに発音は “post-gres-cue-ell” で、よろしくおねがいします」

**Comment by kumewata** [comment]
MySQL vs PostgreSQL
https://soudai.hatenablog.com/entry/2017/05/27/173055

**Comment by kumewata** [comment]
SQLパフォーマンス詳解
https://use-the-index-luke.com/ja

**Comment by kumewata** [comment]
Docker/Kubernetes 実践コンテナ開発入門 出版に寄せて
https://blog.stormcat.io/post/publish-docker-book/

Docker/Kubernetes 実践コンテナ開発入門
https://www.amazon.co.jp/dp/4297100339/

**Comment by ken3ypa** [comment]
————お—————わ—————り—————❤️———
1.5.1 Herokuのセットアップまで
———————————————————————————
