### ISSUE TITLE
第132回　ゆうし　たけうち　あめざわ　そめや

### ISSUE THREAD

**Issue by RyosukeSomeya** [yochiyochirb/meetups#1423]

**Comment by yk-ky** [comment]
よろしくお願いします！

**Comment by RyosukeSomeya** [comment]
よろしくおねがいします！

**Comment by ryotatake** [comment]
よろしくお願い致します！

**Comment by hideame** [comment]
よろしくお願いします。

**Comment by hideame** [comment]
デプロイとは
https://www.weblio.jp/content/%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4

**Comment by hideame** [comment]
Rubyの他にOSコマンドも覚えなきゃいけない人の話し

**Comment by hideame** [comment]
$ heroku --version
heroku/7.9.3 linux-x64 node-v10.9.0

**Comment by hideame** [comment]
HerokuでSSH公開鍵(publickey)の登録
heroku keys:add

**Comment by hideame** [comment]
上限に達しちゃいました。。
$ heroku create
Creating app... !
 ▸    You've reached the limit of 5 apps for unverified accounts. Delete some apps or add a credit card to
 ▸    verify your account.

**Comment by hideame** [comment]
これで消せるらしい
$ heroku apps:destroy --app アプリ名

**Comment by ryotatake** [comment]
bundlerとは
https://www.sejuku.net/blog/19426

**Comment by hideame** [comment]
heroku apps:infoでアプリ名を確認

**Comment by ryotatake** [comment]
> 例えばAというgemがあって、Aを使うにはBというgemを使う必要がある、そのgemを使うにはCというgemを….
となっている時、AはBに依存しており、BはCに依存しているということになります。
>
> そうなった時、一つ一つのgemをインストールするのって面倒ですよね？
>
> しかし、bundlerを使えば、依存関係のあるgemを一括でインストールしてくれます！

**Comment by hideame** [comment]
heroku apps でアプリの一覧表示

**Comment by hideame** [comment]
どれを消したらいいのかわからない。。

**Comment by RyosukeSomeya** [comment]
bundllerについて

https://qiita.com/lasershow/items/1a048d03ddaaba98171e

**Comment by hideame** [comment]
app名をきちんと付ける必要あるかも

**Comment by hideame** [comment]
1.5.3まで終了
