### ISSUE TITLE
第133回 あだるとチーム ゆかお みなみや わかすぎ

### ISSUE THREAD

**Issue by 5t111111** [yochiyochirb/meetups#1424]
🥇

**Comment by 5t111111** [comment]
「1.5.4 Herokuコマンド」から

**Comment by yuki3738** [comment]
☔️

**Comment by 5t111111** [comment]
「Listing Users」って出てない

**Comment by yuki3738** [comment]
ゆかおの思ひ出 「super agile struts」
http://sastruts.seasar.org/tutorial.html

**Comment by yucao24hours** [comment]
https://weblog.rubyonrails.org/2012/2/26/edge-rails-patch-is-the-new-primary-http-method-for-updates/

**Comment by yuki3738** [comment]
ブラウザのjsを無効にするとdeleteできなくなる 👀

**Comment by yucao24hours** [comment]
>ブラウザのjsを無効にするとdeleteできなくなる 👀

https://qiita.com/y-temp4/items/2d50feb3ff0d65acdf67

**Comment by yucao24hours** [comment]
`DELETE` は JS で、 `PATCH` は HTML の `hidden` 属性を使って実現されてる。

**Comment by yuki3738** [comment]
## Rails Tutorial Rails 4.0 版
![mvc_detailed](https://user-images.githubusercontent.com/6305192/45296646-a45d2380-b53d-11e8-90eb-81f40a75b812.png)

↓

## Rails Tutorial Rails 5.1 版

![mvc_detailed 1](https://user-images.githubusercontent.com/6305192/45296669-b9d24d80-b53d-11e8-8f49-acd4e44cad3e.png)

**Comment by yuki3738** [comment]
🤔 

> いくつかの文献では「ビューは (ApacheやNginxなどのWebサーバーを経由して) ブラウザにHTMLを直接返す」と説明しています。著者は、Railsの実際の実装とは無関係に、コントローラを軸にして情報の流れを捉えると分かりやすいと考えています。つまりビュー単体を切り離して理解しようとするのではなく、「情報の流れの中心にコントローラというハブがある」と考えると良いでしょう。

**Comment by yucao24hours** [comment]
"ビューテンプレートで作られた HTML がコントローラに返される" っていう意識をもって開発したことがなかったけど、本当にそうなっているのだろうか？
以下を見ると、この著者が「そう考えたほうがわかりやすいよ」と言っているだけのようにもみえる。

https://railstutorial.jp/chapters/toy_app?version=5.1#cha-2_footnote-3

**Comment by yuki3738** [comment]
> MVC2モデルとMVCモデルの違い

http://forza.cocolog-nifty.com/blog/2014/07/mvc2mvc-ffd9.html

**Comment by yucao24hours** [comment]
リスト 2.6 https://railstutorial.jp/chapters/toy_app?version=5.1#code-rails_routes_root_route までよんだ
