### ISSUE TITLE
第133回 ドバッティ, オバマ, チナツ

### ISSUE THREAD

**Issue by ckanayama** [yochiyochirb/meetups#1426]

**Comment by dobatty** [comment]
よろしくお願いします:)

**Comment by ckanayama** [comment]
よろしくお願いします！

**Comment by ckanayama** [comment]
> heroku open

したら

> Manually visit https://polar-forest-39693.herokuapp.com/ in your browser.

**Comment by dobatty** [comment]
試しに個人開発していたheroku appでlogsみたら、redis関連のlogがいっぱい出てきた

**Comment by ckanayama** [comment]
>ランダムなサブドメイン名を設定し、この章の冒頭で説明したアプリケーションのセキュリティを実装

**Comment by ckanayama** [comment]
コマンドラインコマンド
コマンドラインのコマンド

**Comment by ckanayama** [comment]
scaffold　=  足場

**Comment by dobatty** [comment]
scaffoldはRailsアプリケーションの概要を素早くつかむには最適、、と。

**Comment by ckanayama** [comment]
```
[!] There was an error parsing `Gemfile`: Undefined local variable or method `ource' for Gemfile. Bundler cannot continue.

 #  from /home/ec2-user/environment/toy_app/Gemfile:1
 #  -------------------------------------------
 >  ource 'https://rubygems.org'
 #  
 #  -------------------------------------------
```

**Comment by ckanayama** [comment]
source が　ource になっていた...

**Comment by ckanayama** [comment]
https://about.gitlab.com/

**Comment by PEPSINEX** [comment]
Bitbucket作成してませんでした。作成します。

**Comment by ckanayama** [comment]
ここで言ってる
データモデルは概念のお話でmodelとは別の話と思われ
https://ja.wikipedia.org/wiki/%E3%83%87%E3%83%BC%E3%82%BF%E3%83%A2%E3%83%87%E3%83%AB

**Comment by dobatty** [comment]
![638px-data_modeling_context svg](https://user-images.githubusercontent.com/3538315/45296975-c1462680-b53e-11e8-9c88-fe65afb55268.png)

**Comment by ckanayama** [comment]
ユーザー用のデータモデル
usersデータモデル
Userモデル

**Comment by ckanayama** [comment]
>if user.errors.any?

のところでエラーの表示出し分けている

**Comment by ckanayama** [comment]
どうやったら失敗できるのか...

**Comment by dobatty** [comment]
「2.2.2 MVCの挙動」の前の演習まで

**Comment by dobatty** [comment]
https://railstutorial.jp/chapters/toy_app?version=5.1#sec-mvc_in_action

**Comment by ckanayama** [comment]
サブドメインをランダムにするセキュリティ対策の話

ガチガチのセキュリティにしたい時にそういう技を使うことがある
- 権限のある操作ができる画面
- パスをかけられない時
とか場面によっては有効に使える
