### ISSUE TITLE
第１３３回　だて　しげみつ　POPMAC 　らいむ

### ISSUE THREAD

**Issue by ghost** [yochiyochirb/meetups#1427]

**Comment by shogoshigemitsu** [comment]
宜しくお願いします！

**Comment by popmac** [comment]
よろしくお願いします！

**Comment by lime1024** [comment]
オネガイシマス！

**Comment by ghost** [comment]
よろしくお願いします！

**Comment by shogoshigemitsu** [comment]
Herokuのアドレス名 =  アプリケーション名ですか？

**Comment by shogoshigemitsu** [comment]
サブドメインとカスタムドメインの違いはなんですか？

**Comment by shogoshigemitsu** [comment]
サブドメインは変えることが可能。ただし、誰かが使用しているサブドメイン名は取れない

**Comment by shogoshigemitsu** [comment]
カスタムドメイン = 独自ドメイン

**Comment by shogoshigemitsu** [comment]
バーチャルホストとは、１つのサーバで複数のドメインを運用する技術です。 サーバの代表となるドメインが実ホスト、それ以外がバーチャルホストです。

**Comment by shogoshigemitsu** [comment]
Herokuアプリケーション名はHerokuコマンドで変更可能である

herokuアプリのディレクトリ内で変更する場合

$ heroku rename 新しい名前
herokuアプリのディレクトリ外で変更する場合

$ heroku rename 新しい名前 --app 古い名前

**Comment by lime1024** [comment]
vim で盛り上がっています

**Comment by lime1024** [comment]
> この章の冒頭で説明したアプリケーションのセキュリティを実装してみる方法もあります。

冒頭のセキュリティ is 何

**Comment by popmac** [comment]
`irb` と `pry` の違いとは？

Rubyistよ、irbを捨ててPryを使おう - TIM Labs
http://labs.timedia.co.jp/2011/12/rubyist-should-use-pry.html

今までRubyの挙動を確認する時は `irb` を使っていた...

**Comment by lime1024** [comment]
「何はともあれman」

**Comment by ghost** [comment]
プログラミング初心者歓迎！「エラーが出ました。どうすればいいですか？」から卒業するための基本と極意（解説動画付き）
https://qiita.com/jnchito/items/056325421b7e36f02335

**Comment by popmac** [comment]
伊藤さんのYouTube動画は「こういう風に考えてコード書くのか」みたいな発見があって参考になります(朝ごはんの時に見たりする)
https://www.youtube.com/channel/UCekUxQPwLf-YCxbGtqeEmxg

**Comment by popmac** [comment]
**1.6.1 本章のまとめ**

まで読みました

**Comment by yucao24hours** [comment]
何はともあれマン
