### ISSUE TITLE
第134回 けん　すみかつ　ドバティ

### ISSUE THREAD

**Issue by ken3ypa** [yochiyochirb/meetups#1428]

**Comment by dobatty** [comment]
よろしくお願いします:)

**Comment by AiSumikatsu** [comment]
おねがいします！

**Comment by ken3ypa** [comment]
よろしくお願いします！

**Comment by ken3ypa** [comment]
![image](https://user-images.githubusercontent.com/28388130/46285952-4958a280-c5b8-11e8-9fb0-1e9fdba6fb11.png)

1.2　こんなことが書いてました

**Comment by ken3ypa** [comment]
RESTfulアーキテクチャの説明
https://qiita.com/NagaokaKenichi/items/0647c30ef596cedf4bf2

**Comment by ken3ypa** [comment]
### アドレス可能性(Addressability)
提供する情報がURIを通して表現できること。全ての情報はURIで表現される一意なアドレスを持っていること。

### ステートレス性(Stateless)
HTTPをベースにしたステートレスなクライアント/サーバプロトコルであること。セッション等の状態管理はせず、やり取りされる情報はそれ自体で完結して解釈できること。

### 接続性(Connectability)
情報の内部に、別の情報や(その情報の別の)状態へのリンクを含めることができること。

### 統一インターフェース(Uniform Interface)
情報の操作(取得、作成、更新、削除)は全てHTTPメソッド(GET、POST、PUT、DELETE)を利用すること。

**Comment by dobatty** [comment]
RESTとは、FieldingのRESTアーキテクチャスタイルの原則に合わせたWebサービスシステム。
https://ja.wikipedia.org/wiki/Representational_State_Transfer

**Comment by dobatty** [comment]
アーキテクチャスタイルとは複数のアーキテクチャに共通する性質
https://www.masalog.site/entry/2017/04/24/211354

**Comment by dobatty** [comment]
アーキテクチャとは、情報システムの設計方法、設計思想、およびその設計思想に基づいて構築されたシステムの構造などのことである。

**Comment by dobatty** [comment]
フィールディング活動とは
情報関連領域において、お客さまの活躍現場で、お客さまの快適運用と最適活用を実現すると共に、お客さまのニーズを先取りして様々なサービスを創出し、提供することです。
https://www.fielding.co.jp/info/rinen.html

→fieldingは人の名前

**Comment by dobatty** [comment]
fieldingとは、、、
https://en.wikipedia.org/wiki/Roy_Fielding

**Comment by dobatty** [comment]
例えば住所録の例では、住所は複数の名前と関連がある場合があります。住所のエンティティと名前のエンティティとの関係の接続性は、1 対多 (1:n) です。
https://www.ibm.com/support/knowledgecenter/ja/SSGU8G_12.1.0/com.ibm.ddi.doc/ids_ddi_168.htm

**Comment by dobatty** [comment]
接続性とは、エンティティのインスタンスの数を意味します。エンティティのインスタンスは、エンティティの特定のオカレンスです。以下の図に示すように、接続性には 1 対 1 (1:1)、1 対多 (1:n)、多対多 (m:n) の 3 つのタイプがあります。

**Comment by dobatty** [comment]
リソースの中には、指定されたリソースと関連をもつ他のリソースへのハイパーメディアリンク(URI)を含める。
ROAでは、リソース状態の表現の中に、他のリソースへのハイパーメディアリンクを含めることを「接続性」と呼んでいる。
これは、関連をもつリソース同士が相互にリンクを保持し、そのリンクをたどる事で関連する全てのリソースにアクセスできる状態にしておく事を意味している。
https://terasolunaorg.github.io/guideline/1.0.1.RELEASE/ja/ArchitectureInDetail/REST.html

**Comment by dobatty** [comment]
![restconnectivity](https://user-images.githubusercontent.com/3538315/46286711-1bc12880-c5bb-11e8-97bf-364e8c1fb4fd.png)

**Comment by ken3ypa** [comment]
インターフェース、プロトコルで仕切られた境界、ぐらいの意味？

**Comment by ken3ypa** [comment]
rails -v　打って入ってたらnew

**Comment by AiSumikatsu** [comment]
mbp:~ ai$  rails _5.1.6_ new toy_app
/Users/ai/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem railties (= 5.1.6) (Gem::GemNotFoundException)
	from /Users/ai/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
	from /Users/ai/.rbenv/versions/2.4.2/bin/rails:23:in `<main>'
m

**Comment by ken3ypa** [comment]
バージョン古かった！

**Comment by ken3ypa** [comment]
バージョン大事だ‥

**Comment by dobatty** [comment]
**_group :development doのgemについて_**

web-consoleとは、
ブラウザ上からconsoleを操作することができるデバッグ用のライブラリです。http://localhost:3000/consoleでコンソールが立ち上がります。また、ViewやControllerでコンソールメソッドを呼び出すことでコンソールを立ち上げることもできます。

https://qiita.com/kkenya/items/e9eba0021b1cf5efca2b

**Comment by dobatty** [comment]
listenとは、
ファイルの変更を**検知してそれをフックに**何か処理ができるgemとのこと
https://suin.io/536

**Comment by dobatty** [comment]
spring-watcher-listenとは、
springのファイルシステムの変更検知方法をpollingからlistenに変更してくれるgem。
https://suin.io/536

ちなみに、pollingとは，SNMPやICMP（Ping）を使ってネットワークの検出や監視を**周期的**に行うことです。
http://itdoc.hitachi.co.jp/manuals/3021/30213A7100/NNMK0051.HTM

**Comment by dobatty** [comment]
springとは、
Railsのアプリケーションプリローダで、テストやrakeタスクの起動を高速化してくれる
https://suin.io/536

**Comment by ken3ypa** [comment]
|gem名|機能|
| --- | --- |
|gem 'rails',        '5.1.6'|railsの基本機能を提供|
|gem 'puma',         '3.9.1'|webサーバ|
|gem 'sass-rails',   '5.0.6'|sassをRailsで使えるようにする|
|gem 'uglifier',     '3.2.0'|UglifyJS2 という JavaScript のコード軽量化ライブラリを、Ruby で簡単に使えるようにした gem|
|gem 'coffee-rails', '4.2.2'|coffeeスクリプトをrailsで使えるようにする|
|gem 'jquery-rails', '4.3.1'|RailsでjQueryを使えるようにする|
|gem 'turbolinks',   '5.0.1'|ページ遷移をAjaxに置き換え、JavaScriptやCSSのパースを省略することで高速化するgem|
|gem 'jbuilder',     '2.7.0'|入力するとJSONデータを返してくれる|
|sdoc:| RDocコメントからHTMLのAPIドキュメントを作ってくれる|

**Comment by ken3ypa** [comment]
markdown 記法で検索ゥ！

**Comment by ken3ypa** [comment]
```
|||
| --- | --- |
|||
```

**Comment by ken3ypa** [comment]
|a|a|
| --- | --- |
|a|a|

**Comment by ken3ypa** [comment]
|||
| --- | --- |
|||
|||

**Comment by dobatty** [comment]
| gem名 | 機能（group :development doのgemについて） | 
|:-----------|------------:|
| web-console | ブラウザ上からconsoleを操作することができるデバッグ用のライブラリ。http://localhost:3000/consoleでコンソールが立ち上がります。また、ViewやControllerでコンソールメソッドを呼び出すことでコンソールを立ち上がる。 |
|listen | ファイルの変更を**検知してそれをフックに何か処理**ができる |
|spring | Railsのアプリケーションプリローダで、テストやrakeタスクの起動を高速化 |
|spring-watcher-listen | springのファイルシステムの変更検知方法をpollingからlistenに変更するgem。pollingとはSNMPやICMP（Ping）を使ってネットワークの検出や監視を**周期的に**行うこと |

**Comment by ken3ypa** [comment]
pollingとは：周期的に実行してくれる
listenとは：反応があったら即時反応してくれる

**Comment by AiSumikatsu** [comment]
|gem 'sqlite3', '1.3.13|sqlite(データベース)をつかえるようにする|
| --- | --- |
| gem 'byebug',  '9.0.6', platform: :mri|rubyで使えるデバッガ（バグを見つけてくれる）|

**Comment by ken3ypa** [comment]
spring + listen　を繋げてるのがspring watcher listen?

**Comment by ken3ypa** [comment]
![image](https://user-images.githubusercontent.com/28388130/46288003-5fb62c80-c5bf-11e8-83c4-b69bbe299406.png)

**Comment by ken3ypa** [comment]
パース　＝　解析

**Comment by ken3ypa** [comment]
・Sass「Syntactically Awesome StyleSheet」
Syntactically　＝　構文的に
Awesome　＝　 イケてる
StyleSheet　＝　スタイルシート

**Comment by dobatty** [comment]
tzinfo-dataとは、タイムゾーンを扱うライブラリです。WindowsのRuby64bit版ではよくこれで躓きます。
https://qiita.com/kkenya/items/e9eba0021b1cf5efca2b

**Comment by ken3ypa** [comment]
https://github.com/rails/rails/pull/27717
Windows対応してるらしい

**Comment by ken3ypa** [comment]
pollingとは
http://e-words.jp/w/%E3%83%9D%E3%83%BC%E3%83%AA%E3%83%B3%E3%82%B0.html

**Comment by dobatty** [comment]
**今日やったこと**
①RESTとは
②gem何が入っているか
③マークダウンの書き方

**Comment by ken3ypa** [comment]
---
## 2.1 アプリケーションの計画まで
---

**Comment by kumewata** [comment]
昨日見つけた便利ツール↓
HTML上で簡単にMarkdownの表を作れるツール
https://markdowntable.haramishio.xyz/

**Comment by dobatty** [comment]
Ruby MRIとは、まつもとゆきひろによって開発されたRubyのリファレンス実装。
https://ja.wikipedia.org/wiki/Ruby_MRI
