### ISSUE TITLE
第134回　たけうち　ゆうし　つじはし

### ISSUE THREAD

**Issue by yk-ky** [yochiyochirb/meetups#1429]
よろしくお願いします！

**Comment by ryotatake** [comment]
よろしくお願いします！

**Comment by KohichiTsujihashi** [comment]
宜しくお願いします！

**Comment by yk-ky** [comment]
git add のあとには git status で確認。基本ですね、、

**Comment by ryotatake** [comment]
ブランチについて

**Comment by ryotatake** [comment]
開発を進めるときは、masterブランチに影響を与えないように新しいブランチを作成して開発を進める。

新しいブランチで開発が進んだら、masterブランチにマージする。

**Comment by ryotatake** [comment]
`git remote -v`で出てくる`fetch`と`push`って？

```
ec2-user:~/environment/toy_app (master) $ git remote -v
origin  git@github.com:ryotatake/toy_app_for_yochiyochirb.git (fetch)
origin  git@github.com:ryotatake/toy_app_for_yochiyochirb.git (push)
```

**Comment by ryotatake** [comment]
`git remote -v`について

> 今までにどのリモートサーバーを設定したのかを知るには git remote コマンドを実行します。これは、今までに設定したリモートハンドルの名前を一覧表示します。リポジトリをクローンしたのなら、少なくとも origin という名前が見えるはずです。これは、クローン元のサーバーに対して Git がデフォルトでつける名前です。

> -v を指定すると、その名前に対応する URL を表示します。

[Pro Git](https://git-scm.com/book/ja/v1/Git-%E3%81%AE%E5%9F%BA%E6%9C%AC-%E3%83%AA%E3%83%A2%E3%83%BC%E3%83%88%E3%81%A7%E3%81%AE%E4%BD%9C%E6%A5%AD)

**Comment by ryotatake** [comment]
`git add`と`git commit -a`の違い

一度`add`されたファイルは、以降`git commit -a`だけでコミットできる。
一度も`add`されていないファイルは、`git commit -a`だけではコミットできず、`git add`→`git commit`としないといけない。

**Comment by yk-ky** [comment]
Git がまだしっくりきていないです。。add とかcommit とか、、
が、今回また少しレベルアップしました。。助かります。

**Comment by yk-ky** [comment]
ローカルでpush するときは要注意ですね。

**Comment by ryotatake** [comment]
`git push`を取り消したいとき

http://www-creators.com/archives/2020

**Comment by ryotatake** [comment]
`rails generate scaffold User name:string email:string`
なぜUserと単数形なのか

["rails generate scaffold modelname"でモデル名を単数にする理由について](https://github.com/yochiyochirb/meetups/issues/94)

**Comment by yk-ky** [comment]
2.2 Usersリソースまで終了
