### ISSUE TITLE
134回　ごうだ　くめ　ウーロン

### ISSUE THREAD

**Issue by Keisukegdk** [yochiyochirb/meetups#1430]

**Comment by Keisukegdk** [comment]
よろしくお願いします！

**Comment by kumewata** [comment]
よろしくお願いします！

**Comment by ghost** [comment]
よろしくお願いします!

**Comment by kumewata** [comment]
scaffoldジェネレータ
＞MVC一通り作ってくれる

**Comment by kumewata** [comment]
RESTアーキテクチャ？？

**Comment by Keisukegdk** [comment]
RESTアーキテクチャ
routingとかの書き方でコントロールできたよな、、、？

**Comment by ghost** [comment]
マイクロポスト?

**Comment by kumewata** [comment]
とらLab
https://news.toranoana.jp/64239

**Comment by Keisukegdk** [comment]
マイクロポストから成り立っています？
What マイクロポスト？

**Comment by kumewata** [comment]
小さい規模のポスト？
＞140文字

**Comment by Keisukegdk** [comment]
Bitbucketとは？

**Comment by Keisukegdk** [comment]
Bitbucket：基本的に５人までなら、非公開にできる。

**Comment by ghost** [comment]
僕はGitHubにあげてました。

**Comment by kumewata** [comment]
githubとbitbucketであまりコマンド変わらない

bitbucket
```
git remote add origin git@bitbucket.org:<username>/toy_app.git
git push -u origin --all
```
github
```
git remote add origin git@github.com:<username>/toy_app.git
git push -u origin --all
```

**Comment by Keisukegdk** [comment]
rails generate scaffold User name:string email:string

**Comment by kumewata** [comment]
scaffoldコマンドの引数はリソース名を```単数形```にしたもの

**Comment by kumewata** [comment]
なんでRakeコマンドからRailsコマンドに変わったんだろう？

**Comment by kumewata** [comment]
Makeで説明してあるけどMakeがわからない。。

**Comment by kumewata** [comment]
Rails4から5にかけて結構構成が変わったのかな？？
```
Rails 4以前のアプリケーションでは、
rakeコマンドのバージョンをGemfileで定義しているため、
Bundlerのbundler execコマンドを通して実行する必要があります。
```

**Comment by Keisukegdk** [comment]
execを使う意味は、、、、Makeを追いかけないといけないのか？？

**Comment by kumewata** [comment]
Makefileを手順書として、Makeコマンドで処理を走らせるって感じかな

**Comment by kumewata** [comment]
Rails guide / strong parameter
https://railsguides.jp/action_controller_overview.html#strong-parameters

```
strong parametersを使用することで、
Action Controllerのホワイトリストに載っていないパラメータが
Active Modelのマスアサインメントに利用されることを禁止できます
```

**Comment by Keisukegdk** [comment]
https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/railties/lib/rails/generators/rails/scaffold_controller/templates/controller.rb.tt

**Comment by Keisukegdk** [comment]
⬆️Successfully ...

**Comment by kumewata** [comment]
2.2.1の演習の途中まで

**Comment by kumewata** [comment]
@Keisukegdk @r-oolong 
輪読会の募集ページです
https://esa-pages.io/p/sharing/8771/posts/55/3003f203fea80a085604.html

**Comment by kumewata** [comment]
何故か今までrails5でも```rake routes```でルーティング一覧を確認していたけれど、
昨日```rails routes```でも同じことが出来ることを知った。
実は今はrakeコマンドとrailsコマンドが共存しているっぽい

[Rails guide / 5 ルーティングの調査とテスト](https://railsguides.jp/routing.html#%E3%83%AB%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E3%81%AE%E8%AA%BF%E6%9F%BB%E3%81%A8%E3%83%86%E3%82%B9%E3%83%88)

**Comment by ManabuSeki** [comment]
@kumewata 

こちらに載ってます
https://techracho.bpsinc.jp/hachi8833/2017_03_01/36329

https://railsguides.jp/5_0_release_notes.html
こちらにも記載がありました

[該当のPull Request](https://github.com/rails/rails/pull/22288)

**Comment by kumewata** [comment]
@ManabuSeki 
ありがとうございます！
```
同記事によると、rakeコマンドを好む開発者も多い中、
Railsコアチームはrakeでできるタスクをrailsでもできるようにする決定を下したとのことです。
もちろん従来どおりrakeコマンドで実行することもできますので、
rakeに慣れた開発者も戸惑わずに済みます。
```

そして親切設計！
```
そのためにRails 5ではRake Proxyが導入されました。
railsにないオプションが指定されるとこのRake Proxy経由で
コマンドをrakeに委譲するようになっています。

rails --helpを実行すると、従来rakeで実行できたオプションも続けて表示されます。
たぶんこれが一番ありがたいと思います。
```
