### ISSUE TITLE
第134回 みなみや 草野

### ISSUE THREAD

**Issue by yuki-kusano** [yochiyochirb/meetups#1431]

**Comment by yuki3738** [comment]
1章からやります！！

**Comment by yuki3738** [comment]
rubyのversion古いなんでや

**Comment by yuki3738** [comment]
gitignore の話した
https://qiita.com/y_minowa/items/e3d8513dc31c1b378e0d

**Comment by yuki3738** [comment]
Rack とは
https://qiita.com/k0kubun/items/248395f68164b52aec4a

**Comment by yuki3738** [comment]
> rubyのversion古いなんでや

AWSではないcloud9のRails tutorialじゃないworkspace (AWSではenvironment) を使ったからっぽい。

**Comment by yuki3738** [comment]
rails new した後のdirectory 構成を熟読した
