### ISSUE TITLE
第135回 やまくち、はと、ちなつ

### ISSUE THREAD

**Issue by ckanayama** [yochiyochirb/meetups#1432]

**Comment by hato810** [comment]
よろしくお願いしますー！

**Comment by ryamakuchi** [comment]
よろしくおねがいします!!

**Comment by ckanayama** [comment]
よろしくお願いします！

**Comment by ckanayama** [comment]
第2章 Toyアプリケーション
からします。

**Comment by ckanayama** [comment]
scaffold = 足場

**Comment by hato810** [comment]
RESTアーキテクチャてなに

**Comment by ckanayama** [comment]
http://karur4n.hatenablog.com/entry/read-webtechbook

**Comment by hato810** [comment]
REST：Webサービスの設計モデル

Representational State Transfer の略で、インターネット（Web）上でいろいろな情報や機能を結びつける方法、あるいは考え方のひとつ。

**Comment by ckanayama** [comment]
マイクロポスト
twitterみたいな短いメッセージを投稿できるものみたいな意味合い

**Comment by hato810** [comment]
投稿できる機能的な(?)

**Comment by ryamakuchi** [comment]
Railsチュートリアルで出てくる「マイクロポスト」とは、そういう機能の名前として使っている?
Twitterみたいな機能のこと

**Comment by ckanayama** [comment]
gemfileのproductionに1つだけgemに入れてあったので何かと思ったら
PostgreSQLだった
https://rubygems.org/gems/pg/versions/0.18.4

**Comment by hato810** [comment]
`$rails _5.1.6_ new toy_app`
のrailsはそれ自身がgem　へえ

**Comment by ckanayama** [comment]
`sass-rails`だけ優しさを感じる

**Comment by ryamakuchi** [comment]
`Webアプリケーションを作る際、アプリケーションの構造を表すためのデータモデルを最初に作成しておくのが普通です。`

**Comment by ckanayama** [comment]
routesとroot
ルートルーティング

**Comment by ryamakuchi** [comment]
`protect_from_forgery with: :exception`

 これはCSRF対策用に書かれている

https://www.transnet.ne.jp/2016/10/26/%E3%80%8Cruby-on-rails%E3%81%AEcsrf%E5%AF%BE%E7%AD%96colnd/

**Comment by ckanayama** [comment]
routes でリソースとかルーティングを設定する
rootはルートルーティング（アプリケーションを起動した時に表示されるルート）

**Comment by ryamakuchi** [comment]
Modelが英語の単数形でテーブル名称が複数形になる

いつまでたっても覚えられない

**Comment by hato810** [comment]
2.1.1 ユーザーのモデル設計

**Comment by hato810** [comment]
こんな感じでデータ持つよ〜って話

**Comment by hato810** [comment]
2.1.2 マイクロポストのモデル設計

**Comment by hato810** [comment]
理解

**Comment by hato810** [comment]
マイクロポストのモデル設計のidは、ユーザーのidじゃなくて、投稿に対するid
ユーザーと投稿（microposts）それぞれでデータを持つ

**Comment by hato810** [comment]
2.2 Usersリソース

**Comment by ryamakuchi** [comment]
![ds3zfv-vmae8tij 1](https://user-images.githubusercontent.com/35450730/46950689-821c6f80-d0c0-11e8-81bf-ef6d9621006b.jpg)

**Comment by ckanayama** [comment]
リソース ≒ URI

**Comment by ckanayama** [comment]
主キーという概念がよくわからない

**Comment by hato810** [comment]
rake……

**Comment by hato810** [comment]
主キー：被らないID、TwitterのアカウントIDみたいな

**Comment by ckanayama** [comment]
>idパラメータはRailsによって自動的に主キーとしてデータベースに追加されるため

→ idというカラムにしておけば、Railsが主キーとしてデータベースに追加して（idを作って）くれる

**Comment by ryamakuchi** [comment]
migrateの仕組みがわからない
![cfkm5yguiaeb7yx](https://user-images.githubusercontent.com/35450730/46950932-551c8c80-d0c1-11e8-9448-b71e3de1700c.jpg)

**Comment by ckanayama** [comment]
うーん・・・スキーマファイルの役割？
https://qiita.com/k0kubun/items/491a9d9f2745335566e3

**Comment by ryamakuchi** [comment]
## migrate がしてくれていること
* DBの中の情報を更新してくれる(カラム、属性など)。SQLのALTER みたいなもの?
* schema.rb を更新してくれる

## 疑問
* schema.rb がやってくれることって何?

**Comment by ckanayama** [comment]
2.2 の「コラム 2.1. Rake」の手前まで読みました。

**Comment by ckanayama** [comment]
developmentがsqlite3でproductionがPostgreSQLにしてあるのはなぜか？

→ HerokuはPostgreSQLだけれども、PostgreSQLの環境設定は結構面倒だったりするからチュートリアルでは分けたのかも

**Comment by hato810** [comment]
schema.rb #とは
現在のDBの状態がかいてある（スナップショット的な）

**Comment by ckanayama** [comment]
DBが複数系でModelが単数系なのがよくわからない件

→DB
テーブル内に複数のデータを持っているので複数系
→Model
DBに接続するための最小の単位なので単数系

と考えると自然と考えられそう。
