### ISSUE TITLE
第135回 がく みなみや ゆかお

### ISSUE THREAD

**Issue by ManabuSeki** [yochiyochirb/meetups#1433]

**Comment by ManabuSeki** [comment]
hi 😄

**Comment by yuki3738** [comment]
💪

**Comment by ManabuSeki** [comment]
2.2 Usersリソースから

**Comment by yucao24hours** [comment]
https://github.com/yochiyochirb/meetups/issues/124

**Comment by yucao24hours** [comment]
https://github.com/yochiyochirb/meetups/issues/251

**Comment by yuki3738** [comment]
[演習1](https://railstutorial.jp/chapters/toy_app?version=5.1#sec-exercises_mvc_in_action)
![img_3102](https://user-images.githubusercontent.com/6305192/46950026-47193c80-d0be-11e8-85db-17a225258afe.JPG)

**Comment by yuki3738** [comment]
演習2
これじゃろ？
`@user = User.find(params[:id])`

**Comment by yuki3738** [comment]
演習3
`/toy_app/app/views/users/edit.html.erb`
と
`/toy_app/app/views/users/_form.html.erb`

**Comment by yuki3738** [comment]
> 理解が困難。 scaffoldのコードを理解できるぐらいなら、そもそも本書を読む必要はないでしょう。

おぅよ。

**Comment by yuki3738** [comment]
ほげほげ〜！！！！！

**Comment by yuki3738** [comment]
[演習1](https://railstutorial.jp/chapters/toy_app?version=5.1#sec-exercises_a_micropost_microtour)
`<p id="notice">Micropost was successfully created.</p>`

**Comment by yuki3738** [comment]
上記まで↑

**Comment by ManabuSeki** [comment]
[演習1](https://railstutorial.jp/chapters/toy_app?version=5.1#sec-exercises_a_micropost_microtour)

toy_app/app/controllers/microposts_controller.rb 29行目から
```ruby
respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
```

toy_app/app/views/microposts/show.html.erb 1行目
```erb
<p id="notice"><%= notice %></p>
```
createでnoticeに渡した文字列がviewの`<%= notice %>`ERB(eRuby)で文字列を出力している
