### ISSUE TITLE
第137回 なかにし, やまくち, くめ, たしろ

### ISSUE THREAD

**Issue by tashirosota** [yochiyochirb/meetups#1435]

**Comment by ryamakuchi** [comment]
👍

**Comment by kumewata** [comment]
よろしくお願いします！

**Comment by naknshkk** [comment]
よろしくお願いします！

**Comment by kumewata** [comment]
ライオンの子がいた！

**Comment by naknshkk** [comment]
scaffoldてよくわからないまま進んじゃったから今回助かる

**Comment by tashirosota** [comment]
これめっちゃ使います
http://maeharin.hatenablog.com/entry/20130212/rails_generate

**Comment by kumewata** [comment]
Rails のアプリケーションテンプレート
https://railsguides.jp/rails_application_templates.html

**Comment by kumewata** [comment]
[Rails 5.1] ‘form_with’ APIドキュメント完全翻訳
https://techracho.bpsinc.jp/hachi8833/2017_05_01/39502

**Comment by tashirosota** [comment]
[form_with, form_for, form_tag]
https://qiita.com/hmmrjn/items/24f3b8eade206ace17e2

**Comment by ryamakuchi** [comment]
たくさん知見がたまる

**Comment by ryamakuchi** [comment]
flash
https://kiyotakakubo.hatenablog.com/entry/20110913/1315882887

**Comment by kumewata** [comment]
flash奥が深い
now, keep

**Comment by kumewata** [comment]
simple form便利そう！
https://github.com/plataformatec/simple_form

**Comment by tashirosota** [comment]
おすすめのgem
https://qiita.com/Inp/items/4f72918c2fba0d3a8809

**Comment by kumewata** [comment]
gemの作り方の記事
https://twitter.com/migrateur_k/status/1056374413442994177

**Comment by naknshkk** [comment]
これははいはい.rbを企画する時が来たか

**Comment by naknshkk** [comment]
勉強になる

**Comment by kumewata** [comment]
輪読会でまとめたpostでdeleteを実現する話です↓
https://esa-pages.io/p/sharing/8771/posts/50/8102b64e0fb3ee2c2da5.html#7.9%20POST%E3%81%A6%E3%82%99PUT/DELETE%E3%82%92%E4%BB%A3%E7%94%A8%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95

**Comment by ryamakuchi** [comment]
http://d.hatena.ne.jp/tkuro/20130123/1358920686

**Comment by tashirosota** [comment]
htmlの世界でdata-hogeはdata属性扱いになる。

**Comment by kumewata** [comment]
gem / jquery-ujs
https://github.com/rails/jquery-ujs

**Comment by ryamakuchi** [comment]
```
https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/data-*
```
カスタムデータ属性

コピペしてね

**Comment by tashirosota** [comment]
[deleteに関しての経緯,議論]
http://jxck.hatenablog.com/entry/why-form-dosent-support-put-delete

**Comment by kumewata** [comment]
coffeescript...

<img width="659" alt="2018-10-29 21 23 30" src="https://user-images.githubusercontent.com/28887109/47649550-fbd45300-dbc0-11e8-9a0a-de0e666e859f.png">

**Comment by tashirosota** [comment]
https://qiita.com/chao____/items/565e55ba54621443ff59

**Comment by kumewata** [comment]
2.2.1の演習終わり！

**Comment by kumewata** [comment]
gem回の機運

**Comment by kumewata** [comment]
広く浅く入門できる本
[「プロになるためのWeb技術入門」 ――なぜ、あなたはWebシステムを開発できないのか](https://www.amazon.co.jp/%E3%80%8C%E3%83%97%E3%83%AD%E3%81%AB%E3%81%AA%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AEWeb%E6%8A%80%E8%A1%93%E5%85%A5%E9%96%80%E3%80%8D-%E2%80%95%E2%80%95%E3%81%AA%E3%81%9C%E3%80%81%E3%81%82%E3%81%AA%E3%81%9F%E3%81%AFWeb%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%82%92%E9%96%8B%E7%99%BA%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84%E3%81%AE%E3%81%8B-%E5%B0%8F%E6%A3%AE-%E8%A3%95%E4%BB%8B/dp/4774142352)
