### ISSUE TITLE
第137回　たのうえ　はと　ゆうし　もりの

### ISSUE THREAD

**Issue by takashimamorino** [yochiyochirb/meetups#1436]

**Comment by yk-ky** [comment]
よろしくお願いします！！！

**Comment by hato810** [comment]
もりのさんありがとうございます！
よろしくお願いしますー！

**Comment by ghost** [comment]
よろしくお願いします！

**Comment by hato810** [comment]
スタート！

## 2.2.1 ユーザーページを探検する

**Comment by yk-ky** [comment]
初心者のハードル、Gitって何？でお話ができる。。。親近感があります。。

**Comment by hato810** [comment]
わかります（わかります）

**Comment by hato810** [comment]
Usersリソース #とは

**Comment by takashimamorino** [comment]
https://qiita.com/kidach1/items/43e53811c12351915278

**Comment by hato810** [comment]
```
リソースとは
データモデルとwebインターフェイスが組み合わさったもの。

データモデルとは 現実世界のあるモノを分類/抽象化して落とし込んだカタマリ （より具体的にいえば（今回の文脈では）「RDBMSに則って設計されたデータ群」と同義）
```

RDBMS #とは
Relational DataBase Management System

**Comment by hato810** [comment]
リソース = webでアクセスできるデータ

**Comment by hato810** [comment]
Usersリソース = webでアクセスできるユーザーに関するデータ

**Comment by hato810** [comment]
> [Destroy] リンクをクリックするとユーザーが削除され、indexページのユーザーは1人だけになります (もしこのとおりにならない場合は、ブラウザのJavaScriptが有効になっているかどうかを確認してください。Railsでは、ユーザーを削除するリクエストを発行するときにJavaScriptを使っています。Railsでは、ユーザーを削除するリクエストを発行するときにJavaScriptを使っています)。

JavaScriptはどう使われているのか

**Comment by hato810** [comment]
.o0（Javaがそもそもわからないけども）

ヘルプ(1)

**Comment by takashimamorino** [comment]
https://ics.media/entry/11735

**Comment by kumewata** [comment]
輪読会でまとめたpostでdeleteを実現する話です↓
https://esa-pages.io/p/sharing/8771/posts/50/8102b64e0fb3ee2c2da5.html#7.9%20POST%E3%81%A6%E3%82%99PUT/DELETE%E3%82%92%E4%BB%A3%E7%94%A8%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95

**Comment by yucao24hours** [comment]
https://qiita.com/y-temp4/items/2d50feb3ff0d65acdf67

**Comment by hato810** [comment]
ゆかおさん、くめさんありがとうございます！

以下鳩メモ
```
<a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/users/1">Destroy</a>
の
data-method="delete"
について。
data-とつくものは特別なもの。htmlとjsをつなぐもの。データメソッド。データ属性。

htmlの世界にdeleteの機能はない。ので、jsさんがよしなにしてくれてる。

html「ユーザー1を消したいけどdeleteの機能ない。サーバーに伝わらないこの想い、JSなんとかして」
js 「data-method="delete"きた。deleteしてもらえるようなpostのかたちにしてサーバーになげるね」
ruby 「おっユーザー1消すで」
```
（あってます？？？）

**Comment by hato810** [comment]
### 演習
1. 消えた
2. 登録できた
3. 登録できた
4. User was successfully destroyed.

**Comment by yucao24hours** [comment]
@hato810 すみません！わたしが間違って口走ってたかもしれないですが、
>CSSとJSを

ではなくて

>HTML と JS を

です！失礼しました！

## 参考 URL
- https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/data-*
- https://developer.mozilla.org/ja/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by hato810** [comment]
あっ　ゆかおさん参考URLありがとうございます！！（私のメモミスかもです…）
メモ部分修正しました:pray:

**Comment by hato810** [comment]
2.2.1 ユーザーページを探検する　の終わりまでやりました！
次回、2.2.2 MVCの挙動からです！

**Comment by yk-ky** [comment]
上記の演習で作成したユーザーを削除してみてください。ユーザーを削除したとき、Railsはどんなメッセージを表示するでしょうか?
→<p id="notice">User was successfully destroyed.</p>
ですが、これはどこからきてるのでしょうか、、

UsersControllerに記述ありました。
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

**Comment by yk-ky** [comment]
"<p id="notice">User was successfully destroyed.</p>:"
わからないことだらけですね。
