### ISSUE TITLE
第138回 ゆかお みなみや がく

### ISSUE THREAD

**Issue by ManabuSeki** [yochiyochirb/meetups#1438]
次は2.3.4 継承の階層から

**Comment by yuki3738** [comment]
🌮

**Comment by yuki3738** [comment]
http://www.itsenka.com/contents/development/uml/class.html
<img width="575" alt="2018-11-19 20 44 11" src="https://user-images.githubusercontent.com/6305192/48705212-eab8b800-ec3b-11e8-9d72-a3c799a9a1d3.png">

**Comment by yucao24hours** [comment]
「あの黒いひし形とか白い矢印ってなんていうルールなんだっけ...」の回答
https://ja.wikipedia.org/wiki/%E3%82%AF%E3%83%A9%E3%82%B9%E5%9B%B3

**Comment by yucao24hours** [comment]
>Returns whether this class is an abstract class or not.
https://api.rubyonrails.org/classes/ActiveRecord/Inheritance/ClassMethods.html#method-i-abstract_class-3F

**Comment by yucao24hours** [comment]
```ruby
abstract_class = true
```

とはどこからやってきたのか？を掘り下げてみた
https://github.com/rails/rails/blob/4fe27cdc15b88fed5ae725a886b7e96202f649a8/activerecord/lib/active_record/inheritance.rb#L158

`autoload` されているのはここ
https://github.com/rails/rails/blob/4fe27cdc15b88fed5ae725a886b7e96202f649a8/activerecord/lib/active_record.rb#L47

**Comment by yuki3738** [comment]
https://github.com/rails/rails/commit/ceb33f84933639d3b61aac62e5e71fd087ab65ed

**Comment by yuki3738** [comment]
(∩´∀｀)∩ﾜｰｲ
<img width="508" alt="2018-11-19 21 28 56" src="https://user-images.githubusercontent.com/6305192/48707254-2b1b3480-ec42-11e8-8641-8b3310202f79.png">

**Comment by yucao24hours** [comment]
第2章おわり！次は第3章から
