### ISSUE TITLE
第138回 やまくち、りっきー、けん、はと、

### ISSUE THREAD

**Issue by hato810** [yochiyochirb/meetups#1439]

**Comment by ryamakuchi** [comment]
よろしくお願いします！

**Comment by hato810** [comment]
## 2.2.2 MVCの挙動
ここからはじまりますー！
よろしくお願いします！

**Comment by kenichi-sonoda** [comment]
よろしくお願いしますー！

**Comment by miyariki** [comment]
よろしくお願いします！！！

**Comment by miyariki** [comment]
おー！

**Comment by hato810** [comment]
Controller：ウエイターさん
View：お客さん
Model：料理つくる人さん

**Comment by ryamakuchi** [comment]
MVC の挙動ふわっと理解だったなーと思って、反省！

**Comment by ryamakuchi** [comment]
例えがうまくて感動！

**Comment by ryamakuchi** [comment]
MVVM についても語ってもらえる

https://qiita.com/mizchi/items/4d25bc26def1719d52e6

**Comment by ryamakuchi** [comment]
MVVM じゃなくて仮想 DOM についてのことだった。語ってもらえなかった。

**Comment by hato810** [comment]
パッチとプットの違い
パッチ：一部の変更
プット：全部の変更

**Comment by hato810** [comment]
>ユーザーからリクエストされたURLを、Usersリソースで使うコントローラのアクションに割り当てるためのコード

config/routes.rbの書き方のはなしぽい

**Comment by kenichi-sonoda** [comment]
それぞれアクセスしてみると一番最後のURLが変わっていました。

https://github.com/yochiyochirb/meetups/issues
https://github.com/yochiyochirb/meetups/pulls

もしrailsで書かれているとしたら、
これはおそらく/issues_controller.rbや、/pulls_controller.rbというcontrollerが用意されていて、
config/route.rbに以下のような記述がされているかなと思います。

```
  get 'issues', to: 'issues#index'
  get 'pulls', to: 'pulls#index'
```

**Comment by hato810** [comment]
人をダメにする言語 ruby

**Comment by miyariki** [comment]
人をダメにする言語

**Comment by ryamakuchi** [comment]
> https://developer.mozilla.org/ja/docs/Web/HTTP/Methods


HTTP リクエストメソッドいっぱいあった‥！

**Comment by miyariki** [comment]
railsすげえ（小並感）

**Comment by hato810** [comment]
https://github.com/yochiyochirb/meetups/issues/1436#issuecomment-433891650

**Comment by hato810** [comment]
>htmlの世界にdeleteの機能はない。ので、jsさんがよしなにしてくれてる。

>html「ユーザー1を消したいけどdeleteの機能ない。サーバーに伝わらないこの想い、JSなんとかして」
js 「data-method="delete"きた。deleteしてもらえるようなpostのかたちにしてサーバーになげるね」
ruby 「おっユーザー1消すで」

**Comment by hato810** [comment]
REpresentational State Transfer (REST)
日本語でok

やまくちさん「URLがいけてるもののほうがいいねって話」

**Comment by ryamakuchi** [comment]
*すごいREST*

**Comment by hato810** [comment]
RESTは概念

**Comment by ryamakuchi** [comment]
すごい REST であってる！

**Comment by kenichi-sonoda** [comment]
一般的にはRESTの考え方をWeb APIに適用したものをRESTful APIと呼んでいる。
http://e-words.jp/w/RESTful_API.html

**Comment by hato810** [comment]
RESTful = ~すごいREST~ RESTを適用させる

**Comment by ryamakuchi** [comment]
REST … そういうアーキテクチャ
RESTful … そういうアーキテクチャで設計されているアプリケーション

**Comment by miyariki** [comment]
RESTもRESTfulも、すごいREST

**Comment by hato810** [comment]
URLいい感じにするっていうフレームワーク

**Comment by hato810** [comment]
>@usersは「あっと ゆーざーず」と発音します

早くいって

**Comment by hato810** [comment]
Active Recordほどすごいやつはいない

**Comment by hato810** [comment]
Active Recordさんが、DBから欲しいデータを直感的に、よしなに持ってきてくれる

**Comment by ryamakuchi** [comment]
![図](https://github.com/ryamakuchi/rails-tutorial/blob/master/memo/images/618D1198F83F25F058242FC0E900C889.png)

**Comment by ryamakuchi** [comment]
https://github.com/ryamakuchi/rails-tutorial/blob/master/memo/MEMO.md#222-mvc%E3%81%AE%E6%8C%99%E5%8B%95

これでいけるか！？

**Comment by hato810** [comment]
次回、2.2.3 Usersリソースの欠点から！

**Comment by kenichi-sonoda** [comment]
RESTについてのスライド（俺たちも読んでみましょう 🙌 ）
https://www.slideshare.net/tkawa1/learning-rest-from-rails-style

**Comment by kenichi-sonoda** [comment]
active recordについて
https://railsguides.jp/active_record_querying.html
