### ISSUE TITLE
第138回 とみい　ゆうし　つじはし　もりの

### ISSUE THREAD

**Issue by takashimamorino** [yochiyochirb/meetups#1440]

**Comment by yk-ky** [comment]
ありがとうございます！

**Comment by KohichiTsujihashi** [comment]
宜しくお願いします！

**Comment by t10kiyotaka** [comment]
ありがとうございます！

**Comment by takashimamorino** [comment]
マッピング: 割り当て

**Comment by yk-ky** [comment]
HTTP メソッド、PUT と PATCH の違いをもっとくわしく知りたい 

https://github.com/yochiyochirb/meetups/issues/251

**Comment by takashimamorino** [comment]
PATCH: 一部更新

**Comment by yk-ky** [comment]
https://thinkit.co.jp/free/article/0609/8/4

**Comment by takashimamorino** [comment]
RESTと言われる設計原則のシステムをRESTful

**Comment by yk-ky** [comment]
RESTは設計の制約・原則のことのようですね。

RESTは主に以下の4つの原則から成り立っています。
Addressability：アドレスひとつで指定可能
Stateless：そのつど完結
Connectability：ハイパーメディアで参照可能
Uniform Interface：統一されたインターフェース

すべての情報がＵＲＬやＵＲＩで表現される一意なアドレスをもっている。
セッションなどの状態管理を行わず、やりとりされる情報はそれ自体で完結して解釈できる。
HTMLやXMLといった文書にリンクを含めることで、それだけで他のRESTリソースを参照できる。
情報の操作（取得、作成、更新、削除）は、すべてあらかじめ定義され、共有されたHTTPメソッド（GET、POST、PUT、DELETE）を利用する。

**Comment by yk-ky** [comment]
これはどうでしょう？？
https://www.slideshare.net/tkawa1/learning-rest-from-rails-style
スライドのなかによちよちの記載がありましたが、、

**Comment by yk-ky** [comment]
SOAPとREST
https://teratail.com/questions/34703
ややこしくなっただけでした、、、

**Comment by takashimamorino** [comment]
RESTにのっとてルートを定義することで、一貫性のあるURLを作成できる。

**Comment by takashimamorino** [comment]
2.2の部分にresourcesで作られるルーティングがまとめられている。
https://railsguides.jp/routing.html

**Comment by takashimamorino** [comment]
コラム2.2まで

**Comment by ManabuSeki** [comment]
RESTful API 入門
https://www.slideshare.net/keisuke69/restful-api-56227772
