### ISSUE TITLE
Test::Unit と RSpec の違いって？

### ISSUE THREAD

**Issue by katorie** [yochiyochirb/meetups#186]
RailsチュートリアルではRSpecを採用していますが、RailsではデフォルトでTest::Unitフレームワークが存在します。
チュートリアルがRSpecを採用しているのはなぜなのか…チュートリアルを進めていくとわかるのかもしれませんが、はじめにちょっと比較しておくと、理解が深まるのでは？と思いました。

- Test::Unit と RSpec の違い
- それぞれのいいところ・よくないところ

などが整理できるといいなと思います。

それから、
どっちも書いたことあるよ！みたいな話とか、現場でこんな話したよとか教えてもらえるとうれしいなぁなんて思っていますので、気軽な感じで書き込んでもらえると、とても参考になってうれしいです。

**Comment by yucao24hours** [comment]
#729 の方針にのっとり、現時点でアクティブでなさそうな issue についてはひとまず close させていただきました。
ただし、「今後これの話はいっさいしないで！」というわけではなく、あくまでも **今** ホットなものを open のステータスにしておきたいという私の希望からであって、他意はまったくありません。
私以外のどなたかが「これ必要！」と思った場合はぜひ遠慮なく reopen してくださいね :rose:
