### ISSUE TITLE
インスタンスメソッドとクラスメソッドはどう使い分けるべき？

### ISSUE THREAD

**Issue by odaillyjp** [yochiyochirb/meetups#584]
メソッドには、インスタンスオブジェクトに紐付けられる「インスタンスメソッド」と、クラス本体に紐付けられる「クラスメソッド」がある。（表現は正しいかな。）
使い方はわかったけど、どう使い分ければいいのか調べたい。

ついでに、モジュールに紐付ける「モジュール関数」との使い分けも調べたい。

**Comment by yucao24hours** [comment]
#729 の方針にのっとり、現時点でアクティブでなさそうな issue についてはひとまず close させていただきました。
ただし、「今後これの話はいっさいしないで！」というわけではなく、あくまでも **今** ホットなものを open のステータスにしておきたいという私の希望からであって、他意はまったくありません。
私以外のどなたかが「これ必要！」と思った場合はぜひ遠慮なく reopen してくださいね :rose:
