### ISSUE TITLE
privateメソッドを定義するとき、裏では何が起こっているか？

### ISSUE THREAD

**Issue by waterlow** [yochiyochirb/meetups#627]
今日def式の戻り値がメソッド名のシンボルを返すようになったという話で、その理由として
```ruby
class MyClass
  private def method
    #...
  end
end
```
と書いた時にprivateメソッドが定義できるようにするため、ということでした。確かにprivateというクラスメソッドにメソッド名を引数として渡している感じがしてスッキリしました。
でもそうすると、
```ruby
class MyClass
  private
  def method
    #...
  end
end
```
上のように書いた時のprivateがものすごく気になってきます…。そこで、魔法の言葉「private」の裏では何が起こっているのか。完全には分からないにしても、どう解釈すればスッキリするのか調べたい！

**Comment by yucao24hours** [comment]
#729 の方針にのっとり、現時点でアクティブでなさそうな issue についてはひとまず close させていただきました。
ただし、「今後これの話はいっさいしないで！」というわけではなく、あくまでも **今** ホットなものを open のステータスにしておきたいという私の希望からであって、他意はまったくありません。
私以外のどなたかが「これ必要！」と思った場合はぜひ遠慮なく reopen してくださいね :rose:
