### ISSUE TITLE
Issue の整理をしたい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#729]
おかげさまでだいぶ賑わっている Issue たちですが、立てたまま閉じるタイミングがみつからない…というのもけっこうあるようなので、今アクティブだと私の独断と偏見で判定したもの以外はいったん close したいなと思っています。
で、「これ、もーちょっと話聞きたい（したい）」というのがあったら、ぜひ遠慮なく reopen していただきたい。あとで読み返して「ほ〜 :eyes: 」とか「わ〜 :relaxed: 」とか言えるのが文字情報のいいところだと思うので、ばんばん同じ Issue にログを残していっていいとおもうんです。もちろん新規に立てても :ok_woman: 

っていう方針で、いかがですか？？

**Comment by katorie** [comment]
いいと思います！

**Comment by yuki3738** [comment]
:+1:

**Comment by yucao24hours** [comment]
:pray:

**Comment by yucao24hours** [comment]
ひととおり close 作業を行いました！

**Comment by yucao24hours** [comment]
今やりたいことは終わったので close します。ありがとうございました！
