### ISSUE TITLE
チーム若杉

### ISSUE THREAD

**Issue by ta1kt0me** [yochiyochirb/meetups#749]
議論よう

**Comment by ta1kt0me** [comment]
LT形式の勉強家に参加することはちょくちょくある

**Comment by ta1kt0me** [comment]
Rail ハンズオンに、一時間半でペース早い

**Comment by ta1kt0me** [comment]
忙しくてこれないことが続いた場合とかどうフォローアップしようかな

**Comment by 5t111111** [comment]
## 運営・開催について

- 毎週開催という頻度について
毎週は参加できないので、例えば1ヶ月出れないときはついていけなくならないか？

**Comment by ta1kt0me** [comment]
issueとかでキャップする

**Comment by 5t111111** [comment]
20:00 〜 22:00 はちょうどよいと感じる。

**Comment by 5t111111** [comment]
場所も渋谷近辺が多いのは都合が良い

**Comment by ta1kt0me** [comment]
募集時に、バージョンを入力する必要があるが、手元にPCがない時、募集であせる。

**Comment by 5t111111** [comment]
Railsのバージョン確認が必須項目じゃなくてもいいんじゃないか。

**Comment by ta1kt0me** [comment]
rubyの始め方、入門編とかどう入るかという情報があるといいのか。

**Comment by 5t111111** [comment]
オススメ書籍など

**Comment by 5t111111** [comment]
ロゴマーク欲しい。

**Comment by ta1kt0me** [comment]
hubot有効活用したい

**Comment by ta1kt0me** [comment]
Hirobaみたいなのはやりたい。よちよちのメンバーが気軽に開催できるような形式にできないかな。
