### ISSUE TITLE
Gaku dorachan nekoteni

### ISSUE THREAD

**Issue by ManabuSeki** [yochiyochirb/meetups#751]
ここに書きましょう

**Comment by dorachan1029** [comment]
gaku_nekoteni_dorachan

**Comment by ManabuSeki** [comment]
KPT（ふりかえり・反省） について

このままFacebookで続けてみては

**Comment by dorachan1029** [comment]
その日思ったことはそのときしか分からないので…書き残せるのはいいですよね

**Comment by NEKOTENI** [comment]
一度に複数のスレッドが立っても、別に驚いたりはしないと思います。
『○○のスレッド！』って書いてありますし。

**Comment by dorachan1029** [comment]
自己紹介について…
・一日前はLGTMひとつでマージ
・一時間前はセルフマージ

**Comment by yucao24hours** [comment]
> 一度に複数のスレッドが立っても、別に驚いたりはしないと思います。
> 『○○のスレッド！』って書いてありますし。

こういうフィードバック、とてもありがたいです><

**Comment by yucao24hours** [comment]
貴重なご意見ありがとうございました。
#756 で管理している Issue に転記させていただきましたので、今後これらのコメントも含めて話し合いをすすめていこうと思います。みなさまもぜひ引き続きご希望などお聞かせください！ :ear:
