### ISSUE TITLE
第51回で使ったアジェンダを個別の Issue にして話し合いたい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#756]
改めまして 第51回ミートアップに参加いただいたみなさま、貴重なご意見をどうもありがとうございました。
私の進行がいまいちだったこと、議題として挙げていたものが多すぎたことなどがあって、時間が足りずに申し訳ないことをしてしまったなあと反省しています。ですが、私としてもできるだけ早い段階でみなさんとこれからの方針を決めていけたらいいなと思っています（なあなあにしていると危機感がなくなるのと、宙ぶらりんなことを気にかけている間に心のリソースを割かなければいけないので負担になりやすい）。

オフラインで集まろうとするとなかなかタイミングが合わないと思うので、先日の議題をひとつひとつ Issue にしてみることにしました。で、それぞれに対してコメントをつけてもらいながら流れをみて決めていこうかな〜と思います。

該当 Issue には 'カイゼン大会2014-2015' というラベルを貼っています。

**Comment by yucao24hours** [comment]
あ、もちろん、オフラインで話すとかハングアウトで話すとかも有りだと思うので、お気軽にお誘い合わせの上〜〜

**Comment by TakaakiFuruse** [comment]
ハングアウトもいいかもしれませんね。全体プレゼン->4-5人にわかれて作業とか。

**Comment by yucao24hours** [comment]
この issue に reference を貼ってた issue がぜんぶ close になったので、close します！
