### ISSUE TITLE
開催時間、曜日について

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#757]
#756 より。
今までの運営についてふりかえって、もっとよくさせることができないか考えるスレッドです。

# 曜日、時間
- 毎週月曜日にやっているということについて
- 20:00~22:00にやっているということについて

**Comment by yucao24hours** [comment]
既に出ているご意見を転記しておきます。

@ta1kt0me チーム
- 時間帯についてはちょうどいい
- しばらく来れなかった人は途中から参加しづらかったりする

**Comment by yucao24hours** [comment]
@katorie チーム

- 週始めだと業務におされて参加できない。
- 水曜日がノー残業デーなので参加しやすい。
- 金曜日は予定がはいりやすいので、参加しにくいと思う。
- 場所や時間にもよるかも。。
- 20時はちょうどいいかもしれない。
- 22時以降の終了時間は次の日に響くのできびしい。

**Comment by yucao24hours** [comment]
- **LGTM**

**Comment by yucao24hours** [comment]
- むしろ月曜日がよい！
- 時間も丁度よい！

**Comment by yucao24hours** [comment]
転記は以上です。

**Comment by yucao24hours** [comment]
先日あげてもらった内容を見る限りだと、開催時間については 20:00 ~ 22:00 のままでよさそうに読めますね。終わりの時間は引き続き、踏み抜かないように気をつけて進行していきます。

**Comment by yucao24hours** [comment]
曜日はどうなんだろう。月曜派と水曜派がいるもよう。ちょっと変えてみたりします？？わかんないけど。

**Comment by yucao24hours** [comment]
そういえば去年はミートアップ開始が 平均してだいたい10〜15分遅れでスタートしていた気がするので（主に私のセッティング遅れのせい）、今年はできるかぎり定刻開始を心がけようと思います。
参加者のみなさんにも、今まで以上にいろいろお願いすることがあるかもしれません… :bow:

**Comment by katorie** [comment]
ミートアップ開始時間を定刻通りに開始できるようにするために、
待ち合わせが必要な場合は、連絡係をゆかおさん以外の人にする、というのはどうでしょうか？
ゆかおさんは定刻で始められるように、先に会場入りしてスタンバイできるような仕組みがあればいいのかなと思いました。

**Comment by yuki3738** [comment]
:+1:

**Comment by yucao24hours** [comment]
それだととてもありがたいです :heart_decoration: 

こういった "私以外のかたに何かをお任せする" という時、一番悩むのは どこまで "お任せ" するのが迷惑にならない範囲（== 無理しないで出来る範囲）なのか、ということについてでした。
コミュニティ活動って強制的なものではないので、担当、みたいな言葉を使うのも違うような気がして。それが運用上よさそうであればそのほうがいいと思いますが、みなさんへの確認なしに「きっとみんな優しいからやってくれるよね」という姿勢ですすめるのは良くないことだと、ずっと思っていました。というのが、私のきもちです :bow:

**Comment by yucao24hours** [comment]
5ヶ月ほど経ちましたが、特段問題もなさそうなので、引き続き月曜日の 20:00 からでいきます！
ということで close します。
