### ISSUE TITLE
開催場所について

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#758]
#756 より。
今までの運営についてふりかえって、もっとよくさせることができないか考えるスレッドです。

# 場所
原則として、

- 第1月曜は beez 渋谷さん（有料）
- （空いていれば）第2月曜はスマートニュースさん
- 第3月曜は beez 銀座さん（有料）

それ以外の日は、さまざまな会社さんのオフィスをお借りして、遊びに行っている。

**Comment by yucao24hours** [comment]
- 渋谷ちょーどいい

**Comment by yucao24hours** [comment]
- 渋谷はみんなが出やすいぽい。
- beezさん、ちょっと狭いかもってときある。
- 様々な会社さんを定期的に（月一）とかで借りていると、恐縮してくるかも。beezさんとかのほうが気楽。
- 会社さんの会場を借りれる選択肢がたくさんあるとよさそう。
-貸し会議室どっかあるかな。

**Comment by yucao24hours** [comment]
**LGTM**
いろんなオフィスにお伺いできるの楽しい。

**Comment by yucao24hours** [comment]
- 銀座は行きづらいな〜。終わった後家が遠い〜と感じる。
- 渋谷の違うコワーキングスペースも利用してみたい。
- 色んなオフィス行くの楽しい。

**Comment by yucao24hours** [comment]
転記は以上です。

**Comment by yucao24hours** [comment]
場所っていう言葉にはふたつ意味があって、「地図上のどこか」と「どういった種別の空間なのか」に分けられるなあと気づきました。
「地図上のどこか」という意味での "場所" は、なかなか難しい問題ですね。それぞれのお住まいに大きく左右されることだと思うので、大きめのターミナル駅かどうか、とかで判断したらいいのかな。

**Comment by yucao24hours** [comment]
ひとまず銀座の beez さんは今後の活動場所から外そうかな…と検討中でございます。

**Comment by yucao24hours** [comment]
「どういった種別の空間なのか」という意味での "場所" は、すなわち「誰かのオフィス」とか「貸し会議室」とかそういう意味ですが、もうちょっと広めのコワーキングスペースを探してみますか。

と言いつつ、実はよちよち.rb 発足当時に都内のコワーキングスペースの値段調査などはひと通りしておりまして、beez さんが圧倒的に安価でかつクオリティも高かったため選びました。あとは一回1,000~2,000円/人 とかになっちゃうんですよね。。プロジェクタなどの備品を使うとオプションでもっとかかる、とか。

**Comment by yucao24hours** [comment]
まあでも当時と状況は変わっているし、もう一度探してみてもいいかもしれない。みなさんが一度に支払ってもいいと思える予算がどれくらいなのかによるので、そのへんはご意見をいただきたいところです。

**Comment by yucao24hours** [comment]
先日こちらのコワーキングスペースに連絡し、お借りできないかと聞いてみました :telephone_receiver: 

[CASE Shinjuku（ケイスシンジュク）| 東京都新宿区の高田馬場駅徒歩1分にあるシェアオフィスとコワーキングスペースが併設したメンバー制オフィス](http://case-shinjuku.com/)

原則としてこちらのスペースのメンバーとなっている（定期利用している、という意味らしい）方にスペースをお貸しするということはしているそうなのですが、CASE さんとしては今後新しい業態の展開をしたいと思っているところでもあるため、一度お会いしたいというお話をいただいています :confetti_ball: 
近日中に訪問予定。

**Comment by yucao24hours** [comment]
他にも「こんな :cool: なお店（会社）知ってるぜ :sunglasses: 」「ちょっと気になってて行ってみたい」というところの情報があったら、教えてくだされ。
ついでに「よちよち.rb っていうところで使わせてもらえたら嬉しいって言ってるんですが〜」とかちょこっと掛けあっておいてもらえるともっとありがたいでござる。（でも無理しなくていいでござる）

**Comment by yucao24hours** [comment]
CASE Shinjuku さまへ訪問してきました。
ビックリするくらいおしゃれで広くて、駅からも近いので本当にすばらしい場所でした。

お話をうかがったところ、やはり先に述べたように原則として会員限定のレンタルのスタイルのため、私たちにだけ特別に月曜の夜貸す…というのは厳しいとのこと。
ただ、今は特に開けていない土曜日に、今後はイベントを開催していきたいと思っているとのことで、その枠で（土曜日開催で）使用しないか？とのご提案をいただきました。その場合の使用料は、何時間滞在しても一人あたり 1,000 円とかなり安くしてくださるとのことです。

**Comment by yucao24hours** [comment]
お話をしているうちにご担当者様が三鷹にオフィスをお持ちという話題になり、私たちが Ruby をやっているということから「三鷹は Ruby をまちおこしに使っていたり、とても盛んなんですよ」という話へ（まちづくり三鷹、有名ですよね）。
担当者様「ここのコワーキングスペースにも、 Ruby を教えることができる仲間がいるんですよ。安川さんていうんですけど」
私「えっ、安川さんって沖縄の…！？」
担「そうです、ご存知なんですか？？」
私「知り合いです！」
担「！！！」
という流れで一気に盛り上がってｗ、安川さんのよしみで月曜夜の利用ができるように出来るだけ計らってみると言ってくださいました。ありがたや、ありがたや :pray:

**Comment by yucao24hours** [comment]
聞くところによると安川さんは CASE Shinjuku で CoderDojo を開いているらしく、次は 3月にあるとのこと。CoderDojo 自体の開催時間は 11:00~12:00。
で、そこでのメンターというかコーチというかお手伝いさんというか、を私たちがやって、それが終わったらよちよち.rb のミートアップ本番を（そのまま CASE Shinjuku をお借りして）始める、というのはどうか？とご提案をいただきました。
ただ、安川さんにはまったく確認を取らずにお話が出ただけなのでｗ、一度安川さんにも直接連絡をしてみようと思っているところです。

そうでなくても一度ぜひイレギュラーイベントとかで CASE Shinjuku さん使ってみたいなあ。雰囲気もよいしきっとみなさんも気に入ってくれると思います :relaxed:

**Comment by yucao24hours** [comment]
すみません、

> ひとまず銀座の beez さんは今後の活動場所から外そうかな…と検討中でございます。

と過去に書いたのですが、東京の東・南側にお住まいの方もいらっしゃるので、中央区あたりも活動範囲に含めさせていただこうと思いました。毎回というわけではないため、ご了承いただけると嬉しいです。

**Comment by katorie** [comment]
12人まででしたら、[ユビレジ](https://ubiregi.com/ja)（最寄駅：原宿）も是非ご利用ください！

**Comment by yucao24hours** [comment]
ありがとうございます :tulip: とても助かります。近いうちにお願いするかもしれません :bow:

**Comment by yucao24hours** [comment]
あれからユビレジさんにも大変お世話になっております :construction_worker: 

主催者のわたしが神田あたりに住んでいるということもあり、役得ということでその辺りで開催することもままありますが、原宿のユビレジさん、目黒のリブセンスさん、高円寺のヴァル研究所さん、表参道の grooves さんをメインに使わせていただくようになって、西側を生活圏内となさっている方にも比較的アクセスしやすいようになったかなと自分では思っております。

**Comment by yucao24hours** [comment]
今後も、よちよち.rb メンバーのみなさまのご縁がある場所（主にお勤め先）へお邪魔させていただけると嬉しいなと思いつつ、私自身もまわりでお邪魔できそうな場所があれば積極的におたずねしてみようと思っています。いろんなオフィスを拝見できるのたのしいし！
オフィスでなくても、おもしろそうなお店などもぜひご紹介いただけるとうれしいです。この前 katorie さんが教えてくれた caffice とか、かなりよさそうですしね :coffee: （ネットワーク以外...?）

**Comment by yucao24hours** [comment]
ということで close
