### ISSUE TITLE
参加者募集・応募について

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#759]
#756 より。
今までの運営についてふりかえって、もっとよくさせることができないか考えるスレッドです。

# 参加者募集・応募について
- Doorkeeper を使用している。
- 開催日の前の週の火曜日か水曜日あたりに募集開始をしている。

## 心配していること
yucao24hours 的にはイベントページを作成するコストがわりと無視できないサイズなので、wiki に書けるところは書いてできるだけ固定のテンプレートで済むようにしたい。（会場の場所とか、注意事項とか、待ち合わせ方法とか）

また、私がこんな風に思うくらいだから、参加するみなさんも、毎週のイベントで申し込みをする手間ってけっこう大変なのではないか。だとしたら、Doorkeeper ではなく他の手段を検討したい。（ただ、参加前に Rails のバージョンとか開発環境の確認とかはやっぱりさせてもらいたいな…とも思う）

**Comment by yucao24hours** [comment]
- 募集時に、バージョンを入力する必要があるが、手元にPCがない時、募集であせる。
- Railsのバージョン確認が必須項目じゃなくてもいいんじゃないか。

**Comment by yucao24hours** [comment]
- Doorkeeperが負担に思ったことはないし、Googleカレンダーに登録できるので、嬉しい。
- 直前のキャンセルは申し訳ないので、予定が確定してからギリギリで登録したい気持ちある。 (参加者の心構えとしてキャンセル(特に直前キャンセル)はやめるべきだよなぁ)
- rails -vはスマホからだと登録できないのが煩わしいので、スマホのメモに保存している。
- rails -vまでたどり着いていない人や、Rails4.1系使ってる人の参加はどう考えたらいいのかな？
- Rails Tutorial追いついてくれてるはずなら、Railsの環境は揃ってるはずでは？
-> Rails Tutororialが追いついてないくらいならフォローできるけど、環境が全くない状態だとフォローできないからでは？
-> 「おしえて.rb」では「Nitrous.io」を使っているらしい。

- DoorkeeperのAPIを叩いて、ゆかおさんの効率化できたらいいのに。
- Doorkeeperの募集を持ち回りにしてもいいのでは？例えば会場係さんにお願いとか。

**Comment by yucao24hours** [comment]
- Doorkeeperは嬉しい。Googleカレンダーへの連携機能が嬉しい。
- テンプレート化はした方がいいと思う。
- 募集する人をローテーションすることが可能であれば是非やります。(@yuki3738,@bonbo0605)
- johnもDoorkeeper経由
- 辛かったらいってもいいんだよ…！？

**Comment by yucao24hours** [comment]
転記は以上です。

**Comment by yucao24hours** [comment]
Doorkeeper 負担でなくてよかった。引き続き Doorkeeper でいきます。

**Comment by yucao24hours** [comment]
> rails -vはスマホからだと登録できない

これについては今回（第52回）の募集から、必須項目から外しました。「[初参加の方へ] 」という文言を入れて、初めて参加する方のみ記入をお願いしています。

**Comment by 5t111111** [comment]
Doorkeeperでイベント作ったことがなかったので、非公開でイベント作ってみました。個人的に勘違いしていたこととかがあったのでメモを残しときます。

> - テンプレート化はした方がいいと思う。

これってそういう機能があるのかと思ってましたが、そういうわけではないんですね。
入力は結局手動でする必要があるので、共通のテンプレートをwikiとかに外出しにできるようにしてその手間を最小限にしたいということで理解しました。

> - DoorkeeperのAPIを叩いて、ゆかおさんの効率化できたらいいのに。

イベント情報を取得するようなAPIはありましたが、イベントを作成するようなAPIが公開されているのは見つけられませんでした。すでにそういうAPIがある、というわけではないんですね。

じゃあどうすれは楽にできるか。
Doorkeeperのシステム上に限った話ですが、テンプレートとかはできるだけ用意するようにして、入力についてはゆかおさんがチラッと言ってたようにプログラムでやっちゃうのが一番楽そうに思えました。

幸いJSで通信したりしない素直なサイトだったので、Mechanize使ってRubyコードからイベント登録するところまでアッサリと行けました。

Doorkeeperイベント登録サンプル
https://gist.github.com/5t111111/bc016a24f2327624947c

プログラムで扱えるなら自由に便利にできそうなので一考の価値はあるかも。(ただしテストはろくにしてません…)

**Comment by yucao24hours** [comment]
@5t111111 こちらもすっかり遅くなってしまいましたが、ありがとうございます！めかないず〜

イベント作成は最近会場がある程度固定になってきて、前回のものをコピーして作ることが多くなったのでストレスレスになってきました。
2015年5月からはすでに参加したことがある人だけを対象にしているので `rails -v` もやってないですし、みなさんにとってのご負担も少なくなってきたのではないかなと思っておりますがいかがでしょうか。

**Comment by yucao24hours** [comment]
ということで、こちらは役目を果たしたという判断で close しようとおもいます！ありがとうございました :pray:
