### ISSUE TITLE
ミートアップ前の自己紹介について

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#761]
#756 より。
今までの運営についてふりかえって、もっとよくさせることができないか考えるスレッドです。

# 自己紹介について
## 初めて参加する方
- Gist を使って書いてもらう
- その URL を Issue に貼ってもらう

## 2回目以降の方
- Pull Request を使って書いてもらう。
- 他メンバーのレビューで LGTM が2つ以上ついたらセルフマージしてもらう。

## 心配していること
自己紹介ファイルを管理できるというのはとてもよいが、レビューの手間がとても気になっている。ミートアップ当日はたいてい平日なので、仕事があってレビュー時間が取れる確証はない人がほとんどだと思う。そんななかでレビューを強要するのは仕組みとしてちょっといけてないような気がしてならない。

## これからどうしよう
- レビュー制をなくす（ブランチ切って PR は送るけどすぐセルフマージしてもらう）
- LGTM ひとつでマージにする
- その他...

**Comment by yucao24hours** [comment]
- 一日前はLGTMひとつでマージ
- 一時間前はセルフマージ

**Comment by yucao24hours** [comment]
転記は以上です。

**Comment by yucao24hours** [comment]
むずかしいですね。。「マージをする」のが目的であれば上記のような対応でもいいと思うんですが、たとえば Markdown のミスを見つけてもらうとか、Git の扱いが間違っていないかとか、そういうことについてをレビューしてもらい「正しくきれいなものを作り上げる」のが目的だと、この方法ではまずそう。

**Comment by yucao24hours** [comment]
ちなみに Ginza.rb さんも PR 形式ですね（よちよち.rb を真似てくれたらしい）。willnet さんがひととおりマージしていらっしゃいますが、どういう判定をしているんだろう。PR 来たら機械的にマージ、なのかな。

**Comment by ta1kt0me** [comment]
承認欲求が満たされるのでレビューされるの嬉しいです。例えば、こんなことをチェックしてみましょう、とかっていうリストを用意してみてレビューの経験を重ねるといいかもしれませんね。

**Comment by ta1kt0me** [comment]
こんなのを見つけました。
https://guides.github.com/introduction/flow/

実際にPull Request投げる時に、どういう風にすればいいのか、図で可視化してくれています。英語なので抵抗はありますが、目に見えると自己紹介のプルリクの作り方がわかりやすくな理想かなって思いました。使えそうだったら取り入れてみるのもいいかもしれません。

**Comment by yucao24hours** [comment]
おおおすごい！！！そしてこれぜったい私が書いた wiki 参考にしてる！！！！（調子乗りました）

そういえばどこかに英語技術書の読書会をしていて英語訳に前向きな方がいらっしゃると聞いたことがあるような〜〜 :ear:

**Comment by ta1kt0me** [comment]
@yucao24hours  :skull::interrobang: 近いうちに〜ノ

**Comment by yucao24hours** [comment]
セルフマージの話だけ早めに決めてしまいたい。
別 Issue にするかな〜。

**Comment by yucao24hours** [comment]
> セルフマージの話だけ早めに決めてしまいたい。
> 別 Issue にするかな〜。

#1238 で issue 立てたのでこちらは close
