### ISSUE TITLE
運営で使用しているツール・サービスについて

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#762]
#756 より。
今までの運営についてふりかえって、もっとよくさせることができないか考えるスレッドです。

# ツールについて
- Facebook グループは、誰でも入れるようにする+よちよちでない Rubyist さんからも見られるようにすることで、「私たちのことを知ってもらう場所」として使っている。
- Idobata は原則としてよちよち対象メンバーのみの利用のため、メンバー間でのコミュニケーションツールとして使用。また、Github 通知によって開発促進をするためのツールともなっている。
- Github は主に wiki と Issue を活用し、決め事や決まったことの共有など、資産保管のために使用している。

**Comment by yucao24hours** [comment]
#763 で Facebook に投稿するのには抵抗があるという意見を見て、こういったサービスへの価値観は個人間でだいぶ差があるんだなと痛感しました。

おしゃべり、流れていい会話… Idobata
ミートアップ募集開始告知… Twitter, Facebook
よちよち.beer 等イベント告知… 主に Facebook, Idobata

**Comment by yucao24hours** [comment]
5月末現在のわたしの気持ちですが、正直、使うサービスが分散しているとメンテナンスがたいへん煩雑で運営のモチベーションが下がるのを感じるので、せいぜい Idobata と GitHub （必要に応じて Twitter）に絞りたいなというのが正直なきもちです。

**Comment by yucao24hours** [comment]
一方で、Facebook Group は「イベント」という強力な武器があるのだよなあ。
よちよち.beer のように、お店の予約などのように外部オペレーションと関連するイベントの場合は（キャンセルなどの都合がシビアに関わってくるので）FB Group だと要件にこたえきれないのだけど、ちょっとした出欠確認とかイベント告知にはたいへん便利なんですよね。

**Comment by yucao24hours** [comment]
いま思いついたけど、Idobata に「いままでよちよち.rb に参加したことのない人がよちよち.rbに向けてはじめの一声を投稿する room 」とか作るといいのかな。
そこは、既に参加していて投稿したことある人は発言しちゃだめ、というかんじに（それだけだと一方向でつまんないから、適宜くふうは必要そうだけど）。

**Comment by to0526** [comment]
基本運用はIdobata＋GitHubで良いと思います！
告知、雑談やミートアップの記録（github issue）、自己紹介ファイルの管理（PR）などバランスよく運用できていると思います
何か外部に発信したい時などにtwitterとかを使えばよいのかなと思いました
doorkeeperの話が出てきていませんがまた別のスコープの話になるんですかね？

イベント開催に関しては「よちよち関連のイベントを開催するときはIdobataで告知する」ということだけ徹底して、イベント自体の管理ツールは主催する人に任せちゃっていいんじゃないですかね〜（楽観的な気もしますが）
ただ今まで得た知見はどこかで共有できれば良いかもしれないと思いました（beerの件など）

Idotabaを見ればよちよちrb関連のことは分かる状態にできれば運用も楽になりみんな幸せだと思いました

> いま思いついたけど、Idobata に「いままでよちよち.rb に参加したことのない人がよちよち.rbに向けてはじめの一声を投稿する room 」とか作るといいのかな。

これはどういったきっかけでしょう？発言しやすい場を作りたいとかそんな感じですかね？

**Comment by yucao24hours** [comment]
コメントありがとうございます(_ _)

>doorkeeperの話が出てきていませんがまた別のスコープの話になるんですかね？
イベント開催に関しては「よちよち関連のイベントを開催するときはIdobataで告知する」ということだけ徹底して、イベント自体の管理ツールは主催する人に任せちゃっていいんじゃないですかね〜（楽観的な気もしますが）

これについては尤もですね。Idobata というひとつの" 入り口" を設定することで、常にそこを注視していればいいということになりますもんね。
現状、Doorkeeper と FB Groups でそれぞれやっていますが、特に「いちいち違うからどっち見たらいいかわからんわ！ :anger: 」ということでもなければ、そのような運用でいいように思っています。

ただ、これは参加者のみなさまには直接関係ないことなのですが、主催者として、これからよちよち.rb に参加しようかと思ってお問い合わせをいただく方や よちよち.rb というコミュニティの活動に興味がある外部の方（たとえば他のコミュニティの運営者様など）に対して

「よちよち.rb がこれからどんなイベントを企画しているかは ◯◯◯（統一先のサービス）を見れば一目瞭然ですよ！」

というご案内をしたいことがままあり、そういうとき「適時 Idobata に流れるんで Idobata を監視しててね」とはご案内しづらいなあと懸念しています。そもそも要件が違いますからね。。ユーザストーリーの「◯◯として」の部分が違う。
今は、そのようなお問い合わせが来た場合には私がそれぞれのイベントの日程を把握しながら「◯月◯日にはこのイベントが、✕月✕日にはこのイベントがあります」と文章で伝えて "運用でカバー" している状態です。もうちょっとお問い合わせが来るようなら、GH Pages とか使ってよちよち.rb のホームページ的なものを作ろうかなと思ってます。

**Comment by yucao24hours** [comment]
>"いま思いついたけど、Idobata に「いままでよちよち.rb に参加したことのない人がよちよち.rbに向けてはじめの一声を投稿する room 」とか作るといいのかな。"
>これはどういったきっかけでしょう？発言しやすい場を作りたいとかそんな感じですかね？

多くの方からお問い合わせをいただく中で、けっこうその内容が重複していることがあるのです。代表的なものは、「Rails チュートリアル会って自分みたいな初心者でも行けるんですか？」「本当に初めてなんですけど大丈夫ですかね？」あたりですかね。
なので、
- 既に同じような質問が出ていたときに、重複して質問・回答しなくてすむようにしたい（FAQ のような使いかた）

- 他にも初心者の人はたくさん参加しているから大丈夫だよ！心配しないで！ということを、会話ログを見て実際に感じていただきたい

という目的で、そういう部屋をつくろうと思いました。
あとは単に、心理的な壁を感じてもらわなくて済むようにという思いがあります。もう長く続いているコミュニティなので、まだ仲間に入っていない方からすると内輪感を感じさせてしまっているのかもしれないので（それが悪いと言いたいわけではないです :hand: ）。

**Comment by yucao24hours** [comment]
（メールというツールがメンドクサイ、というのもありますね...。メールをいただくこと自体はありがたいのですが、それとは別の話ですからね。）

**Comment by to0526** [comment]
> Idobata というひとつの" 入り口" を設定することで、常にそこを注視していればいいということになりますもんね。

それです！それが言いたかったんです！

まあでも、統一したほうが楽ですよね〜

DoorKeeperのイベント作成画面を見てみたのですが、詳細が決まっているイベントの募集にとても向いていて、逆に詳細を詰めるためにはFBや調整さんが向いているのかなと感じました。

で、外部アナウンスするということは詳細が決まっている事が多いと思うので、外部に対するアナウンスはDoorKeeperに統一していいような気がしてきました。

（ミートアップの募集もDoorkeeperでやっているので、そちらに倒したほうが楽かなぁ。というのもあります）

イベントの詳細を詰める段階では外部にアナウンスする必要はないと思っているので、特に縛りを設けず、使いやすいツールを使って、そして詳細が決まったらDoorkeeperにイベントを作ってアナウンスすればよいのかな〜と思いました（いま小田井さんに進めてもらっている合宿のような感じです）

**Comment by to0526** [comment]
> 多くの方からお問い合わせをいただく中で、けっこうその内容が重複していることがあるのです。代表的なものは、「Rails チュートリアル会って自分みたいな初心者でも行けるんですか？」「本当に初めてなんですけど大丈夫ですかね？」あたりですかね。

ふむふむ、なるほどです〜。メールだと似たような内容の返信も大変ですよね。

Idobataでwelcomeルームみたいなの作って、そこに書き込むようにしてもらえば我々も回答できて良い気がしました！

descriptionにFAQ書いても良いかもしれませんね〜

**Comment by yucao24hours** [comment]
もうそろそろ一年経っちゃうんだけど、読み返してみるにそこまで今は不便していないので、ひとまず今のままでいってみようと思います。
ご協力いただいたみなさま、ありがとうございました。
