### ISSUE TITLE
KPT（ふりかえり・反省）について

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#763]
#756 より。
今までの運営についてふりかえって、もっとよくさせることができないか考えるスレッドです。

# KPT（ふりかえり・反省） について
Facebook グループにて毎回のミートアップ後に専用スレッドを立てて、その日のよかったことや次は改善したいことをコメントしてもらう。（強制ではない）

## 心配していること
その日単位で情報をまとめられないので、過去にさかのぼりたいときにちょっと大変（本文検索できるので「第n回」とかのワードで調べればいいのだろうけど）なのと、一度に複数のスレッドが立つので関係ない人は驚いていそう。

## これからどうしよう
- やめてみる
- ミートアップの最後に時間をとって、ゆるふわっとやる。結果はメモして wiki にしたりして残す。
- その他...

**Comment by yucao24hours** [comment]
- このままFacebookで続けてみては
- その日思ったことはそのときしか分からないので…書き残せるのはいいですよね
一度に複数のスレッドが立っても、別に驚いたりはしないと思います。『○○のスレッド！』って書いてありますし。

**Comment by yucao24hours** [comment]
- FBで発言するのは、個人的に抵抗があるので、idobataとかGithubとかで振り返りをしたい

**Comment by yucao24hours** [comment]
転記は以上です。

**Comment by yucao24hours** [comment]
きっと同様に「Github は抵抗があって…」という方もいらっしゃるでしょうし、どうするのがいいんだろう。。。

**Comment by yucao24hours** [comment]
ほんとは、ふりかえりをミートアップ中にやりたいのですよね。Ginza.rb さんも p4d さんもそうしていて、すごくいい意見交換ができていたのを覚えています。サービスを介さないためそのサービスに対して個々がどう思っているかに全く影響されないので、意見が出やすいのでしょう。
ただ、今のミートアップの進行だと明らかに時間が足りない…。10分でいいから捻出できたら、そこで一度やってみたいなあ。

**Comment by yucao24hours** [comment]
それか、いっそふりかえりをしない。たのしかったらたのしかったでいいし、イマイチだったらイマイチだったなって思った人が Idobata とかで呼びかけてみる。もしくは私に打ち明けてもらって、私が代弁する。もちろん呼びかけるのは義務じゃないので、「イマイチだった！おわり、まる。」でもいい。

当たり前だけど、ふりかえりをすることはチームにとって義務なわけではない。Asakusa.rb はそういったシステマチックなことは一切しないけどああしてたのしくやっていらっしゃるし、なんていうか、必要ならやればいいし負担ならやめればいい、そういう位置づけかなって思ってます。

**Comment by ta1kt0me** [comment]
今は当日の議論をISSUEベースで進めているんで、最初は抵抗あっても少しずつ慣れていくのかなぁって気はします。毎回だと時間作るのは大変かもしれないので、復習会とかでやるのはどうでしょうか。

**Comment by yucao24hours** [comment]
Issue の使い方勉強会的な！？
（Github の使い方勉強会、になるのかな？）

**Comment by 5t111111** [comment]
経緯を全然知らなくて発言しますが、ミートアップの活動はほぼIssueベースで進めてるにも関わらず、KPTはFacebookを使う理由って何ですか？
想像してみるといくつか思いつく理由はありますが、FBじゃないといけない、というものは思いつかないので。
※ちなみに個人的にはFBでの発言は全然抵抗ないですけど。

**Comment by yucao24hours** [comment]
@5t111111 すっかり遅くなってしまいました(_ _)

> ミートアップの活動はほぼIssueベースで進めてるにも関わらず、KPTはFacebookを使う理由って何ですか？

これは、Facebook のほうが「ミートアップに参加していない人」も見ている割合が大きく、興味を持ってもらいやすいと思ったためです。
GH ってどうしても開発ガリガリやってる人じゃないと見てないことが多くて、よちよち.rb の性質上、GH だけで運営をすすめるっていうのはいかがなものなのかなあと思っていたのでした。

**Comment by yucao24hours** [comment]
...しかし時は流れ、KPT をする習慣がなくなったのであった。

KPT なくてもいいかなー、あまり変わらないかなーという思いで、私が勝手にやらなくなっちゃっただけなんですが、その後どうでしょうか。。
あった頃となくなった時点で比べてみて、変化や気づいたことなどあれば教えていただきたいです。前にも書いたんですが、主催者はどうがんばっても参加者の視点にはなれないので(_ _)特になければ、この issue 自体も close しちゃいます。

**Comment by yucao24hours** [comment]
ひとまず close しちゃおうかな。なにかお気づきのことがありましたら、ここへのコメントでも、直接メッセージでも、飲みの約束でもいただければ、喜んでおこたえします !
