### ISSUE TITLE
その他について

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#764]
#756 より。
今までの運営についてふりかえって、もっとよくさせることができないか考えるスレッドです。

既に挙がっている Issue の議題以外でご意見をお聞かせください。のスレッド

**Comment by yucao24hours** [comment]
- rubyの始め方、入門編とかどう入るかという情報があるといいのか。
- オススメ書籍など
- ロゴマーク欲しい。
- hubot有効活用したい

**Comment by yucao24hours** [comment]
転記は以上です。

**Comment by yucao24hours** [comment]
Hubot は今年絶対こき使います。

**Comment by ta1kt0me** [comment]
そういえば、過去の宿題一覧みたいなのあると、後で読み返してみておもしろそう。(ちょっと大変な気もするから分担してやるとか)

**Comment by yucao24hours** [comment]
そうそう、それ wiki に作りたい！と思っていたんですが大変そうで、結局やっていないのでした :innocent: 
分担、うれしいです！

**Comment by yucao24hours** [comment]
もちろん wiki じゃなくても

**Comment by 5t111111** [comment]
READMEの最初の「このブログ」ってところ修正しませんか？
LTレポートにもこのリポジトリへのリンクが載る予定ですし、来てくれた人が初っ端のリンクをクリックして forbidden だとちょい切ないものがある気がします。

**Comment by yucao24hours** [comment]
すみません。早急に対応します。。。

**Comment by 5t111111** [comment]
:pray:

**Comment by yucao24hours** [comment]
> READMEの最初の「このブログ」ってところ修正しませんか？

かなり時間が経っちゃってましたが、対応しおわってました。
:thought_balloon: それとは別に、README 一新したいな〜 なんとなく

> 過去の宿題一覧

こちらは、今はちょっと保留にさせてください :bow: 

https://github.com/yochiyochirb/meetups/issues/764#issuecomment-70360704 の内容はほとんど実現できたので（ロゴマーク以外は対応したような気持ちでいる）、こちらの issue は一旦 close しようと思います。
