### ISSUE TITLE
第52回 5t111111, bonbon0605, highwide, shin-chang 

### ISSUE THREAD

**Issue by 5t111111** [yochiyochirb/meetups#779]
「5.2 SassとAsset Pipeline」から

**Comment by highwide** [comment]
「あせパ」

**Comment by bonbon0605** [comment]
今日はアセパから

**Comment by bonbon0605** [comment]
public は今もあるけど、404.htmlとかが置いてある

**Comment by 5t111111** [comment]
app と lib の使い分け

**Comment by highwide** [comment]
sinatraでpublic/ 使った。Railsでは使ってなかった。

**Comment by highwide** [comment]
sprocketsがAsset Pipelineを提供してるのか！

**Comment by bonbon0605** [comment]
lib/	は、複数のアプリケーション間で共有するライブラリを格納するディレクトリ

**Comment by bonbon0605** [comment]
app/ は、

アプリケーションを格納するディレクトリ
主要なプログラムはこの配下に格納

**Comment by bonbon0605** [comment]
http://railsdoc.com/asset_pipeline

**Comment by highwide** [comment]
Assets Pipelineを提供しているのはSprocketsだとしたら、Assets Pipelineは厳密にはRailsの機能ではないかも！

**Comment by 5t111111** [comment]
DHHは2005年にデンマークからシカゴに引っ越した。

**Comment by bonbon0605** [comment]
37signals（37シグナルズ）とはアメリカ合衆国イリノイ州シカゴに本社を置く非上場企業でウェブアプリケーションを手がけている。

**Comment by highwide** [comment]
デフォルトのマニフェストファイルを書き換えるときってどんなとき？

**Comment by highwide** [comment]
assets precompileしたタイミングでassetが読み込まれているのは理解できるけど、`rails s`したときはいつassetが読み込まれている？？

**Comment by bonbon0605** [comment]
``*= require_self``はコメントの中に書く

**Comment by shin-chang** [comment]
コメントの中に書かないと、CSSが崩れました。（読み込めなくなる）

**Comment by highwide** [comment]
たぶん、コメントの中にいることをSprocketsのここで見ている。
https://github.com/sstephenson/sprockets/blob/f68df9ebb6ed7d4c9d0a9ff5f6f909cd6eee95da/lib/sprockets/directive_processor.rb#L49

**Comment by highwide** [comment]
http://docs.ruby-lang.org/ja/1.9.3/doc/spec=2fregexp.html

オプション

/pat/という正規表現の直後に以下のアルファベットを 置くことで、正規表現にオプションを指定することができます。

/pat/i 大文字小文字を無視する
/pat/m メタ文字「.」が改行にマッチするようになる
/pat/x コメント内の空白を無視する。コメントの仕様が変化する
/pat/o パターン内の #{} の展開を1回限りしかしない。

**Comment by 5t111111** [comment]
「5.2.1 Asset Pipeline」の「プリプロセッサ」の手前まで！

**Comment by ta1kt0me** [comment]
ステータスコード422

https://gist.github.com/rosylilly/3401612#422-unprocessable-entity

**Comment by yucao24hours** [comment]
:clap:
