### ISSUE TITLE
第52回 ta1kt0me, iKatsuki, pupupopo88, katorie

### ISSUE THREAD

**Issue by katorie** [yochiyochirb/meetups#781]
5.2 からでいいですか？

**Comment by ta1kt0me** [comment]
OKでーす

**Comment by katorie** [comment]
ファイ！

**Comment by ikatsuki** [comment]
OKです！

**Comment by ta1kt0me** [comment]
プリプロセッサエンジン

**Comment by ta1kt0me** [comment]
開けなかった...

**Comment by katorie** [comment]
http://rails.hatenadiary.jp/entry/2013/03/03/125801

**Comment by ta1kt0me** [comment]
wikipediaより
プリプロセッサ

> 特にコンパイラに対して使うことが多く、

**Comment by katorie** [comment]
- app/assets/
- lib/assets/
- vendor/asstes

の使い分けについて

**Comment by pupupopo88** [comment]
外部のソース（gem）とかをそのまま丸っと入れるのが vendor?

**Comment by ta1kt0me** [comment]
assetsってなんなんだろう

> http://dokechin.hatenablog.com/entry/2013/04/21/030856
> 静的なコンテンツ(Assets)という意味だったんですね。

**Comment by ta1kt0me** [comment]
libの肥大化!?

**Comment by katorie** [comment]
> (マニフェストファイルはCSSとJavaScriptには適用されますが、画像ファイルには適用されません) 

これ大事なのでは

**Comment by ta1kt0me** [comment]
コメントアウトされてるからうっかり消してうごかくなる

**Comment by ta1kt0me** [comment]
> Railsは、どのプリプロセッサを使用するかを、ファイル名の拡張子を使用して判断します。

かしこい

**Comment by ta1kt0me** [comment]
CoffeeScriptはエレガントで簡潔な言語

**Comment by pupupopo88** [comment]
>foobar.js.erb.coffee
>これって需要あるんですか？

@ta1kt0me サーバーサイドでインスタンス変数が使用できる様になる

**Comment by ta1kt0me** [comment]
> @ta1kt0me サーバーサイドでjsファイルにインスタンス変数が使用できる様になる

かも?...試してみたい

**Comment by pupupopo88** [comment]
バラバラになっているものを全部一つにまとめてくれるのなら、特定のページしか使わないものが大量にあった場合、余計なものも全部読み込むから逆効果にならないのかな

**Comment by katorie** [comment]
怖い話探してる感じになてる

**Comment by pupupopo88** [comment]
全部読み込むなら、予期してないところで処理走ったりしそう

**Comment by ta1kt0me** [comment]
素晴らしい機能

**Comment by ta1kt0me** [comment]
コンパイル > 機械語に訳してくれ〜

**Comment by ta1kt0me** [comment]
コンパイルしたファイルしかない...

**Comment by ta1kt0me** [comment]
pupoさん ソースコードない...

**Comment by pupupopo88** [comment]
プリコンパイルに満ちた世界

**Comment by ta1kt0me** [comment]
katorieさんのお父さんの話

**Comment by pupupopo88** [comment]
本を買ってきて機械語をまるまる写すkatrieさんのお父さん

**Comment by katorie** [comment]
5.2.2の前まで終わりました

**Comment by ta1kt0me** [comment]
そういえば、JSの使用ページを限定するやり方がありました :eyes: 
http://qa.atmarkit.co.jp/q/3037
