### ISSUE TITLE
第53回 ikatsuki,yucao24hours,katorie,takasuga

### ISSUE THREAD

**Issue by ikatsuki** [yochiyochirb/meetups#808]

**Comment by ikatsuki** [comment]
5.2.1Asset Pipelineのプリプロセッサエンジンからです。

**Comment by yucao24hours** [comment]
hi

**Comment by yucao24hours** [comment]
プリプロセッサエンジンとは…何度調べてもわからない〜

**Comment by katorie** [comment]
プリプロセッサ(preprocessor)とは、一般にある処理を行うソフトウェアに対して、データ入力やデータ整形などの準備的な処理を行うソフトウェアのことである。特にコンパイラに対して使うことが多く

**Comment by yucao24hours** [comment]
http://qiita.com/kidachi_/items/4c47b28b2a74c723d835#3-3
>各アセットを実行し、生のcssやjsを吐き出す。
その際どのプリプロセッサを用いるかは拡張子で判別する。
.scss（Sass）
.coffee（CoffeeScript）
.erb（ERb）
など

**Comment by katorie** [comment]
プリプロセッサっていう言葉を調べようとすると、チュートリアルが出てきちゃう循環参照

**Comment by yucao24hours** [comment]
最終的な成果物をつくるためになんかよしなにしてくれるのがプリプロセッサ？:+1:

**Comment by yucao24hours** [comment]
最終的な成果物：html, css, javascript

**Comment by yucao24hours** [comment]
あぷりうごかないかなしさ

**Comment by katorie** [comment]
http://www.tam-tam.co.jp/tipsnote/html_css/post5189.html

> ※前提

Sassを書けば勝手にCSSをいい感じに書いてくれる！というものではありません。
まだCSSにちょっと自信がない人は、まずはCSSに慣れたほうがいいです。
どんな効率化ツールを使うときでも、根本となる基礎はきちんと理解しましょう。

**Comment by yucao24hours** [comment]
```scss
.center {
  text-align: center;
  h1 {
    margin-bottom: 10px;
  }
}
```

えーー！！！！これが CSS の生の書き方かと思ってた（衝撃）

**Comment by yucao24hours** [comment]
http://css2sass.herokuapp.com/

てきとうに探したらあった

**Comment by katorie** [comment]
CSSたーーーーくさんかくと、Sassのありがたみがわかる

**Comment by yucao24hours** [comment]
```sass
#logo
  float: left
  margin-right: 10px
  font-size: 1.7em
  color: #fff
  text-transform: uppercase
  letter-spacing: -1px
  padding-top: 9px
  font-weight: bold
  line-height: 1
  &:hover
    color: #fff
    text-decoration: none
```
SASS のほうがかっこいい

**Comment by katorie** [comment]
`.sass`いいー

**Comment by yucao24hours** [comment]
リスト 5.8 http://railstutorial.jp/chapters/filling-in-the-layout?version=4.0#code-logo_css を見たところまでやりました！

**Comment by yucao24hours** [comment]
@katorie 「Sass とは何を指すのか」みんな「」
