### ISSUE TITLE
TakaakiFuruse,ManabuSeki,pupupopo88,keng5scal

### ISSUE THREAD

**Issue by ManabuSeki** [yochiyochirb/meetups#809]

**Comment by pupupopo88** [comment]
5.2.1Asset Pipeline の プリプロセッサエンジン から

**Comment by pupupopo88** [comment]
がくさんのAsset Pipeline講座

**Comment by ManabuSeki** [comment]
日本語じゃない

**Comment by pupupopo88** [comment]
初めて見るとSが多すぎて混乱しそう

**Comment by ManabuSeki** [comment]
http://www.buildinsider.net/web/rubyonrails4/0903

**Comment by pupupopo88** [comment]
Sass最初に使った時衝撃的だった。便利すぎる

**Comment by pupupopo88** [comment]
アンパーサンド &
まじか

**Comment by ManabuSeki** [comment]
# 劇的に向上していることを確認してみてください。

**Comment by pupupopo88** [comment]
>LESSではアットマーク@を使用しているのに対して、Sassはドルマーク$を使っていることはすぐにわかります。= bootstrap-sassが@も使えるようにしていた...

そうだったのかー！@変数ってピュアなSassの機能じゃなかったのかー！

**Comment by pupupopo88** [comment]
やばい @grayLight さんにメンション飛んでしまった

**Comment by ManabuSeki** [comment]
@grayLightさん　すいません

**Comment by TakaakiFuruse** [comment]
$footerColor; みたいに色を定義して置くとあとから色かえるときに楽､とかそんな使い方はしないのだろうか

**Comment by pupupopo88** [comment]
素晴らしいスタート切れた

Sass使えるとまじライフチェンジング

**Comment by ManabuSeki** [comment]
SCSS勉強します

**Comment by TakaakiFuruse** [comment]
Sassのほうがやっぱり後で買えたりするのが楽そう｡ふつーにＣＳＳとして書いてあとからリファクターでしょうか｡

**Comment by pupupopo88** [comment]
紛らわしいのですが、SassはSass記法とSCSS記法があって、チュートリアルはSCSS記法をとってます。
Sassはインデントで解釈するのでSlimみたいな感じですかね
http://nobyu.hatenadiary.jp/entry/20111009/1318137506

**Comment by TakaakiFuruse** [comment]
Sublime のパッケージありました｡早速インストール｡
http://book.scss.jp/about/c7/editor/st.html

**Comment by TakaakiFuruse** [comment]
＊グループ発表より
最近のＢｏｏｔＳｔｒａｐはキャメルからスネークケースに色の変数の表記方法が変わったらしい｡
なんでそんなことすんの？　（；´Д｀）

**Comment by ManabuSeki** [comment]
[Vim] vim で Scss や Sass ファイルをシンタックスハイライトさせる方法
http://qiita.com/tsumekoara/items/b02f88a4020cff089ab1
