### ISSUE TITLE
第53回 ohtsuka, hashcc, necojackarc, johnwquarles

### ISSUE THREAD

**Issue by to0526** [yochiyochirb/meetups#810]

**Comment by hashcc** [comment]
> johnwquarlesさん
更新の流れ
https://github.com/yochiyochirb/meetups/wiki#how-to-use-github
https://guides.github.com/introduction/flow/index.html

**Comment by to0526** [comment]
> 5.2.2ではSassをそれぞれ扱いました。

未来です

**Comment by hashcc** [comment]
- Asset Pipeline
  - アセットディレクトリ
  - マニフェストファイル
  - プリプロセッサエンジン

**Comment by to0526** [comment]
誰がコンパイルしている？
sprocketsは何者？

**Comment by hashcc** [comment]
Sprocketsの役割は？

**Comment by hashcc** [comment]
https://github.com/sstephenson/sprockets
> Sprockets is a Ruby library for compiling and serving web assets. It features declarative dependency management for JavaScript and CSS assets, as well as a powerful preprocessor pipeline that allows you to write assets in languages like CoffeeScript, Sass and SCSS.

**Comment by to0526** [comment]
sprocketsがコンパイルしているぽい

**Comment by hashcc** [comment]
コンパイル＆インクルード

**Comment by to0526** [comment]
sprocketsをGemfileから消したらエラー
NoMethodError in StaticPages#home

**Comment by hashcc** [comment]
http://blog.mah-lab.com/2014/11/24/angularjs-rails-code/
> Railsでは標準でSprocketsというライブラリを利用してアセットの統合＆Minifyを行うため、・・・

**Comment by to0526** [comment]
foobar.js.erb.coffee

coffeeの後にerbが来ると気持ち悪い

**Comment by hashcc** [comment]
foobar.js.erb.coffee
Coffeeコンパイル→ERB処理

**Comment by to0526** [comment]
使い道はあるのか？

**Comment by hashcc** [comment]
foobar.js.erbはまだわかる

**Comment by hashcc** [comment]
HTTPリクエストが増えることがどれくらいパフォーマンスに影響をあたえるのか定量的なデータがほしい

**Comment by to0526** [comment]
圧縮することによりどれくらい早くなるの？
本当に意味があるのか

**Comment by to0526** [comment]
定量的なデータがほしい

**Comment by to0526** [comment]
一回のhttpリクエストで一つのjsファイルしか持ってこれない、production環境なら一回ですむ

**Comment by hashcc** [comment]
http://www.wakhok.ac.jp/~tomoharu/web2004/text/index_c3.html#doc1_id676
[Webブラウザの働き]
これまで見てきたように、HTTPは要求と応答がペアになっています。１回の要求につき、１つのファイルしか取得できません。

**Comment by hashcc** [comment]
HTTPリクエストを削減する理由を書いてあるところ
http://t32k.me/mol/log/reduce-http-requests-overview/

**Comment by hashcc** [comment]
http://rails.hatenadiary.jp/entry/2013/03/03/125801
> ファイル名にハッシュ値がつくということは、内容が少しでも変わる度に別のファイル名で保存されるということです。以前にプリコンパイルされた古いアセットファイルが public/assets/ ディレクトリにずっと残ってしまいますので、毎回削除してからプリコンパイルした方がいいでしょう。

**Comment by hashcc** [comment]
> アセットファイル名にハッシュ値（MD5）を付加
> 例）application.css ⇒ application-908e25f4bf641868d8683022a5b62f54.css

**Comment by hashcc** [comment]
HTTP 2.0 / SPDY
http://html5experts.jp/komasshu/404/
