### ISSUE TITLE
第54回 katorie, ManabuSeki, yucao24hours

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#831]
[変数](http://railstutorial.jp/chapters/filling-in-the-layout?version=4.0#sec-5_2_2_2) から

**Comment by yucao24hours** [comment]
:+1:

**Comment by ManabuSeki** [comment]
hi

**Comment by katorie** [comment]
色を変数で表現できるとリーダブルかも

**Comment by yucao24hours** [comment]
ふつうなプログラミングだと、1回しか出てこない値ってあまり変数にしないことが多いけど、カラーネームとかだとたしかに変数に入ってたほうがわかりやすい！

**Comment by ManabuSeki** [comment]
3桁だけでも
これだけ表現できるのか
http://toriichi3.com/zatugaku6.7.html

**Comment by yucao24hours** [comment]
LESS の変数一覧を使うのであれば、`$lightGray` の宣言は必要ない

**Comment by yucao24hours** [comment]
うーむうーむ

**Comment by yucao24hours** [comment]
Bootstrap をあらかじめ使うことを定義しているので、LESS の変数を使える
`@` を `$` にすると、あとは変数名さえ同じであれば、内部的に LESS 変数として読み替えてくれるのでは！！！！！！！

**Comment by yucao24hours** [comment]
なんかわかってきた :tada:

**Comment by ManabuSeki** [comment]
# Sassがさすが

**Comment by yucao24hours** [comment]
:see_no_evil:

**Comment by yucao24hours** [comment]
Ruby を書くのに熱中してしまった

**Comment by yucao24hours** [comment]
Home を残したとこまで！

**Comment by ManabuSeki** [comment]
5.22まで

**Comment by yucao24hours** [comment]
`foo_url` と `foo_path` では生成される文字列（URL ）が違う！
