### ISSUE TITLE
第54回 highwide to0526 pupupopo88

### ISSUE THREAD

**Issue by pupupopo88** [yochiyochirb/meetups#832]
変数から
http://railstutorial.jp/chapters/filling-in-the-layout?version=4.0#sec-5_2_2_2

**Comment by to0526** [comment]
「変数」から

**Comment by to0526** [comment]
復習
bootstrap2 $lightGray
bootstrap3 $light-gray

**Comment by to0526** [comment]
色を変数にしたり、クラスにすると変えるとき大変
するなレベル

**Comment by to0526** [comment]
> LESSではアットマーク@を使用しているのに対して、Sassはドルマーク$を使っていることはすぐにわかります。

@は@importとかで使うのでは？

**Comment by highwide** [comment]
CSSで@を使うのは以下のとき。
@importルール, @charsetルール, @mediaルール, @pageルール

https://w3g.jp/css/guide/at_rule

**Comment by to0526** [comment]
https://w3g.jp/css/guide/at_rule

**Comment by to0526** [comment]
`@hogehoge:`コロンをつけたら変数？

**Comment by to0526** [comment]
いいんだ。そういうものなんだ

**Comment by highwide** [comment]
CSS回のテンションの低さは異常。

**Comment by pupupopo88** [comment]
ふ〜ん

**Comment by pupupopo88** [comment]
私は楽しいですよっ！？

**Comment by yucao24hours** [comment]
> CSS回のテンションの低さは異常。

ｶﾞﾝﾊﾞｯﾃｰ(∞*･3･*)ﾉ

**Comment by highwide** [comment]
SCSS！！！！１１超楽しい！！！１１１１
すごい劇的に！！！向上するよ！！！！！！！１１

**Comment by pupupopo88** [comment]
**レイアウトのリンクでRubyに戻るぞ！？！？**

**Comment by to0526** [comment]
変数の使いところがわからん
うめくみさん、はっしーさん求ム

**Comment by pupupopo88** [comment]
うっちーさん＜Rubyんところやりましょう

**Comment by highwide** [comment]
SCSSが便利なんじゃない、CSSが不便なんだ。

**Comment by pupupopo88** [comment]
**私はライフチェンジングしましたよ！？！？？！？！**

**Comment by pupupopo88** [comment]
このチーム怖い...

**Comment by highwide** [comment]
「最初はよくあるCSSかなって思ったんですけど、触っていくほど、SCSSの魅力を知って、今ではもう、SCSSがない人生なんて考えられないですね」

「今回のSCSSが一番おもしろかったです！」

「「「せーの！！」」」
「「「SCSSサイコー！！！」」」

**Comment by highwide** [comment]
ご丁寧に演習をやってたせいで退屈するクラスタ

**Comment by highwide** [comment]
Vimで、「d」とは別に、レジスタに入れずに純粋に文字を削除することがしたいときがある。どうすればいいんだろう。

**Comment by highwide** [comment]
Railsのルーティング、いろいろ書き方あるので混乱してしまう。
(レシピブック読書会でも思った記憶がある)

**Comment by pupupopo88** [comment]
http://railsdoc.com/routes

**Comment by to0526** [comment]
5.3.2まで終わりました
