### ISSUE TITLE
第54回 @bonbon,@ikatsuki,@yuki3738

### ISSUE THREAD

**Issue by yuki3738** [yochiyochirb/meetups#833]
はらへった

**Comment by bonbon0605** [comment]
:ramen:

**Comment by yuki3738** [comment]
:meat_on_bone:

**Comment by bonbon0605** [comment]
footerタグのルールが、劇的に向上している？

**Comment by yuki3738** [comment]
劇的(笑)

**Comment by bonbon0605** [comment]
``bootstrap-sassというgemを使えば、``

bootstrapはデフォルトLESSだということ？

**Comment by bonbon0605** [comment]
WikiよりBootstrap
```
モジュール化されており、LESSの様々な要素を実装している。
 bootstrap.lessにはコンポーネントのスタイルシートが含まれており、 
利用者は使用するコンポーネントを選択して、ファイル自体を修正できる。
```

**Comment by yuki3738** [comment]
SCSS(Sass)とLESSの比較とその結果
http://www.wan55.jp/column/detail/id=179

**Comment by bonbon0605** [comment]
bootstrapはSassもLESSもいけるから、
``bootstrap-sass``はSassを選ぶよ、という意味？

**Comment by bonbon0605** [comment]
名前付きルートとは？

``about_path``と書くけど、``static_pages/``はどこに行ってしまったのか？

**Comment by bonbon0605** [comment]
sudo xcodebuild -license

**Comment by bonbon0605** [comment]
.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/nokogiri-1.6.6.2/mkmf.log

**Comment by katorie** [comment]
:bento:

**Comment by yucao24hours** [comment]
:curry:

**Comment by pupupopo88** [comment]
:sushi:

**Comment by highwide** [comment]
:rice_ball:

**Comment by yuki3738** [comment]
:ramen:
