### ISSUE TITLE
Sendagaya.rb + よちよち.rb(2/16開催)で使うGist 回収場所

### ISSUE THREAD

**Issue by highwide** [yochiyochirb/meetups#845]
自己紹介で使うGistを、ここのコメントに貼っていってください :rabbit:

# 書いておいてほしい内容

* お名前
* ご職業
* 右のリンクを参考にした Rails 4 と Github に関するあなたのステータス [各技術のステータス | よちよち.rb](https://github.com/yochiyochirb/meetups/blob/master/member_status.md)  
※ ステータス「5」よりもできるという場合はその旨お書きください！
* Sendagaya.rb / よちよち.rbどちらから応募したか

# 自己紹介を既に push してある方は(よちよち.rbの方向け)

~~1. /members/ 配下のファイルを更新（更新がなければそのままで OK~~
~~2. reports/#{ミートアップ開催年月日}_{開催回}/ ディレクトリにコピー（こちらは、誰が参加したかがわかるようにするため、ファイル自体に更新がなくても行ってください :bow:~~

~~以上を行って Pull Request を出しておいてください。~~

(2月16日更新)

自己紹介を既にPushしてある方については、こちらでミートアップディレクトリにコピーしますので、特に作業頂かなくて大丈夫です。

既にコピー＆プルリクエストして頂いた方については、そのまま活用させて頂きますので、特に取り消しなどして頂く必要はありません。

**Comment by knjcode** [comment]
今回、初参加です。当日よろしくお願いします。
https://gist.github.com/knjcode/cce5844f2238257974f9

**Comment by 5t111111** [comment]
ペアプロ大会楽しみにしてます。よろしくお願いします。

すでに過去に `/members/` 配下に push した自己紹介がありますが、今回 Sendagaya.rb からの申し込みなので、念のため改めて Gist で書いています。

https://gist.github.com/5t111111/60ba21acf988718fc970

**Comment by osadake212** [comment]
ペアプログラミングというものに初めて参加します。よろしくお願いします。

https://gist.github.com/osadake212/06a682cc384f0815e35c

**Comment by nishio-dens** [comment]
Sendagaya.rbからの参加です。よちよち.rbは初参加です。
よろしくお願いいたします。

https://gist.github.com/nishio-dens/c1608b374b7a3f730130

**Comment by haazime** [comment]
初めて参加させていただきます。
https://gist.github.com/haazime/68182a92db9ce1116e7e

よろしくお願いいたします！

**Comment by kseito** [comment]
すいません、２回目参加でmembers/にmdファイルを追加してPushしようとしたら
The requested URL returned error: 403
というエラーがでてPushできないのですが、どうすればいいでしょうか。
自分で作成したリポジトリにはプッシュできたので、ssh keyの設定はできてるっぽいです。

**Comment by yucao24hours** [comment]
@kseito 過去に参加していただいた際に、こちらの Organization への招待メールをお送りしています。そのメールの URL をふんでいただくことで、このリポジトリへの push 権も付与されるようになっていますので、お手数ですがよろしくお願いします。
参考: https://github.com/yochiyochirb/meetups/issues/728#issuecomment-70340197

**Comment by kseito** [comment]
@yucao24hours 見落としてましたすいません。
無事プルリク送れますた。
ありがとうございます！

**Comment by hokkai7go** [comment]
Sendagaya.rbから参加します
ねんがんのよちよち初参加です
楽しみです。よろしくおねがいしまする

https://gist.github.com/hokkai7go/7a1c22610455be1c3c3b

**Comment by tkawa** [comment]
Sendagaya.rbから参加します
よろしくおねがいします！
https://gist.github.com/tkawa/9456d3556d1b8a83ae7f

**Comment by youchan** [comment]
どちらも初参加です。よろしくおねがいします。
https://gist.github.com/youchan/1bbfe5d67218b2e1c5f8

**Comment by shinoq** [comment]
はじめまして、初参加です。
よろしくお願いしますm(__)m
https://gist.github.com/shinoq/224ed2a01ad5f55b9d9a

**Comment by deme0607** [comment]
よろしくお願いします！
https://gist.github.com/deme0607/d091f022c0706fb2c236

**Comment by oakbow** [comment]
初心者ですがよろしくお願いします！
https://gist.github.com/oakbow/6ede17ceec4806610fc3

**Comment by kaekasui** [comment]
慌ててはりつけました。よろしくおねがいします。
https://gist.github.com/kaekasui/f7e6d0695b88ffc25d71

**Comment by fukajun** [comment]
https://gist.github.com/fukajun/d79337510639e14ac16c fukajun

**Comment by yucao24hours** [comment]
みなさま、改めまして先日はお疲れ様でした。また機会がありましたら、どうぞよろしくお願いします :whale:
