### ISSUE TITLE
るびまふりかえり用スレッド。

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#855]
@to0526 さんと @odaillyjp さんの舵取りにより、第50回 ミートアップ（LT 大会）のレポートをるびまに投稿することができました :tada: 
一般公開はまだですが、ひとまず草案提出までの一連のうごきについてふりかえりをするための会話録です。
いつでも誰でも書き込み可能！:pencil:

**Comment by yucao24hours** [comment]
hi

**Comment by to0526** [comment]
hi

**Comment by odaillyjp** [comment]
hi

**Comment by to0526** [comment]
とりあえず入稿できた

**Comment by to0526** [comment]
リタイアしなかった

**Comment by to0526** [comment]
自発的にプルリクが飛んできた

**Comment by to0526** [comment]
どん語

**Comment by yucao24hours** [comment]
そらそうよ

**Comment by to0526** [comment]
そら（ほげほげなら）そう（いう結果になる）よ

**Comment by to0526** [comment]
写真良かった

**Comment by to0526** [comment]
めも：レポート書きたいな〜という気持ちはLT前からあった

**Comment by to0526** [comment]
次は写真を積極的に撮るふうにしても良いかも

**Comment by to0526** [comment]
こたつ暖かい

**Comment by to0526** [comment]
皆で進められた

**Comment by yucao24hours** [comment]
> こたつ暖かい

:+1:

**Comment by to0526** [comment]
レビュー依頼とかしても、遅くても1週間以内に返事が来た感じ

**Comment by to0526** [comment]
書き直しレベルの大きな修正が2つあった

**Comment by to0526** [comment]
レポートは中々書かないので大変だった

**Comment by to0526** [comment]
筆者目線で書く

**Comment by yucao24hours** [comment]
> 自発的にプルリクが飛んできた

これすごーくうれしかった :relaxed:

**Comment by to0526** [comment]
個別記事大変だったが結果的に良かった

**Comment by to0526** [comment]
レポートとは、人によって考え方が違う

**Comment by to0526** [comment]
どこまでフォーマルにするか？

**Comment by to0526** [comment]
「全国デビュー」という言葉に釣られた :fishing_pole_and_fish:

**Comment by to0526** [comment]
レポート内容に密度があった

**Comment by to0526** [comment]
人数がちょうどよかったかも（10人強）

**Comment by to0526** [comment]
今まさにこうやって振り返りをしていること

**Comment by yucao24hours** [comment]
:clap:

**Comment by to0526** [comment]
P

**Comment by to0526** [comment]
特に序盤「一人でやってやろう」感があった（大塚）

**Comment by to0526** [comment]
beer幹事と引っ越しとかぶった

**Comment by to0526** [comment]
今思うと幹事は投げたら良かったかも

**Comment by to0526** [comment]
引っ越してすぐネットがつながらなかったので動画が見れずに逆に捗った感

**Comment by ta1kt0me** [comment]
お疲れ様でした！ :tada: 
当日写真をレポート用に狙いながら撮ればよかった :camera:

**Comment by ta1kt0me** [comment]
最初の方は早めにレビューできたけど途中から失速してしまった...(ほぼ任せきりに...)

**Comment by to0526** [comment]
@ta1kt0me コメントありがとうございます！

**Comment by yucao24hours** [comment]
@ta1kt0me :clap:

**Comment by to0526** [comment]
メンバーの巻き込みかた（？）難しいかった

**Comment by to0526** [comment]
tokyuさんは確固たるコミュニティ
レポート書くのが当たり前みたいな文化がある？

**Comment by to0526** [comment]
最初から「担当」という形で決めちゃうと辛いかも
最初は立候補で良いのでは？

**Comment by to0526** [comment]
押し付けではないが体制を整えておくとよかったかも

**Comment by to0526** [comment]
レポートを書いていることをちゃんと周するべきだったかも

**Comment by to0526** [comment]
どの程度認知されているのか？

**Comment by to0526** [comment]
（レポート関係ないけど）周知手段は何が良いのか

**Comment by to0526** [comment]
年末年始何もしなかった

**Comment by to0526** [comment]
コントと漫才の違い

**Comment by yucao24hours** [comment]
そらそうよ

**Comment by to0526** [comment]
トミーズ

**Comment by ta1kt0me** [comment]
> トミーズ

そういえば、解散の話聞かないけれどまだやっているのだろうか

**Comment by to0526** [comment]
関西ではレギュラー番組があるんやで

**Comment by to0526** [comment]
せやねん！
http://www.mbs.jp/seyanen/

**Comment by yucao24hours** [comment]
関西の野球情報は阪神が勝った試合しか放送さなれないらしい…すごい情報統制… :tiger:

**Comment by to0526** [comment]
連絡手段は個別が良いか全体が良いか
時と場合による

**Comment by to0526** [comment]
日にちが経ってしまったので内容をあまり覚えていなかった
→スライドがあったので書けた

**Comment by odaillyjp** [comment]
スライドをあげてくださった方、ありがとうございました

**Comment by to0526** [comment]
2~3人軸でできたら良かったかも

**Comment by to0526** [comment]
↑からtryです

**Comment by to0526** [comment]
ゆかおさんと相談する形になってしまうことが多かった

**Comment by to0526** [comment]
何人かで方針を決定できるようであればよかったかも

**Comment by to0526** [comment]
レポート班を固定せず、皆がなんかしらの担当をする

**Comment by to0526** [comment]
もしくは固定してしまうかどっちか？

**Comment by to0526** [comment]
例えば次の人のレポートを書くなど

**Comment by to0526** [comment]
数人で班を作って回していくのが現実的かな〜

**Comment by odaillyjp** [comment]
おまかせ

**Comment by to0526** [comment]
個人のことではなくコミュニティとしてのことなので、決めきることが難しかった

**Comment by to0526** [comment]
レポートは書いている人ではなくコミュニティとしてのことなので少し気を使った感

**Comment by to0526** [comment]
読む人は何を考えている？

**Comment by to0526** [comment]
フォーマルは無難

**Comment by to0526** [comment]
レビューしてなかったら暴走していた

**Comment by odaillyjp** [comment]
LT大会のときの仕事のとりあいがすごかったし。。。

**Comment by to0526** [comment]
「これやりたいけどどう？」って投げると結構協力してくれるかな

**Comment by yucao24hours** [comment]
ケーキ班 @katorie 、会場係 @bonbon0605 、bnk 班のみなさま、ありがとございました :pray: 
（るびまの話ではないけどｗ）

**Comment by to0526** [comment]
全員分書きたい

**Comment by to0526** [comment]
話した内容も大事だが参加していただいたということを

**Comment by odaillyjp** [comment]
名前を出すだけでも価値はあると思ってる

**Comment by yucao24hours** [comment]
なるほど勉強になる！

**Comment by to0526** [comment]
写真も

**Comment by to0526** [comment]
るびまが発信源となる？

**Comment by to0526** [comment]
レポートの目的によって書き方が変わってくるのでは

**Comment by odaillyjp** [comment]
レポートの目的は？
「何を話したのかを伝えたい」「頑張っている人の顔を広めたい」

**Comment by to0526** [comment]
内容しっかり目に書くのも良いし、参加者の名前を全員分出すのも良い

**Comment by yucao24hours** [comment]
今日のふりかえりでの話題はこんなかんじかな〜

**Comment by yucao24hours** [comment]
やっぱ issue にのこすのいいですね！

**Comment by yucao24hours** [comment]
おつかれさまでした！！！！！！！！！！！！！！！！！！！！！！

**Comment by to0526** [comment]
まとめブログ書きました
http://t-ohtsuka.hatenablog.com/entry/2015/02/25/230639

**Comment by yucao24hours** [comment]
無事に公開されました！:tada:
http://magazine.rubyist.net/?0050-YochiyochiRbLtEventReport

ということでこちらは close します。みなさまお疲れ様でした！
