### ISSUE TITLE
開発合宿に行きたい！

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#863]
2月も間もなく終わり、本格的に2015年の計画を立てていきたいな〜とおもっているところですが、去年やった開発合宿がとっってもたのしくていい経験になったので、今年もやりたいなと思っています！

## 候補地
- Ruby の birthplace 松江市
- 去年行ってみてとてもよかった 山喜旅館
- その他オススメあったら :pray: 

## 時期
未定

やりたいこととか、ここ行きたい！とか、なんでもコメント welcome :100:

**Comment by ta1kt0me** [comment]
:+1:  +1

**Comment by yucao24hours** [comment]
島根県のご担当者福田さん、Sprout.rb の主催をしている松岡さんからメッセージがきました。

```
加藤さん
お久しぶりです。松岡です。
松江市の福田さんより下記のようなご連絡を頂きました。
ご検討ください(^o^)/
--------------------------------------------------------------------
加藤さん（Cc松岡さん）
島根県東京事務所の福田です！
ご無沙汰をしております。
昨年のRubyWorld Conferenceの場で、松江市美保関町での合宿について改めてご相談をさせて頂けないかと思っております。
3月になり、県・市の来年度予算の状況も見えてきまして合宿の支援についても具体的にお話ができる状況になってまいりました。
加藤さんがお考えの合宿のイメージと、松岡さんがお考えのイメージ、これについてヒアリングさせていただき、支援内容もそれに則した形にしていきたいと思っています。
と、ということで、一度お伺いさせていただき（またはどこかで落ち合わせていただき）意見交換させいてただけませんか？
ちなみに、Skypeで松岡さんを繋いでMTGをやれたらなぁと考えております（松岡さんとは調整済みです）。
松岡さんが平日はご家庭のこともありお忙しいようで、平日であれば22時以降ならSkype参戦可能！とのことなのですが、加藤さんはその時間でMTGさせていただけそうな日がございますでしょうか？
※御社にその時間に入らせていただくのが厳しい場合、もし加藤さんがよろしければ県の東京事務所（永田町）までお越しいただければSkypeができる環境がございます。
ちなみに、もし加藤さんがご迷惑でなければ、土日であれば松岡さんももう少し早い時間の対応ができるとのことでした。
長くなったので整理します。
・皆さんのコミュニティの美保関合宿を実現したいです。
・県・市の支援メニューの参考にするため、合宿イメージのすり合わせと「あったらいいな」の内容をMTGしたいです。
・Skypeを使って松岡さんを交えてMTGしたいです。
・近いところでの日程候補は、
　3月7日（土）（20時くらい？）
　3月8日（日）（20時くらい？）
　3月11日（水）（22時くらい）
という感じでございます。
場所は、福田が御社（または加藤さんご指定の場所）にお伺いするか、加藤さんに永田町の県オフィスにお越しいただくか、というイメージでございます。
大変勝手なお願いで恐縮ですが（そして無駄に文章が長い・・・）、ご検討よろしくお願いします！
```

**Comment by yucao24hours** [comment]
言い出しっぺなのに大変申し訳ないのですが、身辺の状況がいろいろ変わってしまったため、私はこちらの合宿への参加を見合わせようかと思っています。
ただ、他のメンバーのみなさまの中で興味を持ってくれている方もいると思うので、そういった方々に引き継ぎをしたいと思います。ご希望の方はご連絡ください（早めだと助かります）。
企画自体を見送るという選択肢もあると思っているので、そういった方針に関するご意見もお待ちしています。

まずは先方に、打ち合わせの日時をもう少し後にしてもらえないか依頼してみます。

**Comment by odaillyjp** [comment]
Oh.
ゆかおさんが今年の開発合宿自体の企画を見合わせるということでしょうか？
3月中の日程での打ち合わせは参加できませんが、企画自体には興味がありましたので、僕が引き継いでも良いですよ。

**Comment by yucao24hours** [comment]
@odaillyjp ありがとうございます！
おそらく実際に合宿自体に行くのはしばらく後のことだと思うので、その頃に私の状況が変わっていれば参加したいのですが、普段のコミュニティの運営と併行して企画に関わるのはちょっと難しそうな状況なので、他の方へお任せしたいなと思った次第です。

現在、福田さんから「打ち合わせができそうな日程をいくつか提示してほしい」と言われている状況です。どなたか参加できませんかねえ。。

（不安なのは、松江市側で想定している人数（具体的にはマダ聞いていませんが）を満たすくらいの参加者がいるかまったくわかっていないことですかね。。やっぱりある程度お金をかけてくれることだと思うので、最低催行人数みたいなものがあるのでは、と勝手に想像。このへんもまず打ち合わせで聞いてみたいのですが。）

**Comment by odaillyjp** [comment]
承知しました！ゆかおさんは普段のよちよちの準備がありますし、合宿に関しては僕が引き継ぎます。

3月14日（土）か3月15日（日）でしたら終日時間が取れそうですので、その日時で打ち合わせが可能でしたら、松江市の合宿について聞いてきますよ。
福田さんにこの日時と私の連絡先（ourwers@gmail.com）を伝えていただけますでしょうか。

**Comment by yucao24hours** [comment]
ありがとうございます。今のところ Facebook メッセージでやりとりをしているので、そちらの会話へ追加させていただこうと思います。

ひとまず、ミーティングの日程を決めて、合宿についてお互いどういうことを考えているのかをすり合わせるのが最初のタスクだと認識しています。私としては「まだ何も決めていなくて、よちよち内の合宿参加希望者のみなさんと話しながら決めようかと思っていました」という感じです。なので、小田井さんが主導しつつ参加希望者のみなさんと話し合っていただくのがいいのかなあ。

**Comment by yucao24hours** [comment]
（ここからは個人的な想像による心配事）
ゆるデブさんがゴールデンウィークに3泊4日で松江市のその合宿支援施策にのっかって合宿に行くそうなんですが、交通費・宿泊施設費込で一人あたりの負担額が70,000円超だったらしいのです。
ゴールデンウィーク中ということもあって交通費が跳ね上がっているのは仕方ないと思うのですが、ちょっと簡単には出せる金額じゃないなあ〜〜という感じもしました。
「価格によっては行く（価格によっては諦める）」という人もいるかもしれないので、その概算も早いうちにわかるといいかもしれませんね。

**Comment by yucao24hours** [comment]
@odaillyjp FB メッセージのほうへ追加させていただきました！

**Comment by yucao24hours** [comment]
第一回打ち合わせ結果
https://github.com/yochiyochirb/meetups/issues/902#issuecomment-87336919

**Comment by yucao24hours** [comment]
前後してしまった。打ち合わせ時に話すことまとめ
https://github.com/yochiyochirb/meetups/issues/902

**Comment by odaillyjp** [comment]
リンクを張ってくださり、ありがとうございます。

よちよちで確認しないといけないことは以下の2つです。

- 「6月6日（土）〜6月7日（日）」か「6月13日（土）〜6月14日（日）」に開催する場合の参加人数

- 金曜日の夜（20:00羽田）に移動するか、土曜日の朝（06:30羽田）に移動するかを決める

**Comment by odaillyjp** [comment]
調整さんで参加人数の確認を行います。参加を考えている方は入力をお願いしますm(_ _)m
https://chouseisan.com/schedule/List?h=bef383b2f716449d93972c6e362f75a5

**Comment by yucao24hours** [comment]
みなさま、先日の匿名アンケートへのご回答ありがとうございました！すごくいい意見をたくさん聴くことができ、方針を決めるための大きな助けとなりました。お忙しい中協力していただけたことに大変感謝しています。

以下に今回の結果が集計されています。閲覧はどなたでもできます。（ただし、SNS 等でシェアすることはご遠慮ください。）
https://docs.google.com/forms/d/1phXKZPo0lJgI77TPlct86PS6hI2dg-oDkCYAX6qbeYY/viewanalytics

上記の結果をうけて小田井さんと相談し、このたびの松江合宿はいったん見送らせていただこうということになりました。
楽しみにしてくださっていたみなさま、申し訳ありません。

今回の判断の経緯等は以下のとおりです。
このあと以下の内容で松江のご担当者様へ連絡します。

---

おはようございます。加藤です。
合宿の件に関しての連絡なのですが、折り入っての話なので、私のほうから直接お話をさせていただくことにしました。

実は、この度検討していただいていた松江への合宿を、見送らせていただきたいのです。
かねてよりいろいろな配慮をいただいていた福田さんと松岡さんには大変申し訳ないのですが、よちよち.rb としては、今はまだ実現する時期ではないと判断したためです。

よちよち.rb ではこの度の合宿企画に関して、匿名でアンケートに回答していただきました。（ Doorkeeper のメンバーとして登録してくださっている方全員 https://yochiyochirb.doorkeeper.jp/members へアンケートフォームを一斉送信しました）
その質問内容と結果が以下に集計されています。
https://docs.google.com/forms/d/1phXKZPo0lJgI77TPlct86PS6hI2dg-oDkCYAX6qbeYY/viewanalytics

こちらを見ると、
- 企画自体には大多数のメンバーが前向きであること
- 費用に対しての懸念が大きいこと

がわかります。

また、やる内容としては「もくもく作業をすること」「現地の Ruby コミュニティのみなさんと交流をすること」「現地の文化や名産品をたのしむこと」といった、「普段生活している環境ではなく、その場所だからこそできること」を求める人がほとんどのように見受けられます。

このような結果から、今回の内容のままで合宿企画をすすめることは "よちよち.rb の総意としては" 適していないように思えたため、小田井さんや他のメンバーとも相談し、残念だがいったん見送りとさせていただこう、という結論に達しました。
 
せっかくのお話でしたのに、申し訳ありません。

**Comment by yucao24hours** [comment]
なお、「開発合宿」の企画自体はなくさず、今回のアンケートの結果を反映させて

- もくもく(たまにワイワイ)作業ができる
- ふだんの仕事や学業から離れた環境、だけど出費は大きくならない

といった内容で引き続き小田井さんのお力を借りてすすめていきたいと思っています。
（他にも企画進行に興味のあるかたがいらっしゃいましたらぜひお声がけください！！ :pray: ）

**Comment by yucao24hours** [comment]
以下の文章も書き添えておいた

---

アンケートの結果を見るに、もし松江へ訪問させていただくとしたら、"合宿" という枠組みではなく「Rubyist の聖地巡礼ツアー！」のような企画にして、存分に松江を堪能するための旅がいいのかなと思いました。
ただ、今回はみんな「コードを書けること」を重点的に考えていたため、ぜひ別の機会に実現できたらいいな、と思っている次第です。

**Comment by odaillyjp** [comment]
合宿とは別企画として、追加の質問が届きました。

---

・「Rubyistの聖地巡礼ツアー」の実施の可能性はあるか？今年の6月までで、2泊3日（金曜または月曜を含む）とした場合、何名程度ご参加いただける可能性があるか？
・その際に、2泊3日でおいくら程度の予算にしたいか？
・アンケートで「参加したい。もしくは、参加を考えているので予定を調整中である。」と回答された5名の方に、「2泊3日での参加が可能か？」と確認いただくことは可能か？
・アンケートで「やる内容にも場所にも興味はあるが、費用が高いため、参加をためらっている(もしくは参加しない)。」と回答された12名の方に、「予算がおいくらであれば2泊3日で参加可能か？」と確認できるか？

---

別企画となるため追加でアンケートを取る必要があるが、コミュニティに参加してくださっているメンバーの負担が増えてしまうので、追加アンケートを取れないかもしれないことを説明し、ご了承いただいています。

**Comment by yucao24hours** [comment]
開発合宿のはなし、そろそろ再開したいね〜という話をおだいさんと先日してました。
かつてしていた島根のお話と混ざってしまうので、新しく issue たてますかね〜？

**Comment by odaillyjp** [comment]
そうですね。一つissueが長くなり過ぎると見難いですし、新しくissueをたてましょう。
（一応、今週末に一度アンケートを取ろうと思っています。そのときにもう一度issueを立てようかなと）

**Comment by yucao24hours** [comment]
:LGTM:

**Comment by yucao24hours** [comment]
次回は、日帰り参加とかも可能にできたらいいのかな〜

**Comment by yucao24hours** [comment]
こちら、閉じても平気ですかね？何かやり残したことなどあれば教えてください👣

**Comment by yucao24hours** [comment]
ていうかこっちは松江の話をしていたときのやつなのか。じゃ、閉じても平気そうなので、閉じます！🙏 まずかったら reopen してください〜
