### ISSUE TITLE
第57回 yucao24hours, hashcc, katorie

### ISSUE THREAD

**Issue by katorie** [yochiyochirb/meetups#866]
hi

**Comment by katorie** [comment]
5.3.2 Railsのルートからです

**Comment by yucao24hours** [comment]
ラウトドットアールビー

**Comment by katorie** [comment]
> Railsチュートリアルでは、path書式を使用する一般的な規約に従い、リダイレクトの場合のみurl書式を使用します。これは、HTTP標準では技術的にリダイレクト後にフルURLが要求されるためです。

知らなかったー

**Comment by yucao24hours** [comment]
順調.rb

**Comment by yucao24hours** [comment]
\# TODO: ドレスコードをつけたミートアップをやる

**Comment by yucao24hours** [comment]
>Web共通の慣習

UI にもデザインパターンという概念があるらしい！

**Comment by hashcc** [comment]
な、なんばーさいん
http://en.wikipedia.org/wiki/Number_sign

**Comment by yucao24hours** [comment]
Rails チュートリアルハックだ！！

**Comment by hashcc** [comment]
スタブ＝Stub＝仮置きのモジュール実装

**Comment by katorie** [comment]
順風満帆.rb

**Comment by yucao24hours** [comment]
```sh
/Users/yucao24hours/work/yochiyochi/railstutorial/db/schema.rb doesn't exist yet. Run `rake db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/yucao24hours/work/yochiyochi/railstutorial/config/application.rb to limit the frameworks that will be loaded.
```

**Comment by katorie** [comment]
リスト5.34 最初のユーザー登録ページ (スタブ)
の前まで進みました！
すいすい

**Comment by hashcc** [comment]
■ウェブサイト向け
シニアが使いやすいウェブサイトの基本ルール http://www.amazon.co.jp/dp/4766126947
デザイニング・ウェブナビゲーション http://www.amazon.co.jp/dp/4873114101

■アプリケーション向け
デザイニング・インターフェース 第2版 ―パターンによる実践的インタラクションデザイン http://www.amazon.co.jp//dp/4873115310/
モバイルデザインパターン 第2版 ―ユーザーインタフェースのためのパターン集
http://www.amazon.co.jp/2-Theresa-Neil/dp/4873117038
