### ISSUE TITLE
第58回 odailly_jp ta1kt0me seki pupupopo88

### ISSUE THREAD

**Issue by pupupopo88** [yochiyochirb/meetups#880]

**Comment by ta1kt0me** [comment]
5.3.4RSpecを洗練させる から...?

**Comment by pupupopo88** [comment]
テストの為のメソッド
でもそのメソッドが正しいかどうか...
テストの為のメソッドのテスト？？？

＿人人人人人人人人＿
＞　いたちごっこ　＜
￣Y^Y^Y^Y^Y^Y^Y￣

**Comment by pupupopo88** [comment]
おだいさん：それはアンチパターンですよ

**Comment by ManabuSeki** [comment]
やりすぎ

**Comment by ta1kt0me** [comment]
コンテンツの文字列を比較するときに、i18n.tをcallして表示する文字列をテストしたい場合、テストの比較結果でもi18n.tを使うべきなのかな？

**Comment by ta1kt0me** [comment]
テストやめたい発言www

**Comment by ta1kt0me** [comment]
時間との戦い

**Comment by pupupopo88** [comment]
もや〜っとした構想しかなくてTDDはやるべきではない
こうすると、はっきりしたものがある時にやった方が良い

くっ.......

**Comment by odaillyjp** [comment]
TDDの話で盛り上がっている

**Comment by odaillyjp** [comment]
> もや〜っとした構想しかなくてTDDはやるべきではない

「やるべきではない」というより「TDDできない」というイメージかなと。
「この入力に対して、この返り値が欲しい」とかはっきりした答えがないとテスト書けないですし、無理矢理に書いても全部消すケースも多いですし。。。

**Comment by ta1kt0me** [comment]
研修でテストやる話

**Comment by odaillyjp** [comment]
http://devtesting.jp/tddbc/

**Comment by ta1kt0me** [comment]
https://github.com/mixi-inc/RubyTraining

**Comment by odaillyjp** [comment]
参考になるかどうかわかりませんが、私の参加レポートを貼っておきます。
http://shindolog.hatenablog.com/entry/2013/05/22/231311

**Comment by pupupopo88** [comment]
赤い文字が怖いよー

**Comment by ta1kt0me** [comment]
rspecのエラーを潰す会

**Comment by ta1kt0me** [comment]
テンプレートなかった...

**Comment by ta1kt0me** [comment]
タイトルコメントアウトしてた :scream:

**Comment by ta1kt0me** [comment]
:green_heart: :green_heart: :green_heart: :green_heart: :green_heart: :green_heart: :green_heart: :green_heart: :green_heart:

**Comment by ta1kt0me** [comment]
半角スペース地獄

**Comment by pupupopo88** [comment]
テスト用のメソッドで半角スペースが抜けていただけでした :scream:

**Comment by ta1kt0me** [comment]
should_notの罠

**Comment by ta1kt0me** [comment]
全員グリーンになった！

**Comment by pupupopo88** [comment]
5.3.4RSpecを洗練させる が終わりました
