### ISSUE TITLE
第60回 (3/16) yucao24hours ta1kt0me yuzoiwasaki pupupopo88

### ISSUE THREAD

**Issue by pupupopo88** [yochiyochirb/meetups#897]

**Comment by yucao24hours** [comment]
hi

**Comment by pupupopo88** [comment]
hi

**Comment by yucao24hours** [comment]
`get 'users/new` が、ダメな理由ってなんだろう（"Rails 風じゃないから" っていう理由じゃなくて、REST の観点から理由があるのなら、知りたい）

**Comment by pupupopo88** [comment]
RESTful勉強会で聞いてくる

**Comment by pupupopo88** [comment]
Railsチュートリアル最新の原著がRSpecじゃなくてminitestになってるっぽい

**Comment by pupupopo88** [comment]
newはget
Array.newみたいに空のインスタンスとってくるみたいなイメージ
createだったらpostじゃないとだめ

**Comment by yucao24hours** [comment]
ぜんぜん違うとこ読んでたすみません！

**Comment by yucao24hours** [comment]
CSS の第5章おわりましたよ！！！！！！！（うっちーとなく）

**Comment by pupupopo88** [comment]
あ〜やっとテストの章が終わったぞ〜

**Comment by yucao24hours** [comment]
>この章は長いうえに、学ぶことがたくさんあります

Oh... ganbarou

**Comment by yucao24hours** [comment]
>ある実践的な実験によると、多くのサイトの認証システムは膨大なカスタマイズを必要とするため、サードパーティ製品を変更して導入する場合にはシステムをゼロから作成するよりも多くの仕事を要するという結果が出ています。

**Comment by yucao24hours** [comment]
Git のブランチに、`-` と `_` とどっちを使う〜？

**Comment by yucao24hours** [comment]
ブランチ名スラッシュ使えるのか

**Comment by yucao24hours** [comment]
ブランチ階層化できるのすごい！！！

**Comment by yucao24hours** [comment]
シークウェル…！

**Comment by ta1kt0me** [comment]
スィークゥエル

**Comment by yucao24hours** [comment]
gem sequel tteiunoga aru

**Comment by pupupopo88** [comment]
→スィークゥエル
→そんなGemあったような
　https://github.com/jeremyevans/sequel
→Active Recordあるのにこんなん誰が使うねん！
→ピュアRubyで使ってました...
→すみませんゆとりなので...
→Active Record もつらくないですか！？

**Comment by pupupopo88** [comment]
SinatraでDB使うときはどうしますっけ？

それならPadrinoかRails使いましょうって話しに

**Comment by yucao24hours** [comment]
6.1.1 データベースの移行の直前までやりました！ :+1:

**Comment by yucao24hours** [comment]
Padrino のソースわからん

**Comment by yucao24hours** [comment]
嘘です！！
