### ISSUE TITLE
第60回 fried_shrimp gaku ohtsuka

### ISSUE THREAD

**Issue by to0526** [yochiyochirb/meetups#898]

**Comment by ManabuSeki** [comment]
hi

**Comment by shrimp78** [comment]
Hi :fried_shrimp:

**Comment by to0526** [comment]
:fried_shrimp: hi

**Comment by to0526** [comment]
リスト5.33 から

**Comment by ManabuSeki** [comment]
provide
http://qiita.com/sue738/items/eed0f2a4dc312e9bbe26

**Comment by shrimp78** [comment]
Provide久しぶりに見て忘れてました

**Comment by to0526** [comment]
適切なREST規約 (表2.2) に従っていません。

**Comment by shrimp78** [comment]
yeild 先輩

**Comment by to0526** [comment]
yield 先輩にパラメータを渡す :fried_shrimp:

**Comment by to0526** [comment]
http://qiita.com/take/items/7bb67276c785e223069a

**Comment by to0526** [comment]
" uniteをインサートモードでスタート
let g:unite_enable_start_insert = 1

autocmd filetype unite call s:unite_my_settings()

" Unite overwrite settings.
function! s:unite_my_settings()"{{{
  " エスケープで去る
  nmap <buffer> <ESC> <Plug>(unite_exit)
  nmap <buffer> <ESC><ESC> <Plug>(unite_exit)
  " インサート脱出
  imap <buffer> jj <Plug>(unite_insert_leave)
  imap <buffer> kk <Plug>(unite_insert_leave)
endfunction"}}}

**Comment by shrimp78** [comment]
5.5 きたで

**Comment by to0526** [comment]
6 きたやで

**Comment by shrimp78** [comment]
記念すべき６０回目のよちよちで６とつぬー

**Comment by to0526** [comment]
https://github.com/CanCanCommunity/cancancan

**Comment by to0526** [comment]
cancancan

**Comment by to0526** [comment]
cancanはユーザに権限を与えたりする感じ

**Comment by to0526** [comment]
> 加えて、既成品のシステムは内部がわかりづらいことが多く、ブラックボックスになっています。

ほんとよくある！ :fried_shrimp:

**Comment by shrimp78** [comment]
http://blog.qujami.com/images/DSC_qq0118500.jpg

**Comment by to0526** [comment]
https://github.com/NoamB/sorcery

**Comment by to0526** [comment]
義t

**Comment by shrimp78** [comment]
↑
めっちゃよくある :fried_shrimp:

**Comment by to0526** [comment]
http://e-words.jp/w/DDL.html

ddl

**Comment by shrimp78** [comment]
DDL　とは
http://api.ning.com/files/D1*nxuy077RnkvpJaL2hYMQrpCrJ3t6S59oLclX4Z9iEsHwFrvS0YAK3jxL0Olv5*xqvPHjqZ5manC59DgRWszLdNijlaNgI/SQL.PNG

**Comment by to0526** [comment]
db/migrate/20140519122451_create_users.rb

みたいな？

**Comment by to0526** [comment]
カスタムビルドクラスのUser

さよならしたユーザ

**Comment by shrimp78** [comment]
大塚さん、去年の5月に未来に来てた

**Comment by shrimp78** [comment]
けど、未来は変わってた

**Comment by ManabuSeki** [comment]
過去と未来を行き来しててよくわからない

**Comment by to0526** [comment]
$ rails generate model User name:string email:string

**Comment by shrimp78** [comment]
将軍「default値はString]

**Comment by to0526** [comment]
$ rails generate model User name email

stringはかかんでよい

**Comment by ManabuSeki** [comment]
migrationファイル生成時のコマンドでデフォルトはstringって知らなかった

**Comment by to0526** [comment]
リスト3.4やリスト5.29でアクション名を使用して生成した例と比較してみてください。

なにを？

**Comment by ManabuSeki** [comment]
# インクリメンタル!

**Comment by shrimp78** [comment]
何の時間だろう・・

**Comment by shrimp78** [comment]
Sekiさん「Time.zone.nowや！」

**Comment by to0526** [comment]
リスト6.2の直前まで

**Comment by to0526** [comment]
やりました

**Comment by ManabuSeki** [comment]
```rb
irb(main):013:0* Time.zone
=> #<ActiveSupport::TimeZone:0x007f9b91615bf0 @name="UTC", @utc_offset=nil, @tzinfo=#<TZInfo::TimezoneProxy: Etc/UTC>, @current_period=nil>
```

**Comment by ManabuSeki** [comment]
```rb
irb(main):016:0* Time.zone.now
=> Mon, 16 Mar 2015 12:42:24 UTC +00:00
```
