### ISSUE TITLE
今後の活動方針の変更についてのご相談です。

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#899]
昨今、自社システムに Rails を採用する企業が増加してきているという話をよく聞きますが、それに伴ってか よちよち.rb へのお問い合わせも確実に増えています。
お問い合わせの内容はさまざまですが、

- プログラミングをしたことがないのですが参加できますか？
- 今日参加したいのですが、Rails ってすぐインストールできますか？
- Windows しか持っていませんがどうしたらいいでしょうか？

といったものが多いです。

Rails を愛する仲間が増えることは純粋に喜ばしいことですし、先代よちよチストとしても、自分が通ってきたような苦労と不安の道をたどろうとしている方々を迎えて一緒に自信をつけていきたいという気持ちはとても大きいです。
これは、既によちよち.rb に何度も参加してくださっている方もきっと同じではないかなと想像します。

しかし、私たちがすすめてきた Rails チュートリアルも、前回のミートアップをもってついに第6章（データモデリングを詳しく勉強する章）に入りました。
冒頭に書いたような質問をくださるようなよちよチストさんが新たに参加する会としては、あまりに技術的な前提レベルが高すぎるように思います。
（実際、そのレベル差にびっくりして次回から参加しなくなってしまったというご意見を幾度となく聞いたことがあります。）

「プログラミング歴2年以内」の方**すべて**を参加対象とするのであれば、ハローワールドからの方々でも気負いなく参加できる場を用意するのが筋ではないかと私は考えました。

そこで、以下のようによちよち.rb の活動方針を変えることを検討しています。

### 1.  技術的前提を（ほぼ）作らないミートアップを行う
毎月第2月曜日夜のもくもく会のほかに、毎月第3土曜日昼間にもくもく会をやる。時間が長いので、午前は Rails 関係の話題についてトーク/研究する会、午後はもくもく会、としてもいいかも。
もちろん参加は今までどおり任意とする。
（試しに今月から実施し募集を開始しているが、既に15名を超える申し込みがあり、半数が初参加の方であるので、気にかけてくれていた方が潜在的にいたんだということがわかる。）

### 2. Rails チュートリアル会は準クローズドに
今まで継続してきている Rails チュートリアル会は原則として準クローズドとする。 
具体的には、

- **現時点で GitHub の meetups リポジトリに push 権がある方** のみを対象とする
- すすんで新規参加者を募らないが、「前回のところまでをやってあることを前提にしている」という条件を了承してもらえるようであれば、新たに参加していただくのはまったく構わない

というスタンスにする。

## 現時点で出ている懸念事項
- Rails チュートリアル会については、なんらかの形で「今まで参加したことのある人のみ」に告知しイベント参加者を募る必要がある。必要であればイベント用ツールも Doorkeeper 以外のものに変える。

## いつから
早ければ 4月のミートアップから上記の変更を行おうと思っていましたが、それだとみなさんの意見をお聞きする時間が足りなさそうなので、5月からでいいかなと思っています。
また、準クローズドにする少し前から 外部へ告知する必要もあると思いますので、遅くても4月中旬ごろくらいには告知文を出せるといいな、という状態でいます。

感想やご意見などありましたら、ぜひコメントください。よろしくお願いします。

**Comment by katorie** [comment]
よさそう :clap: 
そっか、よちよチストの変化もあるけど、周りも大きく変化してきているのですね。
それに合わせて活動方針を変えていくことは、全面的に賛成です :raising_hand: 

そうすると、2のチュートリアル会は毎月第1、3、4、（5）月曜ということになるということであっていますか？

**Comment by yucao24hours** [comment]
コメントありがとうございます!

> 2のチュートリアル会は毎月第1、3、4、（5）月曜ということになるということであっていますか？

はい、そのとおりです。

**Comment by yucao24hours** [comment]
（GitHub の meetups リポジトリに push 権がある方… GitHub API で取得…なんかどっかで聞いたことあるな…！）

**Comment by yucao24hours** [comment]
ひとまず、簡易 クローズド運用として、Idobata の meetup ルームを「ミートアップに来たことがある人だけが参加できるルーム」にする。当日来てくれた人に直接、インビテーション URL を教える。外部に見える形で貼ってあるインビテーション URL へのリンクは削除する。

**Comment by yucao24hours** [comment]
Doorkeeper での募集開始も、そこでやる。…しかし、Doorkeeper の RSS feed を15分おきに Twitter に流す bot とかがいるし、既に Doorkeeper のメンバーになっている方もいるので、完全にクローズドにするのはむずかしそうだ。

**Comment by yucao24hours** [comment]
告知用ブログ書きました。
http://www.yucao24hours.me/2015/04/06/notification-for-yochiyochirb/

このあと SNS にリンク貼ります。

**Comment by yucao24hours** [comment]
無事に運用開始しました。ご意見・ご協力ありがとうございました！
