### ISSUE TITLE
合宿の打ち合わせで何を伝える？何を聞いておく？

### ISSUE THREAD

**Issue by odaillyjp** [yochiyochirb/meetups#902]
# このIssueで相談したいこと

3月28日（土）に島根県庁の方によちよち合宿のイメージの説明と合宿支援についてのヒアリングを行います。誤ったイメージを伝えてしまったり、合宿支援について聞き逃しまうことを避けたいですので、事前に「よちよち合宿のイメージ」と「合宿支援について聞くべきこと」をまとめておきます。どんな些細な意見でもokですので、何か思いついた方はコメントいただけますと嬉しいです。

# このIssueのクローズ条件

打ち合わせの報告をあげる

**Comment by odaillyjp** [comment]
# よちよち合宿のイメージとして伝えること

- 「『これを勉強したかった』『こんなのを作りたかった』など、普段は忙しくてなかなか取り組むことができなかったことを各自持ち寄って、合宿という集中できる環境を利用して一気に取り組もう！」というのが目的で2014年に合宿を行った。

- 前回の合宿が好評であり、また、2014年の合宿に参加したかったけど参加できなかった人も多かったので、今年も同じ目的の合宿を考えている。

- 他のコミュニティに比べて初心者が中心となるイベントなので、ハッカソンなどの高レベルなことはやらないつもり。

- 「必ず何かしらの成果を出す！」などは考えずに、ゆるい気持ちで参加できる合宿にしたい。

- 島根に行ったことがない人も多いので、少し観光ができるくらいの気持ちの余裕を持って参加できるようにしたい。

- 参加人数は不明。前回の合宿の参加人数は9人だったことは参考記録として伝えるつもり。

- 時期も未定。4月と5月はみんな忙しいようなので、6月以降にしたい。

- 日数も未定。時間とお金の都合を考えると土日の1泊2日か、どこか3連休を使っての2泊3日になると思われる。

# 合宿支援についてのヒアリング

- 時期はいつでも大丈夫なのか。

- 人数は何人でも大丈夫なのか。

- いつまでに連絡をしなければいけないか。

- 支援内容は何なのか。

- 合宿後に何か報告が必要なのか。

**Comment by pupupopo88** [comment]
ひとつ気になっていることなんですが、**松江に行く理由**ってなんでしょう :neutral_face: ?
松江に行くってそれなりにお金もかかりますし、そこをはっきりさせた方がいいかなぁという意見です。
変な話、ただもくもくするだけだったら近場でも日帰りでもいいですしね！

個人的には、せっかくなので現地の方々と交流の機会があってもおもしろそうかなと :smiley:

**Comment by yucao24hours** [comment]
コメントありがとうございます！

> 松江に行く理由ってなんでしょう  ?

そもそも私がこの「松江に行こう！」っていうのを言い出したのですが、その理由は
- Ruby の生まれ故郷だから Rubyist としては純粋に興味があるし、そういうところで合宿をできたらなんかテンションあがりそうだから
- 実際に松江に合宿しに行った人たちがみんなたのしそうだから

といった安直な思いつきからでした。

> それなりにお金もかかります

という点についてはご尤もで、非日常を味わいつつもくもく合宿をするのが目的であれば前回好評だった山喜旅館でもいいですし、それこそ都内のビジネスホテルとかなら交通費もほとんどかからないし、そちらのほうがいいと思います。
松江を選んだのは、Rubyist だから、です。それだけです。相変わらず無責任で、せっかく引き継いでくださった小田井さんにも申し訳ないです。
ただ、今までに2回松江に行って、やっぱりそれなりに感動した（松江駅前に Ruby のロゴが大きく貼りだされているオープンソースラボの様子などは、本当に嬉しかった）ので、"松江だからこそ味わえるもの" が全くないわけではないとも思っています。

私としては本当にただ「なんかたのしそう」という（いつも通りの）思いつきで言い出しているので、たとえばお金がものすごくかかるとか、合宿の企画を決めるのにものすごくたくさんの書類が必要とかで ちょっと実現までが大変そうだなという感じがあるなら、松江の方にはごめんなさいと伝えようかなと思っています。（その時はさすがに小田井さんにお任せしないで私から直接謝ります。小田井さんは何も悪くないですので！）
というわけで、値段がいくらくらいになるかっていうのはひとつ重要なファクターだと思っているため、大ざっぱでも構わないので早めにそれがわかっているといいなというのが私の希望です。

**Comment by odaillyjp** [comment]
料金はすごく大事な要素ですね。山喜旅館などの近場で合宿した方が料金は確実に安くなります。

ただ、例えば「山喜旅館で合宿するために必要な値段に5000円くらいを上乗せすれば、松江で合宿できる！」ということであれば、参加者の負担はそんなに大きくないですし、普通の観光目的で松江に行くより安く済みますし、噂で聞いた松江の「Ruby大歓迎！」という様子を見てみたいので、僕は松江で合宿してみたいです。1万円以上の上乗せが必要ならば、参加者がだいぶ減ってしまうと思いますので、そうなったら松江合宿は見送ることになるのかな……とぼんやり考えています。

今のところ、松江で合宿した場合に料金がどれくらいになるのか見当がついていませんので、料金についてはヒアリングしておきます。

松江側も合宿支援はボランティアではないですし、合宿後の報告がたぶん必要になると思いますので、参加者の負担が大きくなり過ぎないか考えて、合宿先を松江にするか決めたいです。

**Comment by pupupopo88** [comment]
いえ！実は私自身が「Rubyの聖地だから行ってみたいしモチベ上がりそう！」くらいにしか考えてなかったのですが、いろんな人が参加するとなった時にちゃんと説明出来るようにしておきたいなと思ったんです :bow: 小田井さんのおっしゃる通り、自分で観光に行くよりも歓迎されている感？味わえて良さそう！と思ってました :smirk: 

>松江側も合宿支援はボランティアではないですし、合宿後の報告がたぶん必要になると思いますので、

なるほど、そういう点もありましたね。それなら何か成果物出したいですね〜！


あと「思いつきでも何でもいいのでまず言ってみよう、やってみよう！」「共感できる人は乗っかろう！」というのがよちよちの文化だと思っていますので、そこは変に恐縮しすぎることはないかなと思っています。それによってみんなも気軽に発言できていますし、合宿などいい活動もできていますし。全部が全部うまくいくとは限らないので、普段通り「みんなで転んで、みんなで進んで」いければいいんじゃないでしょうか :smiley: 
と、合宿周りのこと全部お任せしてしまってる私が言うのもなんですが :sweat_smile:

**Comment by odaillyjp** [comment]
@pupupopo88 さん、@yucao24hours さん、コメントありがとうございました。
お互いに悪いようにならないように、頑張ってリスニングしてきます:heavy_check_mark:

**Comment by odaillyjp** [comment]
打ち合わせに行ってきました。長文になってしまうので、少しずつ書いていきます。

# 合宿内容

## 勉強

- 2つのコミュニティがコラボして合宿しているという様子を取材して、宣伝に使いたいので、スプラウト.rbと合同で合宿を行ってほしい。

- お互いもくもくしていても構わないが、別々の場所で開催しているコミュニティが集まるのだから、できれば2つのコミュニティが集まることを活かした合宿をしてほしい。

- 普段、スプラウト.rbは『Rails Tutorial』を各自でもくもくと読むということ行っている。

- スプラウト.rbはよちよちよりも初心者が多いコミュニティなので、ハッカソンやアイデアソンを行うは難しい。

- RubyWorldカンファレンスで、スプラウト.rbの松岡さんがゆかおさんから「よちよち.rbでは、みんなで『Rails Tutorial』を読んで勉強している」という話しを聞いた。よちよち.rbのIssueなどを眺めたが、「みんなで読んでいく」というのがどんなやり方なのか想像できないので、一度見てみたい。

- 「普段のよちよちのRailsTutorial読書会をスプラウト.rbと合同で行ってみるのはどうか？」という提案をしたところ、松岡さんは「よちよちの進め方に興味があったので、やってみたい！」とのこと。島根県庁の福田さんも「広報に使いやすいので、やってほしい！」とのこと。

- よちよちのRailsTutorial読書会は6章まで進んでいて、Railsをよく知らない人が今から参加するのは難しいことを伝えた。「ここまでは事前にやってきてください」ということを提示すれば、スプラウト.rbはそこまで事前にやってくるとのこと。また、スプライト.rbはよちよち.rbの進め方を見たり、交流したりすることを目的にしたいので、Railsを勉強することに拘らなくていい。

- よちよちで一度LT大会を行ったことがあることを伝えた。松岡さんは「LT大会は少しハードルが高いけど、挑戦してみてもいいかも」とのこと。

## 観光

- 島根県庁から何かしら観光になる企画を用意したい。

- クラウドワークスさんが合宿をしたときは「地引き網」を体験してもらった。
http://engineer.crowdworks.jp/2014/10/30/development-camp-2014.html

- 「地引き網」はすごく体力を使うが、大人数で協力して行うものなので、合同合宿の企画としては良い内容かもしれない。

- スケジュール次第では無しになるかも？他のことが決まってから、詳細を決めたい。

**Comment by odaillyjp** [comment]
# 時期

- 島根県庁の広報の都合上、6月上旬か中旬に行ってほしい。

- 6月6日（土）〜6月7日（日）、6月13日（土）〜6月14日（日）あたりが希望。

# 移動

- 羽田空港から飛行機で米子空港に移動。米子空港から送迎バスで美保関の旅館まで移動。

- 羽田発→米子着の飛行機は、20:00発が最終便。

- 前回の合宿のように、金曜の仕事終わりに移動することを考えると、羽田に20時より前に集合するのは難しいと思われる。

- 土曜日の朝に移動するとなると、06:30発が一番早い。

- 6時30分よりも前に羽田に集合できるかがネック。

# 支援内容

- 旅館の用意

- 送迎バスの用意

- Wifiやテーブルタップ、プロジェクタなどの機材の貸し出し（パソコンだけを持っていけば、大丈夫ないようにする）

- 交通費1人あたり1万の支給

# 料金

- 土曜日の朝に移動して1泊2日だとすると、およそ40,000円ほどかかる。

- 金曜日の夜に移動して2泊3日だと、およそ50,000円ほどかかる。

- 人数と時期が確定したり、福田さんが詳細の見積もりを出してくださる。

**Comment by odaillyjp** [comment]
# その他

> 合宿後に何か報告が必要なのか。

- 特に何も必要ないが、合宿の様子をブログなどに書いていただけると嬉しい。

- 合宿の様子を広報で使いたいので、写真を撮らせてほしいとのこと。

# よちよちで確認しないといけないこと（※大事※）

- 「6月6日（土）〜6月7日（日）」か「6月13日（土）〜6月14日（日）」に開催する場合の参加人数

- 金曜日の夜に移動するか、土曜日の朝に移動するか

**Comment by odaillyjp** [comment]
以上です。確認しないといけないことがいくつかありますが、このIssueのクローズ条件は完了しましたので、明日にでもクローズしようと思います。
確認しないといけないことは別Issueでやろうと思います。
