### ISSUE TITLE
第61回 yucao24hours task1010243 pupupopo88 ganchan0929

### ISSUE THREAD

**Issue by TasukuNakano** [yochiyochirb/meetups#911]

**Comment by yucao24hours** [comment]
:fried_shrimp:

**Comment by yucao24hours** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)

**Comment by pupupopo88** [comment]
:fried_shrimp:

**Comment by yucao24hours** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)

**Comment by pupupopo88** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)

**Comment by TasukuNakano** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)

**Comment by TasukuNakano** [comment]
http://railstutorial.jp/chapters/modeling-users?version=4.0#sec-database_migrations
から

**Comment by yucao24hours** [comment]
>メールアドレスをユーザー名にしたことで、理屈の上では将来ユーザー同士で通信できるように拡張できる可能性が開かれます

ユーザが一意になるから、ユーザを指定したやりとりができる、ということでは！

**Comment by TasukuNakano** [comment]
timestampはどこの情報を見て時間を決めているのか…？

**Comment by yucao24hours** [comment]
`t.timestamps` で使われるタイムゾーンは
http://api.rubyonrails.org/classes/ActiveRecord/Timestamp.html
で設定できる :en:

**Comment by pupupopo88** [comment]
デフォルトだと UTCらしい

**Comment by yucao24hours** [comment]
Rails の timestamps のデフォルト挙動が、Rails5 から変わるよという話
http://juanitofatas.com/2015/01/28/rails-5-timestamps/

**Comment by pupupopo88** [comment]
原文(Rails 4.2.0)は`t.timestamps null: false`って書いてありますね
https://www.railstutorial.org/book/modeling_users#code-users_migration

**Comment by yuzoiwasaki** [comment]
デフォルトカラムとして作成されるidの型は変更可能だが、integerのままがよい。

**Comment by TasukuNakano** [comment]
`id`という一意なカラムが決まっているなら、`email`という一意なカラムを任意で作る必要がないのでは…？

**Comment by pupupopo88** [comment]
http://goo.gl/CxkHVb

**Comment by yucao24hours** [comment]
migrating up っていうのしらなかった

**Comment by pupupopo88** [comment]
```ruby
create_table :books, id: false do |t|
  t.integer :book_id
  t.string :title

  t.timestamps
end
```

**Comment by yucao24hours** [comment]
"エスキューエライト" っていうの…その「エ」いるの…

**Comment by TasukuNakano** [comment]
「秘伝のDBが…！」

**Comment by pupupopo88** [comment]
秘伝のDBにはこれ使ってました
http://www.dehats.com/drupal/?q=node/58

**Comment by TasukuNakano** [comment]
Litaは私も使ったことありました

**Comment by TasukuNakano** [comment]
サンドボックスモードとは…

**Comment by yucao24hours** [comment]
>User.newを引数なしで呼んだ場合は、

の直前までおわりました！

**Comment by yucao24hours** [comment]
感想をかいてみようのコーナー

**Comment by yucao24hours** [comment]
デービーとかモデルとかは楽しい！モデリング好きだからうれしい！

**Comment by TasukuNakano** [comment]
やっとmodelの辺りに突入して楽しくなったきた。
SQLiteの読み方新鮮

**Comment by yuzoiwasaki** [comment]
modelの入り口だったので今日は大丈夫かな。次回から手強くなってきそう。。

**Comment by pupupopo88** [comment]
どんどん進んで楽しい！Railsは4.0と4.2でも違う、5.0だと更に違う、ということで怖いなと思いました（小並感）
https://camo.githubusercontent.com/41d9dd6e8e2a4f536fcc27095fd347672745f628/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f756e69636f64652f31663336342e706e67

**Comment by pupupopo88** [comment]
海老フライが食べたいです
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)

**Comment by yucao24hours** [comment]
これなんでもできるのかな…

:bow:

**Comment by yucao24hours** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f647.png)
