### ISSUE TITLE
第61回 ohtsuka, odai, kiyama, katorie

### ISSUE THREAD

**Issue by katorie** [yochiyochirb/meetups#912]

**Comment by odaillyjp** [comment]
ここから
http://railstutorial.jp/chapters/modeling-users?version=4.0#sec-database_migrations

**Comment by katorie** [comment]
https://github.com/katorie

**Comment by to0526** [comment]
:fried_shrimp:

**Comment by to0526** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)

**Comment by katorie** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)

**Comment by to0526** [comment]
https://camo.githubusercontent.com/41d9dd6e8e2a4f536fcc27095fd347672745f628/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f756e69636f64652f31663336342e706e67

**Comment by katorie** [comment]
![](chrome-extension://kgljgnbhcigffgoifhjbbifhbdkapmgm/images/emoticons/innocent.png)

**Comment by katorie** [comment]
`$ rails generate model User name:string email:string`
`$ rails g model user name string`

一緒とのこと

**Comment by odaillyjp** [comment]
```ruby
class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :name
      t.string :email

      t.timestamps
    end
  end
end
```

**Comment by to0526** [comment]
`$ rails generate model User name:string email:string name:string email:string name:string email:string name:string email:string name:string email:string name:string email:string name:string email:string name:string email:string name:string email:string name:string email:string`
ズラズラ書くのは辛い

**Comment by odaillyjp** [comment]
http://railsdoc.com/references/create_table

**Comment by kiyamatic** [comment]
t.string :nameのtはcreate_table :users do |t|のt。
なんでもいいけどなるべく分かりやすい名前に。

**Comment by kiyamatic** [comment]
ブロック変数

**Comment by to0526** [comment]
yomyomの宣伝

**Comment by to0526** [comment]
http://yochiyochi-yomyom.herokuapp.com/

**Comment by katorie** [comment]
https://github.com/katorie/rss_reader

**Comment by to0526** [comment]
```
[~/yochiyochi/rails_projects/sample_app]$ bundle exec rake -T b:m     *[modeling-users][2.0.0-p576] 
rake db:migrate         # Migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)
rake db:migrate:status  # Display status of migrations
```

**Comment by to0526** [comment]
「マジックカラム」とは

**Comment by to0526** [comment]
created_at、updated_atだけ？

**Comment by katorie** [comment]
http://www.sequelpro.com/

**Comment by katorie** [comment]
使用上の注意点 :skull:

**Comment by katorie** [comment]
6.1.1が終わったところです。

**Comment by kiyamatic** [comment]
データベースの削除 = drop

**Comment by to0526** [comment]
`$ bundle exec rake -T b:m`

-Tの後に何か書くとgrep的なことをやってくれる

**Comment by kiyamatic** [comment]
$ rails generate model User name:string email:string name:string email:string name:string email:string name:string email:string name:string email:string name:string email:string name:string email:string name:string email:string name:string email:string name:string email:string
みたいに長いと面倒なので一旦:stringで作ってrake db:migrateする前に直で編集したほうがいい。

**Comment by katorie** [comment]
またデータベースと仲良くなりたい

**Comment by odaillyjp** [comment]
英語力ほしい

**Comment by kiyamatic** [comment]
今まで見て見ぬ振りしていた部分を理解できて勉強になった

**Comment by yucao24hours** [comment]
おつかれさまでした！ :fried_shrimp:
