### ISSUE TITLE
第62回 iwasaki, iizuka, katorie

### ISSUE THREAD

**Issue by katorie** [yochiyochirb/meetups#926]
6.1.2からでいいですか？

**Comment by yuzoiwasaki** [comment]
オーケーです！

**Comment by katorie** [comment]
これからActiveRecord::Baseと仲良くなっちゃう

**Comment by katorie** [comment]
https://github.com/yochiyochirb/railstutorial

**Comment by yuzoiwasaki** [comment]
tail -fはみんな大丈夫。

**Comment by yuzoiwasaki** [comment]
同じ機能でtailfコマンドというのもあったりします⭐︎

**Comment by yuzoiwasaki** [comment]
ActiveRecordがSQL操作を隠蔽してくれるっ

**Comment by katorie** [comment]
たすかるっ

**Comment by yuzoiwasaki** [comment]
UTCのトリビアが！

**Comment by katorie** [comment]
create は new して save してくれる

**Comment by spagnios** [comment]
!は、例外を発生させる

**Comment by katorie** [comment]
ActiveRecordたすかるな〜

**Comment by spagnios** [comment]
User.countでユーザ数が返ってくるよ

**Comment by katorie** [comment]
`User.first` `User.last`

**Comment by spagnios** [comment]
PHPのPDOは古いよ。ちょっと簡単なテンプレート程度のもの。ORMとは違うよ。

**Comment by katorie** [comment]
6.1.4まで終わりました

**Comment by yuzoiwasaki** [comment]
PHPも今はオブジェクト指向で書けますし、優れたフレームワークやORMも多いです。PDOは少し昔の書き方なのかなという気がします。移行期の記法ですかね。

**Comment by yuzoiwasaki** [comment]
僕はPerlの人間なのでPHPはそれほど詳しいわけではないですけども(^_^;)
