### ISSUE TITLE
kiyamatic highwide task1010243 ManabuSeki

### ISSUE THREAD

**Issue by ManabuSeki** [yochiyochirb/meetups#927]

**Comment by ManabuSeki** [comment]
hi

**Comment by TasukuNakano** [comment]
:+1:

**Comment by TasukuNakano** [comment]
6.1.2のmodelファイルから

**Comment by kiyamatic** [comment]
rails console --sandbox 
rails c -s

**Comment by ManabuSeki** [comment]
```
rails c -s
```
でサンドボックスを起動できる

**Comment by ManabuSeki** [comment]
## マジックカラム
created_atとupdated_at

**Comment by TasukuNakano** [comment]
なぜ、`name`とか`updated_at`で呼べる？
→`name`,`email`はattr_accesorで呼べる
→マジックカラムとかidはRails側でよしなにやっている？

**Comment by ManabuSeki** [comment]
http://ref.xaio.jp/ruby/classes/array/frozen

**Comment by TasukuNakano** [comment]
↑
`foo = User.create(name: "Foo", email: "foo@bar.com")`
`foo.destroy`
の後に
`foo.save`はできる？って言う話

**Comment by ManabuSeki** [comment]
# 凍結状態を元に戻すメソッドはありません。

**Comment by ManabuSeki** [comment]
真実の愛でも溶かせません

**Comment by ManabuSeki** [comment]
```rb
irb(main):036:0* User.new
=> #<User id: nil, name: nil, email: nil, created_at: nil, updated_at: nil>
irb(main):037:0> u =User.new
=> #<User id: nil, name: nil, email: nil, created_at: nil, updated_at: nil>
irb(main):038:0> u.email = foo.email
=> "foo@bar.com"
irb(main):039:0> u.name = foo.name
```
これはいける

**Comment by highwide** [comment]
find_by_XXXってメソッド気持ち悪いのですが、、

http://railsdoc.com/references/find_by

3系では使えないみたいです :cry:

**Comment by highwide** [comment]
検索条件指定して全部取得するのは `where`

http://railsdoc.com/model#%E6%A4%9C%E7%B4%A2%E6%9D%A1%E4%BB%B6%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%97%E3%81%A6%E5%8F%96%E5%BE%97(where)

**Comment by TasukuNakano** [comment]
cookpadではマイグレーションを使っていないという話
http://techlife.cookpad.com/entry/2014/08/28/194147

**Comment by highwide** [comment]
ク社さんのActiveRecord運用方法

http://techlife.cookpad.com/entry/2014/08/28/194147

**Comment by highwide** [comment]
「こんなSQLを書きたいんですが、ActiveRecordではどう書けばいんですかね...」問題。

**Comment by TasukuNakano** [comment]
http://railstutorial.jp/chapters/modeling-users?version=4.0#sec-updating_user_objects
この前くらいまで

**Comment by highwide** [comment]
saveとsave!の違い。

http://d.hatena.ne.jp/masterpiyo/20111212/1323677704

**Comment by ManabuSeki** [comment]
6.1.5 前まで

**Comment by TasukuNakano** [comment]
(夜分遅くにすみません)
`destroy`メソッドの挙動
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/persistence.rb#L172-L186
