### ISSUE TITLE
第62回 yutackall talktome ikatsuki odaillyjp

### ISSUE THREAD

**Issue by odaillyjp** [yochiyochirb/meetups#928]

**Comment by odaillyjp** [comment]
6.1.2 から

**Comment by ta1kt0me** [comment]
生SQLのつらみ

**Comment by ikatsuki** [comment]
orやexistsが使いにくいので、SQLを直書きしたりする

**Comment by ta1kt0me** [comment]
arel使いたい人用
http://labs.timedia.co.jp/2013/10/activerecord4sql-arel.html

**Comment by ikatsuki** [comment]
[Arel](http://techracho.bpsinc.jp/tsunekawa/2013_05_24/8502)初めて知った！

**Comment by odaillyjp** [comment]
arel
https://github.com/rails/arel

**Comment by ta1kt0me** [comment]
マジックカラムって初めて聞いた

**Comment by ta1kt0me** [comment]
config.time_zone ... config.active_record.default_timezone...

**Comment by ta1kt0me** [comment]
http://qiita.com/joker1007/items/2c277cca5bd50e4cce5e

**Comment by odaillyjp** [comment]
デフォルトはUTC

**Comment by ta1kt0me** [comment]
cron はプロセス再起動しないと、timezone変更が反映されないという事実

**Comment by ta1kt0me** [comment]
destroyしても変数から参照できるのかー

**Comment by ta1kt0me** [comment]
reloadしても消えない

**Comment by ta1kt0me** [comment]
http://www.oreilly.co.jp/books/9784873116860/

**Comment by ta1kt0me** [comment]
delete の時の正しいレスポンスとはなんなのか...204？削除したオブジェクトの情報返す？リダイレクト？

**Comment by ta1kt0me** [comment]
RESTfulなdeleteとは。

**Comment by ManabuSeki** [comment]
```sh
# service crond restart
crond を停止中:                                            [  OK  ]
crond を起動中:                                            [  OK  ]

これで勝つる
```

**Comment by ta1kt0me** [comment]
6.1.3ユーザーオブジェクトを作成する おわった

**Comment by yutackall** [comment]
昨日の DELETE のステータスコードの件ですが、Heroku の APIデザインガイドだと、204 は使ってないみたいですね。
http://deeeet.com/writing/2014/06/02/heroku-api-design/

あと Web API  The Good Parts の該当箇所を見なおしてみましたが、PUT や PATCH メソッドでのデータ更新時も 204 で返すほうが自然みたいな意見もあるみたいです。
salesforce の API だと、PATCH の時に 204 が返るみたいです。
著者の見解だと、PUT、PATCH の場合は、200，POST は 201、DELETE は 204 でした。
Rails だと、routes.rb に メソッド ( get,post 等 ) が記載されて、ステータスコードはコントローラーに記載みたいな形になり、分散してしまうのが嫌ですね。
ApplicationController に各 API の正常終了の際のステータスコードを付与するようなメソッドかいて、after_action で実行みたいな感じですかね。

**Comment by ikatsuki** [comment]
APIの設計って、細かいとこまで仕様を決めないといけないんですね。
今までステータスコードまで考慮しなきゃいけない機会がなかったので、
ステータスコードについて考えるいい機会になりました。
いろいろ調べてくださってありがとうございます！
勉強になりました。
