### ISSUE TITLE
第63回 ikatsuki kiyamatic ganchan0929

### ISSUE THREAD

**Issue by ikatsuki** [yochiyochirb/meetups#944]

**Comment by ikatsuki** [comment]
6.1.4ユーザーオブジェクトを検索する

**Comment by yuzoiwasaki** [comment]
saveは必須

**Comment by kiyamatic** [comment]
更新するときにsaveする方法とupdate_attributesの使い分けどころが？？？

**Comment by kiyamatic** [comment]
db:migrate したデータベースをテスト用のdbに反映させてくれるのがdb:test:prepare

**Comment by kiyamatic** [comment]
DSL ドメイン特化言語

**Comment by ikatsuki** [comment]
RSpecは、RubyのDSL（ドメイン特化言語）。

**Comment by kiyamatic** [comment]
require 'spec_helper'
require 'rails_helper'

**Comment by kiyamatic** [comment]
リスト6.5 :nameと:email属性のテスト ←ここまで
