### ISSUE TITLE
第63回 odailly, kqtts, highwide

### ISSUE THREAD

**Issue by odaillyjp** [yochiyochirb/meetups#945]

**Comment by odaillyjp** [comment]
http://www.slideshare.net/YassLab/rails-46536321

**Comment by odaillyjp** [comment]
6.1.4から
http://railstutorial.jp/chapters/modeling-users?version=4.0#sec-finding_user_objects

**Comment by odaillyjp** [comment]
```
pry(main)> User.find_by(name: 'foo')
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."name" = ? LIMIT 1  [["name", "foo"]]
```

**Comment by odaillyjp** [comment]
where と limit を使ってみる
```
pry(main)> User.where(name: 'foo').limit(1)
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."name" = ? LIMIT 1  [["name", "foo"]]
```

**Comment by highwide** [comment]
`User.find_by`は1件のみ取得。(おだいさんが貼ってくれたSQLでわかるように `LIMIT 1`してる。
`User.where(hoge)` だと複数件取得。

**Comment by highwide** [comment]
`User.where(hoge).first` って気持ち悪いからどうしようという話を、Rails3レシピブック読書会でやっていた。

**Comment by highwide** [comment]
取得した結果が1件であることを期待するとき、`first` で取るべきか `last` で取るべきか。
-> どっちも変わらないのでは。 by おだいさん

**Comment by odaillyjp** [comment]
http://blog.livedoor.jp/sasata299/archives/51485638.html

**Comment by odaillyjp** [comment]
```
 it { should respond_to(:name) }
```

このメソッドを呼び出して、返り血がtrueならばテスト成功とする。
http://ref.xaio.jp/ruby/classes/object/respond_to

**Comment by highwide** [comment]
> 返り血がtrue
