### ISSUE TITLE
第65回 ganchan0929, highwide, kiyamatic

### ISSUE THREAD

**Issue by yuzoiwasaki** [yochiyochirb/meetups#962]

**Comment by yuzoiwasaki** [comment]
今日はバリデーション！

**Comment by yuzoiwasaki** [comment]
（まさに今日仕事で格闘したとこだ。。）

**Comment by yuzoiwasaki** [comment]
慣れてくるとFinderよりTerminalのほうが楽ですよ〜

**Comment by yuzoiwasaki** [comment]
pendingとは！？

**Comment by yuzoiwasaki** [comment]
#{__FILE__}はファイルのフルパスっぽい

**Comment by yuzoiwasaki** [comment]
アンダーバーがっ…

**Comment by highwide** [comment]
> テストデータベースはたまに壊れることがある

ファッ!?

**Comment by yuzoiwasaki** [comment]
何もしてないのに壊れることはないはず（祈り）

**Comment by kiyamatic** [comment]
ターミナルでフォルダを開いたりするように癖をつける

**Comment by kiyamatic** [comment]
tabキーで結構補完してくれる

**Comment by highwide** [comment]
`rake db:test:prepare`
で何をやってるかコード見ようとして断念。

**Comment by yuzoiwasaki** [comment]
Rubyのrespond_to?メソッドとは？

**Comment by kiyamatic** [comment]
describe　＝ 宣言
before = 準備してね
subject { @user } = it

**Comment by highwide** [comment]
Rubyのメソッド呼び出しにおける引数の()は省略すべきか。
参考: https://github.com/cookpad/styleguide/blob/master/ruby.ja.md#method-calls

**Comment by highwide** [comment]
Perlはreturn省略してもいいけど、書く人多いらしい！

**Comment by highwide** [comment]
RSpec先生がこれだけ自然言語に近づけようとしているのに、do/end挟むと残念な気持ちになるのわかる。
でも、複数行になるときは絶対にdo/end使うからしょうがない。

**Comment by kiyamatic** [comment]
$ bundle exec rake db:test:prepare はテストのdbを準備する。

**Comment by highwide** [comment]
`__FILE__` に関していい記事がありましたよ！
http://altarf.net/computer/ruby/509

**Comment by kiyamatic** [comment]
respond_to? = 反応する
