### ISSUE TITLE
第65回 yucao24hours, pupupopo88, zakioka, katorie

### ISSUE THREAD

**Issue by katorie** [yochiyochirb/meetups#963]
6.2 ユーザーを検証するからです

**Comment by yucao24hours** [comment]
:fried_shrimp:

**Comment by pupupopo88** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)

**Comment by katorie** [comment]
はじめての `$ bundle exec rake db:test:prepare`

**Comment by yucao24hours** [comment]
「壊れる」ってすごい表現

**Comment by pupupopo88** [comment]
理由もなく壊れる...!?

**Comment by yucao24hours** [comment]
before hook の話してる http://www.relishapp.com/rspec/rspec-core/v/2-13/docs/hooks/before-and-after-hooks

**Comment by pupupopo88** [comment]
テストの主題がsubject

**Comment by katorie** [comment]
`respond_to?`を暗黙的に使っている。。

**Comment by yucao24hours** [comment]
Ruby の「カッコつけなくてイイかんじ」は、初心者には最初びっくりするスタイルだよねーという話

**Comment by hirozaki** [comment]
カッコは慣れるといい

**Comment by pupupopo88** [comment]
RubyとRailsも文化が違う気がする

**Comment by yucao24hours** [comment]
か◯りえ先生のおトク情報が岡崎さんに継承されている！！

**Comment by yucao24hours** [comment]
https://camo.githubusercontent.com/41d9dd6e8e2a4f536fcc27095fd347672745f628/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f756e69636f64652f31663336342e706e67

**Comment by yucao24hours** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f364.png)

**Comment by katorie** [comment]
いきなり書きかた変わってるじゃん気持ち悪い

```
before do
    @user = User.new(name: "Example User", email: "user@example.com")
  end
```

**Comment by pupupopo88** [comment]
一文なので {} 派

**Comment by yucao24hours** [comment]
[リスト6.8](http://railstutorial.jp/chapters/modeling-users?version=4.0#code-failing_validates_name_spec) を書いたところまで！
