### ISSUE TITLE
spec 内で使われていた repond_to の正体は結局なんなのか

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#964]
[Rails チュートリアルの第6章](http://railstutorial.jp/chapters/modeling-users?version=4.0#code-user_spec) で出てきた `respond_to` というメソッド。
Rails 4.2 から gem として切りだされた [responders](https://github.com/plataformatec/responders) に移ったものという話を私がしたけど、結局それであってたのかな？[RailsGuides](http://edgeguides.rubyonrails.org/4_2_release_notes.html#respond-with-class-level-respond-to) を見ると `Class-Level respond_to` って書いてある（クラスメソッド）から、なんか違うんじゃないか。 :joy: 
ということで、続きを調べてみるスレッド。（参加自由です）

**Comment by ta1kt0me** [comment]
rspecの内容だとすると、[`respond_to` というmatcher](https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/respond-to-matcher)になるのではないだろうか。

**Comment by yucao24hours** [comment]
ありがとうございます ！　:exclamation:  やはり…きのうの皆さんにうそついてしまった :scream:

**Comment by highwide** [comment]
あれ、もしかして僕のRSpec説あってた？笑

**Comment by yucao24hours** [comment]
そうですね…すみません。。 :disappointed_relieved:

**Comment by highwide** [comment]
いえいえ、僕もあんまり確認せずに言っていましたし、RSpec内でどこでやってるかわからなかったのであまり変わらないですｗ

**Comment by yucao24hours** [comment]
気になったので定義場所もしらべてみました。
https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers.rb#L754
```ruby
    # Matches if the target object responds to all of the names
    # provided. Names can be Strings or Symbols.
    #
    # @example
    #   expect("string").to respond_to(:length)
    #
    def respond_to(*names)
      BuiltIn::RespondTo.new(*names)
    end
    alias_matcher :an_object_responding_to, :respond_to
    alias_matcher :responding_to,           :respond_to
```

ためしに、rspec-expectations の上記箇所に `binding.pry` を置いて、昨日やった `respond_to` の Rails チュートリアル中のテストを実行してみたら、以下のようになりました。

```sh
☹  be rspec spec/models/user_spec.rb
From: /usr/local/rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/rspec-expectations-2.13.0/lib/rspec/matchers.rb @ line 538 RSpec::Matchers#respond_to:

    537: def respond_to(*names)
 => 538:   binding.pry
    539:   BuiltIn::RespondTo.new(*names)
    540: end

[1] pry(#<RSpec::Core::ExampleGroup::Nested_1>)> names
=> [:name]
[2] pry(#<RSpec::Core::ExampleGroup::Nested_1>)> exit
.F
From: /usr/local/rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/rspec-expectations-2.13.0/lib/rspec/matchers.rb @ line 538 RSpec::Matchers#respond_to:

    537: def respond_to(*names)
 => 538:   binding.pry
    539:   BuiltIn::RespondTo.new(*names)
    540: end

[1] pry(#<RSpec::Core::ExampleGroup::Nested_1>)> names
=> [:email]
[2] pry(#<RSpec::Core::ExampleGroup::Nested_1>)> exit
```

`BuiltIn::RespondTo` クラスがなんなのかっていうところまでは追っていませんが、少なくともここで定義されているものを使っているのはまちがいなさそう（最近ずっと、「どこでどう定義されているのか気になる病」に苛まれているのであった :space_invader:  ）

**Comment by yucao24hours** [comment]
リファレンス :book: 
http://www.rubydoc.info/github/rspec/rspec-expectations/RSpec/Matchers:respond_to

**Comment by ta1kt0me** [comment]
ふとrailsのrespond_toはどんな時に呼び出すことができるのかなって思ったので後で見てみよう :eyes:

**Comment by yucao24hours** [comment]
みなさま、ありがとうございました！！クローズします。
