### ISSUE TITLE
第66回 ganchan0929, katorie, kqtts

### ISSUE THREAD

**Issue by yuzoiwasaki** [yochiyochirb/meetups#975]

**Comment by katorie** [comment]
hi

**Comment by katorie** [comment]
「6.2.2プレゼンスを検証する」からです！

**Comment by yuzoiwasaki** [comment]
validatesをmodelに書くとバリデーションが働いて不当な値は保存できないわけですね。

**Comment by yuzoiwasaki** [comment]
TDD（テスト駆動開発）

**Comment by yuzoiwasaki** [comment]
Rspecの....は成功したテストの数らしい。知らなかった！

**Comment by katorie** [comment]
Nokogiriこわい、ふたたび

**Comment by yuzoiwasaki** [comment]
Nokogiriはスクレイピングツール、らしい。

**Comment by yuzoiwasaki** [comment]
Nokogiriに襲われた時はbrew update!

**Comment by yuzoiwasaki** [comment]
シンボルとかハッシュとか混乱する

**Comment by katorie** [comment]
%記法の便利なはなし
http://qiita.com/mogulla3/items/46bb876391be07921743

**Comment by yuzoiwasaki** [comment]
リスト6.13まで終わりました〜

**Comment by katorie** [comment]
Nokogiriを使ったスクレイピング
http://morizyun.github.io/blog/ruby-nokogiri-scraping-tutorial/

**Comment by katorie** [comment]
> Nokogiriに襲われた時はbrew update!

私の場合はそれで逃れられたんですが、今回はダメでした。。

**Comment by yuzoiwasaki** [comment]
なんと。。

**Comment by ManabuSeki** [comment]
Ruby2.2で下記の方法でかけるようになりました

```rb
{
  "ヾ(*≧∀≦*)ﾉ": "寿"
}
```
#=> {:"ヾ(*≧∀≦*)ﾉ"=>"寿"}
http://sixeight.hatenablog.com/entry/2014/12/25/205411

**Comment by kqtts** [comment]
http://qiita.com/mist_dev/items/be2efa5913fa0fc861af
nokogiriはこれでいけたけど、また他のエラーがでた
